### ISSUE TITLE
Flaky Test - testAACasualtiesLowLuckMixedWithRollingMissRadar

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1005]
This test does not always pass or always fail:
```
games.strategy.triplea.delegate.WW2V3_41_Test > testAACasualtiesLowLuckMixedWithRollingMissRadar FAILED
    java.lang.AssertionError: expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at games.strategy.triplea.delegate.WW2V3_41_Test.testAACasualtiesLowLuckMixedWithRollingMissRadar(WW2V3_41_Test.java:227)
```

**Comment by DanVanAtta** [comment]
This has not failed in some time, is it actually flaky? 
Let's open  a new issue for any future flaky tests.
Closing this now..
