### ISSUE TITLE
`gradlew` run failing while reporting tests

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#1006]
`gradlew` is failing to complete, at the end of the test run, getting:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.platform.launcher.listeners.TestExecutionSummary.getTotalFailureCount()J
	at org.junit.platform.console.tasks.ExecuteTestsTask.computeExitCode(ExecuteTestsTask.java:101)
	at org.junit.platform.console.tasks.ExecuteTestsTask.executeTests(ExecuteTestsTask.java:65)
	at org.junit.platform.console.tasks.ExecuteTestsTask.lambda$execute$0(ExecuteTestsTask.java:52)
	at org.junit.platform.console.tasks.ExecuteTestsTask$$Lambda$3/1851691492.call(Unknown Source)
	at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
```

**Comment by DanVanAtta** [comment]
#1007 reverted Junit 5 - junit platform, error is no longer happening..
