### ISSUE TITLE
Latest prereleases (starting from 2721) do not run on (my) Win7.64

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1050]
2711 worked smoothly on my Win7.64.
This morning I installed the (then) latest 2724. It does not work.
Trying out the versions between those two, I found out that 2721 does not work either.
The last version I can confirm working on my system is 2715.

This is what happens trying to execute the newest versions:
After the splash screen the console window opens showing just nothing.
The process hangs now - I have to manually kill triplea.exe from the task manager.

I have been downloading triplea_windows-x64_1.9.0.0.27xx.exe in all cases.

**Comment by panther2** [comment]
I have found out that the error.log file is filled with tons of data within seconds, beginning with:

> Could not parse:jar:file:/C:/Games/triplea_2724/maps/tutorial.zip!/games/Tutorial.xml
games.strategy.engine.data.GameParseException: MapName: jar:file:/C:/Games/triplea_2724/maps/tutorial.zip!/games/Tutorial.xml, The following option name of territoryAttachment of class TerritoryAttachment are either misspelled or exist only in a future version of TripleA. Setter: isImpassible
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1358)
	at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1303)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:155)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.fullyParseGameData(NewGameChooserEntry.java:74)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel.selectByName(GameSelectorModel.java:341)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel.loadDefaultGame(GameSelectorModel.java:314)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel.loadDefaultGame(GameSelectorModel.java:265)
	at games.strategy.engine.framework.startup.ui.MainFrame.<init>(MainFrame.java:49)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$30(GameRunner.java:173)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

>

**Comment by DanVanAtta** [comment]
It's a problem with the map, not the game engine. We need to bump the tutorial version in the .travis.yml file that is part of the game engine. Fixing things across 100 some map's is a pain in the butt. At least though we are able to accomplish it, with SVN it was a no-go.

**Comment by DanVanAtta** [comment]
Will be fixed after this is built: https://github.com/triplea-game/triplea/pull/1051

PS: you are you going to need to update all 1.9 maps

**Comment by DanVanAtta** [comment]
please check again @panther2 with latest engine + maps

**Comment by panther2** [comment]
I can confirm that 2728 allows me to open the tutorial. I redownloaded some maps, too. While for example world_war_ii_v6_1941 opens fine, I cannot open world_war_ii_balanced or world_war_ii_global, getting this error message;

> triplea.engine.version.bin:1.9
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
Loading map: world_war_ii_v6_1941, from: C:\Users\User\triplea\downloadedMaps\world_war_ii_v6_1941.zip
Loading map: world_war_ii_v6_1941, from: C:\Users\User\triplea\downloadedMaps\world_war_ii_v6_1941.zip
Could not parse:jar:file:/C:/Users/User/triplea/downloadedMaps/world_war_ii_g40_balanced.zip!/games/ww2_g40_balanced.xml
games.strategy.engine.data.GameParseException: MapName: jar:file:/C:/Users/User/triplea/downloadedMaps/world_war_ii_g40_balanced.zip!/games/ww2_g40_balanced.xml, The following option name of territoryAttachment of class TerritoryAttachment are either misspelled or exist only in a future version of TripleA. Setter: isImpassible
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1358)
	at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1303)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:155)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.fullyParseGameData(NewGameChooserEntry.java:74)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.selectGameFile(GameSelectorPanel.java:423)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.access$200(GameSelectorPanel.java:46)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel$2.actionPerformed(GameSelectorPanel.java:226)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

>

**Comment by DanVanAtta** [comment]
Please check the repo for that map, and see if the XML contains: isImpassible or "isImpassable". Then also check the latest release is in the triplea_maps.yaml file, and last that you also downloaded that same version.

**Comment by panther2** [comment]
Found it. I have corrected the respective game.xml files and also the map.properties files.
See
https://github.com/triplea-maps/world_war_ii_g40_balanced/pull/9
and
https://github.com/triplea-maps/world_war_ii_global/pull/6

**Comment by panther2** [comment]
Just adding that the corrected files work fine in my local installation.

**Comment by RoiEXLab** [comment]
This happens on big world too...

**Comment by panther2** [comment]
@RoiEXLab 
Pull request to fix this is done, too:
https://github.com/triplea-maps/big_world/pull/2

**Comment by panther2** [comment]
@DanVanAtta 

Would you please merge

triplea-maps/world_war_ii_g40_balanced#9
and
triplea-maps/world_war_ii_global#6

too? The issue here can be closed then.

**Comment by panther2** [comment]
Everything fine now. Issue to be closed.
