### ISSUE TITLE
[Regression] Errors while playing against AI

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1064]
While working on the RouteDrawong thing, i noticed freezing on Map 270BC:
The AI cannot go further than Purchasing Units.
This is the StackTrace
```
java.io.NotSerializableException: games.strategy.triplea.delegate.dataObjects.BattleRecords$SerializationProxy
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at games.strategy.engine.framework.GameDataManager.writeDelegates(GameDataManager.java:247)
	at games.strategy.engine.framework.GameDataManager.saveGame(GameDataManager.java:224)
	at games.strategy.engine.framework.GameDataUtils.cloneGameData(GameDataUtils.java:25)
	at games.strategy.triplea.ai.proAI.ProAI.purchase(ProAI.java:195)
	at games.strategy.triplea.ai.AbstractAI.start(AbstractAI.java:425)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:525)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:419)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:271)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$0(AbstractLauncher.java:42)
	at java.lang.Thread.run(Thread.java:745)
```

EDIT: This doesn't happen on all Maps, not sure if this Issue should have been posted at the 270BC repo...

**Comment by DanVanAtta** [comment]
I'll see about taking a look at this tonight or tomorrow. @RoiEXLab , do you have a save game you could post/attach?

**Comment by RoiEXLab** [comment]
@DanVanAtta There's no need for a savegame... I'm just starting a normal local game on 270BC with Carthage AI on hard, and it freezes with an exception (the Console-Window won't open it's just the eclipse debug perspective which opens telling me about the stacktrace...)

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep, I can confirm that just starting 270BC with Hard AI as Carthage reproduces this error. Based on that stack trace, I'm pretty sure its something to do with the recent BattleRecords SerializationProxy changes.

**Comment by DanVanAtta** [comment]
See https://github.com/triplea-game/triplea/pull/1075  for a fix and details
