### ISSUE TITLE
Map Indexing Can Halt (OOM?)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#11138]
Map indexing is not consistently running on the lobby server. Logs have some out of memory errors preventing threads from starting (could be related, maybe not).

```
[72018.495s][warning][os,thread] Failed to start the native thread for java.lang.Thread "HandshakeCompletedNotify-Thread"
Exception in thread "Latest-Engine-Version-Fetcher" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:798)


[72035.653s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
[72035.653s][warning][os,thread] Failed to start the native thread for java.lang.Thread "pool-2251-thread-1"
```

**Comment by DanVanAtta** [comment]
solved! there were several other problems. This is one that is no longer an issue
