### ISSUE TITLE
2947: Error when trying to download games

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1139]
This happens after hitting "Download Maps":

triplea.engine.version.bin:1.9
java.lang.NullPointerException: Failed to download map listing from: http://raw.githubusercontent.com/triplea-maps/Project/master/production_config/triplea_maps.yaml?raw=true
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:228)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:81)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:72)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$layoutComponents$166(GameSelectorPanel.java:180)
	at games.strategy.ui.SwingComponents.lambda$newJButton$550(SwingComponents.java:165)
	at games.strategy.ui.SwingAction$2.actionPerformed(SwingAction.java:53)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:156)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by simon33-2** [comment]
I'm seeing this too.

In build 2947.

**Comment by RoiEXLab** [comment]
Can also confirm... Hmm thats weird

**Comment by RoiEXLab** [comment]
Could somebody test which version is the last working?

**Comment by panther2** [comment]
While downloading with 2882 worked fine until yesterday, I now get the same error with that version.

**Comment by RoiEXLab** [comment]
@panther2 That means, that there's an issue with the triplea-maps.yaml file... https://github.com/triplea-maps/Project/commits/master/production_config/triplea_maps.yaml Who messed up ? \:D

**Comment by panther2** [comment]
No idea, worked fine yesterday.

**Comment by RoiEXLab** [comment]
Ok tested older versions - still not working.
@DanVanAtta any ideas? also, please merge #1141 before starting a fix...

**Comment by RoiEXLab** [comment]
@DanVanAtta From a Coders view:
This is extremly weird... the downloads field (which is a `private volatile List<DownloadFileDescription> downloads;` inside DownloadRunnable.java) is null, due to the fact that it hasn't been initialized when called...
I tried initializing it with a empty list, but that results in an empty download maps window.
This leads to the conclusion, that the method which is supposed to parse the yaml file isn't working, but it isn't throwing an exception either...
Inside DownloadFIleParser.java:
```
 public static List<DownloadFileDescription> parse(final InputStream is) {
//Code here is executed
    @SuppressWarnings("unchecked")
    final List<Map<String, String>> yamlData = new Yaml().loadAs(is, List.class);
//before this code is being executed, the nullPointer is being thrown...
```

I really have no clue what could be causing this...

**Comment by RoiEXLab** [comment]
@DanVanAtta OK I know now, why no error was thrown... The code was in a try catch-block with the error message being passed in a variable, but not printed.
There seems to be the following parse error:
```
Error while Parsing
while parsing a block collection
 in 'reader', line 1, column 1:
    - mapName: ==HIGH QUALITY MAPS==
    ^
expected <block end>, but found BlockSequenceStart
 in 'reader', line 1500, column 2:
     - mapName: war_of_the_relics
     ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:513)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:198)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:153)
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:444)
	at games.strategy.engine.framework.map.download.DownloadFileParser.parse(DownloadFileParser.java:30)
	at games.strategy.engine.framework.map.download.DownloadRunnable.downloadFile(DownloadRunnable.java:73)
	at games.strategy.engine.framework.map.download.DownloadRunnable.run(DownloadRunnable.java:47)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$0(BackgroundTaskRunner.java:20)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by DanVanAtta** [comment]
We should be logging/printing that error message. I *just* fixed the formatting, should be working again now.

**Comment by RoiEXLab** [comment]
@DanVanAtta #1141 implements that

**Comment by RoiEXLab** [comment]
@DanVanAtta Is working fine for me again... This can be closed...

**Comment by panther2** [comment]
I can confirm it works, thanks for fixing. Issue closed.
