### ISSUE TITLE
TripleA 2.6.14483 Reproduceable - An unexpected error occurred! CRASH

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#11927]
Tested 3 out of 3 Crashes so hopefully Reproduceable.

Engine Version: TripleA 2.6.14483
Map = 1941 Global Command Decision v145 
https://forums.triplea-game.org/topic/3326/1941-global-command-decision-official-thread/537

Saved Game
[1z-autosaveBeforeEndTurn.zip](https://github.com/triplea-game/triplea/files/12488589/1z-autosaveBeforeEndTurn.zip)

### Reproduction Steps
**Load Saved Game**
When asked to Scramble from Port Moresby select max (= 3 Fighters, there is only 1 scramble)
Select Scramble button
Wait for it to crash with

![image](https://github.com/triplea-game/triplea/assets/71022517/b8696d89-a718-4109-9f84-2c805c18990e)

**Comment by asvitkine** [comment]
Error stack trace:

```
Caused by: java.util.NoSuchElementException: null
	at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
	at games.strategy.triplea.delegate.dice.calculator.RolledDice.lambda$getDiceForAllRolls$3(RolledDice.java:108)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at games.strategy.triplea.delegate.dice.calculator.RolledDice.getDiceHits(RolledDice.java:71)
	at games.strategy.triplea.delegate.dice.calculator.RolledDice.calculate(RolledDice.java:43)
	at games.strategy.triplea.delegate.dice.RollDiceFactory.rollBattleDice(RollDiceFactory.java:72)
	at games.strategy.triplea.delegate.battle.AirBattle$AttackersFire$1.execute(AirBattle.java:691)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:34)
	at games.strategy.triplea.delegate.battle.AirBattle.fight(AirBattle.java:130)
	at games.strategy.triplea.delegate.battle.BattleDelegate.fightBattle(BattleDelegate.java:241)
	at jdk.internal.reflect.GeneratedMethodAccessor69.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Comment by TheDog-GH** [comment]
046 B Sea Zone has a Japanese sub
Attacked by USA Fighter & 3 Bomber-Tac

Japan 3 Fighter from Port Moresby scramble to intercept

and in the same round

046 B Sea Zone has a Japanese sub
Attacked by Pacific-Allies 5 Bomber-Tac

Japan 3 Fighter from Port Moresby scramble to intercept
But 10 Bomber-Tac show up on the Air Battle, then crash

Hope you get something similar?
