### ISSUE TITLE
2.5.22294: New install. Game won't start.

### ISSUE THREAD

**Issue by TaffyIII** [triplea-game/triplea#12020]
### Reproduction Steps

Game won't start. Splash screen image stays up but then nothing else happens.
Process continues to run.

### Engine Version

Engine Version: 2.5.22294
Installed game using TripleA_2.5.22294_unix.sh. Installed to ~/TripleA with no obvious problems.
Fedora 34
Using two different versions of java. No difference in problem.

java -version
openjdk version "18.0.1" 2022-04-19
OpenJDK Runtime Environment 22.3 (build 18.0.1+10)
OpenJDK 64-Bit Server VM 22.3 (build 18.0.1+10, mixed mode, sharing)
 java -version
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)

cat error.log
java.lang.ClassNotFoundException: org.triplea.game.client.HeadedGameRunner
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
        at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
        at install4j.org.triplea.game.client.HeadedGameRunner.main(Unknown Source)
Uncaught error fetching image:
java.lang.NullPointerException: Cannot invoke "java.net.URL.openConnection()" because "this.url" is null
        at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:103)
        at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:113)
        at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:264)
        at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
        at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)

After starting the following process keeps running duplicating in the  error.log the same error message.

/usr/lib/jvm/java-18-openjdk-18.0.1.0.10-1.rolling.fc34.x86_64/bin/java -splash:/home/game/TripleA/.install4j/s_8of556.png -Xmx2048M -Xms2048M -Xss1250K -classpath /home/game/TripleA/.install4j/i4jruntime.jar:/home/game/TripleA/.install4j/launcherab9dd710.jar:/home/game/TripleA/bin/* install4j.org.triplea.game.client.HeadedGameRunner

No additional firewall or other security apps are installed.
I start the program within the installed dir by command ./TripleA

**Comment by TaffyIII** [comment]
Updates:
Farther testing shows that the java version "1.8.0_381" that I downloaded from Oracle wasn't being used.
Used the "alternatives --config java" command to swap between java versions but found that even though "java -version" command showed "1.8.0_381" when the TripleA command ran the running process showed "/usr/lib/jvm/java-18-openjdk-18.0.1.0.10-1.rolling.fc34.x86_64......".
So removed java-18-openjdk from system to leave only Oracle version.
Now when attempting to run TripleA it fails with error message:
_No suitable Java Virtual Machine could be found on your system.
The version of the JVM must be at least 11.
Please define INSTALL4J_JAVA_HOME to point to a suitable JVM._

Next installed java-11-openjdk.x86_64
Now when running TripleA the process shows /usr/lib/jvm/java-11-openjdk-11.0.15.0.10-1.fc34.x86_64/bin/java but with same results and error log as before.

**Comment by TaffyIII** [comment]
Solved.
After installing java-11-openjdk.x86_64 run the ./TripleA_2.5.22294_unix.sh script again.
Now it works.
