### ISSUE TITLE
2.7 ConcurrentModificationException Game Crash

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#12789]
AI vs AI game crashed with:   `ConcurrentModificationException`

> 15:18:31.877 [AWT-EventQueue-0] ERROR o.t.game.client.HeadedGameRunner - null
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047)
	at games.strategy.triplea.util.UnitSeparator.categorize(UnitSeparator.java:213)
	at games.strategy.triplea.util.UnitSeparator.categorize(UnitSeparator.java:199)
	at games.strategy.triplea.util.UnitSeparator.getSortedUnitCategories(UnitSeparator.java:96)
	at games.strategy.triplea.ui.SimpleUnitPanel.setUnits(SimpleUnitPanel.java:130)
	at games.strategy.triplea.ui.PlacePanel.lambda$updateStep$0(PlacePanel.java:151)

**Comment by DanVanAtta** [comment]
Potentially fixed now.. with luck.
