### ISSUE TITLE
hosted game crash WaW

### ISSUE THREAD

**Issue by Elenol** [triplea-game/triplea#1319]
Seems to come up when we lean on the AI. Not every time, but it's been more than once per full round today. Never happened prior to today. Not sure if I'm getting the same error every time. I'm not very literate with this sort of thing.

Below I've posted the console report. I believe this is the relevent part maybe:
----------------
Caused by: java.lang.IllegalStateException: Being asked to generate random numbers, but we havent finished last generation. Asked for: 1x6 for Thai roll dice for 1 Elite and 1 Tank in Northern Territory, round 2
-----------------

Here's my console clipboard in its entirety:

--------------------------------------------------------------

triplea.engine.version.bin:1.9
INFO [AWT-EventQueue-0] ChatController -> Chatter:Elenol port:3300 ip:2601:1c1:c100:453a:0:0:0:ce73 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
host:45.79.144.53 port:3304
INFO [Decoder -Server] ServerMessenger -> Connection added to:kostik port:54368 ip:71.80.198.193
INFO [pool-1-thread-2] ChatController -> Chatter:kostik port:54368 ip:71.80.198.193 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Loading map: , from: C:\Users\Zach Strole\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\Zach Strole\triplea\downloadedMaps\, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Loading map: world_at_war, from: C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip
Loading resources from the following paths: [C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Loading map: world_at_war, from: C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip
Loading resources from the following paths: [C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
INFO [Decoder -Server] ServerMessenger -> Connection added to:wirkey port:45475 ip:46.5.0.169
INFO [pool-1-thread-1] ChatController -> Chatter:wirkey port:45475 ip:46.5.0.169 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
INFO [Decoder -Server] ServerMessenger -> Connection added to:yxc port:35356 ip:78.50.218.97
INFO [pool-1-thread-7] ChatController -> Chatter:yxc port:35356 ip:78.50.218.97 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
INFO [NIO Reader - Server] ChatController -> Chatter:yxc port:35356 ip:78.50.218.97 has left chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
INFO [NIO Reader - Server] ServerMessenger -> Connection removed:yxc port:35356 ip:78.50.218.97
INFO [NIO Reader - Server] ChatController -> Chatter:kostik port:54368 ip:71.80.198.193 has left chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
INFO [NIO Reader - Server] ServerMessenger -> Connection removed:kostik port:54368 ip:71.80.198.193
INFO [Decoder -Server] ServerMessenger -> Connection added to:kostik port:54416 ip:71.80.198.193
INFO [pool-1-thread-3] ChatController -> Chatter:kostik port:54416 ip:71.80.198.193 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Loading map: world_at_war, from: C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip
Loading resources from the following paths: [C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
Loading map: world_at_war, from: C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip
Loading resources from the following paths: [C:\Users\Zach Strole\triplea\downloadedMaps\world_at_war-master.zip, C:\Program Files\TripleA_1.9.0.0.3266\assets]
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy16.getRandom(Unknown Source)
	at games.strategy.engine.delegate.DefaultDelegateBridge.getRandom(DefaultDelegateBridge.java:75)
	at games.strategy.triplea.delegate.GameDelegateBridge.getRandom(GameDelegateBridge.java:68)
	at games.strategy.triplea.delegate.DiceRoll.rollDiceLowLuck(DiceRoll.java:606)
	at games.strategy.triplea.delegate.DiceRoll.rollDice(DiceRoll.java:371)
	at games.strategy.triplea.delegate.Fire.rollDice(Fire.java:97)
	at games.strategy.triplea.delegate.Fire.access$000(Fire.java:24)
	at games.strategy.triplea.delegate.Fire$1.execute(Fire.java:235)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:35)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:329)
	at games.strategy.triplea.delegate.BattleDelegate.fightBattle(BattleDelegate.java:226)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:148)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:101)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.gamePlayer.GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:162)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at games.strategy.triplea.ai.AbstractAI.battle(AbstractAI.java:480)
	at games.strategy.triplea.ai.AbstractAI.start(AbstractAI.java:436)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:531)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:424)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:259)
	at games.strategy.engine.framework.startup.launcher.ServerLauncher$1.run(ServerLauncher.java:203)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:62)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.gamePlayer.GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:162)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at games.strategy.triplea.ai.AbstractAI.battle(AbstractAI.java:480)
	at games.strategy.triplea.ai.AbstractAI.start(AbstractAI.java:436)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:531)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:424)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:259)
	at games.strategy.engine.framework.startup.launcher.ServerLauncher$1.run(ServerLauncher.java:203)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager.lambda$createOutboundImplementation$71(DelegateExecutionManager.java:110)
	at com.sun.proxy.$Proxy16.getRandom(Unknown Source)
	at games.strategy.engine.delegate.DefaultDelegateBridge.getRandom(DefaultDelegateBridge.java:75)
	at games.strategy.triplea.delegate.GameDelegateBridge.getRandom(GameDelegateBridge.java:68)
	at games.strategy.triplea.delegate.DiceRoll.rollDiceLowLuck(DiceRoll.java:606)
	at games.strategy.triplea.delegate.DiceRoll.rollDice(DiceRoll.java:371)
	at games.strategy.triplea.delegate.Fire.rollDice(Fire.java:97)
	at games.strategy.triplea.delegate.Fire.access$000(Fire.java:24)
	at games.strategy.triplea.delegate.Fire$1.execute(Fire.java:235)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:35)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:329)
	at games.strategy.triplea.delegate.BattleDelegate.fightBattle(BattleDelegate.java:226)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:148)
	at com.sun.proxy.$Proxy9.fightBattle(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:101)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
	... 12 more
Caused by: java.lang.IllegalStateException: Being asked to generate random numbers, but we havent finished last generation. Asked for: 1x6 for Thai roll dice for 1 Elite and 1 Tank in Northern Territory, round 2
	at games.strategy.engine.random.RemoteRandom.generate(RemoteRandom.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$298(UnifiedMessenger.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:62)
	at com.sun.proxy.$Proxy18.generate(Unknown Source)
	at games.strategy.engine.random.CryptoRandomSource.getRandom(CryptoRandomSource.java:91)
	... 40 more
INFO [NIO Reader - Server] ChatController -> Chatter:kostik port:54416 ip:71.80.198.193 has left chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
INFO [NIO Reader - Server] ServerMessenger -> Connection removed:kostik port:54416 ip:71.80.198.193

**Comment by ron-murhammer** [comment]
@Elenol Interesting error, haven't seen that before. Any idea if this would occur in the previous version (1.8.0.9)? Or did you not play many large games with the AI in the past?

**Comment by Elenol** [comment]
I found out my friend did not have his java updated. When he updated and restarted his computer, we did not encounter the problem again with a 2 hour sample size.


We had never had the issue come up in v1.8.0.9 and we did not have the issue come up when he was on his laptop. I am almost certain the error was related to his java not being up to date. Thanks for the quick response! =)

________________________________

**Comment by ron-murhammer** [comment]
@Elenol Ok. If you see it occurred again let us know. Gonna close this for now.
