### ISSUE TITLE
I can't open v3 v4 v5 and v6

### ISSUE THREAD

**Issue by Navalland** [triplea-game/triplea#1334]
triplea.engine.version.bin:1.9
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at games.strategy.ui.SwingAction.invokeAndWait(SwingAction.java:63)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:117)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$99(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: games.strategy.engine.framework.startup.launcher.MapNotFoundException
	at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:57)
	at games.strategy.triplea.ui.UIContext.internalSetMapDir(UIContext.java:73)
	at games.strategy.triplea.ui.AbstractUIContext.setDefaultMapDir(AbstractUIContext.java:118)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:227)
	at games.strategy.triplea.TripleA.lambda$startGame$321(TripleA.java:119)
	at games.strategy.ui.SwingAction.lambda$invokeAndWait$692(SwingAction.java:63)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:353)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by Cernelius** [comment]
To give more info, beside the fact that he says he can't play it, I also hosted a WWIIv3 game with Navalland as Allies and it started normally on my side, but both his bid phases were skipped, just like he decided to not use his bid.
The game didn't crash, and I was in it with Navalland, just like he was there and decided to skip all his phases. Except Navalland tried to join as Navalland (1) and in lobby told me he had issues.
That was very weird; never happened.
I told him to delete all in the downloadedMaps folder, but it didn't seem to have done anything.

**Comment by ron-murhammer** [comment]
@Navalland Looks like it can't find the map files. I would recommend clearing your downloadedMaps folder and redownloading the maps. Then check to see if singleplayer works first.

**Comment by Navalland** [comment]
this error message is common among v3, v4, v5 and v6 Than I take this information from Triplea. For example when I try to open v5 also I take this message in addition

Map missing world_war_ii_v5_1942 could not join game
would you like to download the map now?
Once the download completes, you may reconnect to this game.

I tried. I deleted all maps which include downloadedMaps but it still didn't work.

**Comment by jdimeo** [comment]
Was this game created with the older version? are you now trying to play it on the new version? I believe you need to put the map in "maps" not "downloadedMaps". "downloadedMaps" was new for this latest release and older versions don't know to look there for maps.

**Comment by Navalland** [comment]
No. It's new.

**Comment by Navalland** [comment]
My Triplea is 1.9.0.0.3133

**Comment by ron-murhammer** [comment]
@Navalland Have you tried uninstalling and redownloading TripleA? Also make sure you have Java 8 installed?

**Comment by ron-murhammer** [comment]
@Navalland Where you able to resolve your issues?

**Comment by simon33-2** [comment]
I've seen the same error messages when running via gradle without maps. Did the user download the maps and select one?

I can't remember where the config for where TripleA looks for maps is, perhaps it is hard coded?

Perhaps there is a wrong map under the <program_dir>/maps ?

**Comment by Navalland** [comment]
I have tried uninstalling and redownloading Triplea and I have java 8. Still isn't work.

 I downloaded the maps but I coudn t  understant what is the mean of "select one"

I coudn't find <program_dir> file. How  can I find this?

**Comment by panther2** [comment]
program_dir stands for the installation directory of TripleA.

In windows it is for example
c:\Program Files\TripleA_xxxx 
by default (if you did not change it manually).

"Select One" means "choose a map". When starting TripleA you need to choose (select) the map that you want to play.

What is your native language?

**Comment by simon33-2** [comment]
The angle brackets were meant to signify a placeholder.

**Comment by Navalland** [comment]
Ok I understand my native language is Turkish.

**Comment by simon33-2** [comment]
@Navalland 
Reiterating Ron's question - where you able to fix this or is it still an issue for you?

**Comment by Navalland** [comment]
It is still an issue for me.

**Comment by Navalland** [comment]
I solved my problem

**Comment by ron-murhammer** [comment]
@Navalland Oh how did you end up fixing it?

**Comment by Navalland** [comment]
for example v3's zip file's name was "world_war_ıı_v3" I changed this to "world_war_ii_v3

**Comment by Cernelius** [comment]
This might be a major problem for Turkish users.
It seems that for him all occurrences of "ii", used in the Roman numerals fashion (actually, the true Roman numerals should be "II", not "ii"), in the zip names, but not in the xml, are automatically changed to "ıı" (a Turkish letter), when he downloads.
This doesn't happen with normally used "i". For example, "domination" doesn't become "domınatıon".
I'm guessing most other users that might have this problem won't figure out before giving up.

**Comment by DanVanAtta** [comment]
#1436 to follow up and discuss ways to solve this. It is interesting that the map download was renamed. Overall the game should not depend on the names of folders for finding maps, #1436 is to track that problem.
