### ISSUE TITLE
Java error prevents loading in leap 4.2 Linux

### ISSUE THREAD

**Issue by basmith-triplea** [triplea-game/triplea#1350]
The following Java error is posted after attempting to load a local game (World War II V3 1942) also with other maps.

triplea.engine.version.bin:1.9
Loading map: tutorial, from: /home/basmith/TripleA_1.9.0.0.3307/maps/tutorial.zip
Loading resources from the following paths: [/home/basmith/TripleA_1.9.0.0.3307/maps/tutorial.zip, /home/basmith/TripleA_1.9.0.0.3307/assets]
java.lang.ExceptionInInitializerError
	at games.strategy.net.HeadlessServerMessenger.<init>(HeadlessServerMessenger.java:18)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:40)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$116(AbstractLauncher.java:43)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: java.net.UnknownHostException: leap42: leap42: unknown error
	at games.strategy.net.Node.<clinit>(Node.java:23)
	... 4 more
Caused by: java.net.UnknownHostException: leap42: leap42: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at games.strategy.net.Node.<clinit>(Node.java:21)
	... 4 more
Caused by: java.net.UnknownHostException: leap42: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 5 more

**Comment by DanVanAtta** [comment]
I think this might have to do with the /etc/hosts file not having an entry for localhost or alternatively for 127.0.0.1.

Would you mind listing your localhost entries from /etc/hosts? (and any entries that refer to 127.0.0.1)

**Comment by basmith-triplea** [comment]
127.0.0.1	localhost

# special IPv6 addresses
::1             localhost ipv6-localhost ipv6-loopback

fe00::0         ipv6-localnet

ff00::0         ipv6-mcastprefix
ff02::1         ipv6-allnodes
ff02::2         ipv6-allrouters
ff02::3         ipv6-allhosts

**Comment by DanVanAtta** [comment]
I think you need at least one 127.0.0.1 entry referring to your local host machine by name.

**Comment by basmith-triplea** [comment]
Added 
127.0.1.1 machine.name

This corrected problem, both for local game and on-line play.
