### ISSUE TITLE
1.90 issues noticed thus far

### ISSUE THREAD

**Issue by Deltium** [triplea-game/triplea#1356]
I've been starting to play live more, and I have noticed the following bugs while playing Revised:

- today, when typing notes in the screen, I could not see the text, but my opponent could.  why?

- the screen crashed multiple times, with a dialog box opening up with a large amount of text in it, presumably error messages.

- when  an opponent suddenly exits the game (for whatever reason), the entire game board disappears.  Shouldn't this stay open to allow the remaining player the opportunity to save the game file?

- I noticed that some maps (e.g. AA 50 '41 version) had an update to it, but I wasn't notified, until I noticed it by chance.    How is one supposed to know if there are map updates after downloading?

**Comment by Deltium** [comment]
Here's an example of a crash just moments ago:

triplea.engine.version.bin:1.9
Loading map: , from: C:\Users\Richard\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\Richard\triplea\downloadedMaps\, C:\Program Files\TripleA_1.9.0.0.3277\assets]
java.lang.ArrayIndexOutOfBoundsException: 13
	at games.strategy.engine.lobby.client.ui.TableSorter.modelIndex(TableSorter.java:231)
	at games.strategy.engine.lobby.client.ui.TableSorter.getValueAt(TableSorter.java:277)
	at javax.swing.JTable.getValueAt(Unknown Source)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at games.strategy.engine.lobby.client.ui.LobbyGameTable.prepareRenderer(LobbyGameTable.java:33)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.ArrayIndexOutOfBoundsException: 13
	at games.strategy.engine.lobby.client.ui.TableSorter.modelIndex(TableSorter.java:231)
	at games.strategy.engine.lobby.client.ui.TableSorter.getValueAt(TableSorter.java:277)
	at javax.swing.JTable.getValueAt(Unknown Source)
	at javax.swing.JTable.prepareRenderer(Unknown Source)
	at games.strategy.engine.lobby.client.ui.LobbyGameTable.prepareRenderer(LobbyGameTable.java:33)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JLayeredPane.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
	at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
	at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
	at java.awt.Container.paint(Unknown Source)
	at java.awt.Window.paint(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by DanVanAtta** [comment]
1. I think there is a fix for this one, but we need to simply update the latest website version for download. Ron has asked me if I wanted that done, I was too busy at the time to say yes. Any backwards compatible new versions should be the website download version.
Richard, please give the latest release a try.

2. The error messages will be important, did you capture/save them by any chance?

3. This is just a bug, needs to be fixed..

4. The problem there is that folks have not been updating the download version in triplea_maps.yaml at the right time. That is the mechansim that notifies you of new maps. IF people do not update it, the game will not notify you.

**Comment by panther2** [comment]
@DanVanAtta 
Regarding 4.
Of course "folks" and "people" have updated the triplea_maps.yaml as soon as possible:
https://github.com/triplea-game/triplea/pull/1347
After the changes had been merged to the map repos Ron asked Simon and me to do some testing before updating the triplea_maps.yaml. Given the huge time zone differences between USA, Germany and Australia I fail to see how this process could have been quicker.

**Comment by panther2** [comment]
@Deltium 

Update notification in 1.9 is different from 1.8.
While in 1.8 the installed map that needed an update appeared in red and bold,
in 1.9 map updates are noted in a separate window next to "Available" and "Installed".

Just in case you were not affected by the short update delay I described above.

**Comment by DanVanAtta** [comment]
Sorry, my tone/writing was wrong. It's an easy version number to understand, and it's been pretty prevalent confusion as to what it is. When there is a problem of no in-game prompt, typically this has been the problem. Ideally we'd have a cleaner versioning system, including something that versioned the XML spec itself.

**Comment by panther2** [comment]
Maybe the version update in the triplea_maps.yaml could be done sort of automatically once the changes have been merged to the map repos...

**Comment by panther2** [comment]
Also I think that the process of updating maps including the versioning in the triplea_maps.yaml is not yet familiar to everyone contributing.

**Comment by DanVanAtta** [comment]
- https://github.com/triplea-game/triplea/pull/1363 will address the stack trace. 
- Spawned: https://github.com/triplea-game/triplea/issues/1362 to track game board disappearing problem.
