### ISSUE TITLE
TripleA Freeze/Crash

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1459]
Somehow got this error when scrolling with held down mouse button while opening a map for the first time...
Had the same error a while back, but couldn't reproduce it just like now
```
java.lang.NullPointerException
	at games.strategy.thread.LockUtil.acquireLock(LockUtil.java:53)
	at games.strategy.triplea.ui.screen.Tile.clear(Tile.java:180)
	at games.strategy.triplea.ui.screen.TileManager.resetTiles(TileManager.java:178)
	at games.strategy.triplea.ui.MapPanel.recreateTiles(MapPanel.java:194)
	at games.strategy.triplea.ui.MapPanel.setScale(MapPanel.java:699)
	at games.strategy.ui.ImageScrollerLargeView.lambda$0(ImageScrollerLargeView.java:139)
	at java.awt.Component.processMouseWheelEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by DanVanAtta** [comment]
Is this consistent? Which map?

**Comment by RoiEXLab** [comment]
I don't know, it seems to happen randomly... I will look into this on Tuesday

**Comment by DanVanAtta** [comment]
What was the impact of this? did you have to restart the game, or could you play through it?

**Comment by DanVanAtta** [comment]
nm, disregard last question on impact - clear now from title "crash/freeze"

**Comment by RoiEXLab** [comment]
Can't reproduce anymore...
Probably due to https://github.com/triplea-game/triplea/pull/1506
