### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by captnchuck67** [triplea-game/triplea#1467]
Have a Win 7 pro 64 bit. Can download the install program when it runs it gets about 33% then stops gives me an error message saying cannot connect to java runtime downloader check internet connection and retry. I have tried 3 different connection,I get the same message on all three.

**Comment by panther2** [comment]
Any firewall blocking the installer's outgoing connection?

Anyway, please

- read and follow https://java.com/en/download/faq/remove_olderversions.xml
- download the latest Java RE directly from http://javadl.oracle.com/webapps/download/AutoDL?BundleId=216434
- install the downloaded file (JRE for Windows 64bit)
- reinstall TripleA

Then you should be fine.

**Comment by captnchuck67** [comment]
okay got it installed but now I can not down load maps

**Comment by Cernelius** [comment]
May be your maps downloading issues the same as these (in this case, better closing this and joining that issue):

https://github.com/triplea-game/triplea/issues/1376

**Comment by panther2** [comment]
@captnchuck67 

Looks like a firewall issue (same as your first statement). 
You need to enable **javaw.exe** to connect to the internet in order to download maps.

**Comment by captnchuck67** [comment]
not the problem tried all that still getting this 
Error - will show an empty list of downloads. Failed to get files from: http://raw.githubusercontent.com/triplea-game/triplea/master/triplea_maps.yaml?raw=true
java.net.SocketException: Unrecognized Windows Sockets error: 10106: create
	at java.net.Socket.createImpl(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadUtils.getUrlFollowingRedirects(DownloadUtils.java:80)
	at games.strategy.engine.framework.map.download.DownloadUtils.downloadFile(DownloadUtils.java:74)
	at games.strategy.engine.framework.map.download.DownloadRunnable.downloadFile(DownloadRunnable.java:43)
	at games.strategy.engine.framework.map.download.DownloadRunnable.getDownloads(DownloadRunnable.java:29)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$showDownloadMapsWindow$129(DownloadMapsWindow.java:74)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$null$242(BackgroundTaskRunner.java:17)
	at java.lang.Thread.run(Unknown Source)

**Comment by panther2** [comment]
This indeed is the same as mentioned in #1376 
As Cernelius mentioned you can close this issue here now and go on there.

**Comment by RoiEXLab** [comment]
It may be the case that port 10106 is blocked by another Process...
Please press `Windows + R` enter `resmon.exe`, press `Enter` and search for an Application using port 10106.
If you terminate this application you will hopefully find, everything should work fine again

**Comment by DanVanAtta** [comment]
Could you also check if you have a IPv4 or IPv6 IP address? It looks like that could be at play, and adding `-Djava.net.preferIPv4Stack=true` to the startup flags can help.

http://stackoverflow.com/questions/3947555/java-net-socketexception-unrecognized-windows-sockets-error-0-jvm-bind-jboss

**Comment by DanVanAtta** [comment]
@captnchuck67  any luck?
