### ISSUE TITLE
Unable to select Tutorial map

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#1567]
#### Environment
* Fedora 25 (4.9.12-200.fc25.x86_64)
* TripleA 1.9.0.0.3856

#### Reproduction steps
* Install `TripleA_1.9.0.0.3856_unix.sh`.
* Start TripleA.
* Click **Select Map**.
* Click **Tutorial**.

#### Expected results
The game notes for the Tutorial map should be displayed in the right-hand panel.

#### Actual results
A message dialog is displayed:

![download-map](https://cloud.githubusercontent.com/assets/4826349/23687428/6b02bd08-037c-11e7-90cf-8a0ba0634639.png)

The following stack trace is displayed in the console:

```
games.strategy.engine.framework.startup.launcher.MapNotFoundException
	at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:57)
	at games.strategy.util.LocalizeHTML.localizeImgLinksInHTML(LocalizeHTML.java:87)
	at games.strategy.engine.framework.ui.NewGameChooser.updateInfoPanel(NewGameChooser.java:140)
	at games.strategy.engine.framework.ui.NewGameChooser.lambda$setupListeners$239(NewGameChooser.java:173)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1796)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1810)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectionInterval(JList.java:2065)
	at javax.swing.plaf.basic.BasicListUI$Handler.adjustSelection(BasicListUI.java:2739)
	at javax.swing.plaf.basic.BasicListUI$Handler.mousePressed(BasicListUI.java:2695)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:349)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at games.strategy.engine.framework.ui.NewGameChooser.chooseGame(NewGameChooser.java:105)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.selectGameFile(GameSelectorPanel.java:394)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$setupListeners$182(GameSelectorPanel.java:216)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:349)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by panther2** [comment]
Same on Windows.

**Comment by panther2** [comment]
After deleting tutorial.zip other maps can be chosen without issues.

**Comment by ssoloff** [comment]
I looked into this a bit.  Understanding the root cause is easy, but I'm not sure what's the best way to fix it.

Let's start with the root cause.  #1492 moved the Tutorial map from the `<root>/maps` folder to the `<root>` folder ([diff](https://github.com/triplea-game/triplea/pull/1492/commits/3e10b9435bcaa4e159d2d1f040b2334c95dfd3ac#diff-dbb5c25d5c0c7a1b56707fcf8f00b85b)).  In addition, the default maps folder was changed from `<root>/maps` to just `<root>` ([diff](https://github.com/triplea-game/triplea/pull/1492/commits/3e10b9435bcaa4e159d2d1f040b2334c95dfd3ac#diff-70d60de023e422ce6c8234744e6d8bc0)).  However, the code in [`ResourceLoader#getPaths()`](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/games/strategy/triplea/ResourceLoader.java#L83) was not changed to include the root folder in the list of searchable paths.  The absence of the root folder in this list is why the "map missing" message is displayed.

I was able to get everything working with this two-line change:

```diff
diff --git a/src/main/java/games/strategy/triplea/ResourceLoader.java b/src/main/java/games/strategy/triplea/ResourceLoader.java
index ab57b90..93eece4 100644
--- a/src/main/java/games/strategy/triplea/ResourceLoader.java
+++ b/src/main/java/games/strategy/triplea/ResourceLoader.java
@@ -94,6 +94,8 @@ public class ResourceLoader implements Closeable {
     candidates.add(new File(ClientFileSystemHelper.getUserMapsFolder(), zipName));
     candidates.add(new File(ClientFileSystemHelper.getRootFolder() + File.separator + "maps", dirName));
     candidates.add(new File(ClientFileSystemHelper.getRootFolder() + File.separator + "maps", zipName));
+    candidates.add(new File(ClientFileSystemHelper.getRootFolder(), dirName));
+    candidates.add(new File(ClientFileSystemHelper.getRootFolder(), zipName));
 
     final String normalizedZipName = normalizeMapZipName(zipName);
```

(Note that only the second candidate was actually required.  My initial reaction was simply to duplicate the same dual folder/archive pattern used for other candidates.  But just to get `tutorial.zip` found, only the second candidate is needed.)

However, I'm not sure this is the right fix.

First, I'm concerned about adding this line:

```java
candidates.add(new File(ClientFileSystemHelper.getRootFolder(), dirName));
```

I'm not sure if that could cause problems by searching what I'll call TripleA's "infrastructure" folders for maps (e.g. `assets`, `bin`, `icons`, etc.).  Could that lead to some unintentional behavior in the future?  However, I think searching the root folder for zip archives is fine.  **So my first question is should both folders and zip archives in the root folder be searched for maps?**

Second, is the `<root>/maps` folder formally deprecated as of #1492?  **If so, should all references to it be removed?**  In addition to `ResourceLoader#getPaths()`, there are a few other locations where it is used (e.g. [here](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/games/strategy/engine/framework/headlessGameServer/AvailableGames.java#L179), [here](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/games/strategy/engine/framework/startup/mc/GameSelectorModel.java#L34), [here](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/games/strategy/engine/framework/ui/NewGameChooserEntry.java#L155), [here](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/tools/image/AutoPlacementFinder.java#L88), and [here](https://github.com/triplea-game/triplea/blob/de52f7ea14abb3d7d75b1431310a3fec27bcca62/src/main/java/tools/map/xml/creator/MapXmlCreator.java#L363)).  Seems like there could be a new `ClientFileSystemHelper#getSystemMapsFolder()` method to encapsulate this path so it isn't duplicated (regardless of whether it points to `<root>/maps` or just `<root>`).

@ron-murhammer @DanVanAtta

**Comment by panther2** [comment]
Why not install the tutorial.zip into `/downloadedMaps` ?
That would avoid every map installation into the `/TripleA` root directory.

Additionally we could think about leaving the tutorial.zip out of the installation file and offer it via the ingame downloader. 
Or when launching TripleA for the first time the user could be asked if he wanted to download a tutorial.

Just thoughts...

**Comment by DanVanAtta** [comment]
@ssoloff, sorry I was not able to respond sooner, been swamped with work of late. I do have some context into this, and you're very much on the right path IMO.

We used to have a decent number of maps installed in /maps that came with the game engine. This was to make it easy to get maps when installing the game. It was painful to get them one-by-one in the old UI, people wanted a bundled download once version of the game.

There are a few problems though:
- still had two map folder locations, which caused confusion
- game download size was large, 300MB+ (IIRC, I think it was ~350MB)
- any maps bundled with the game cannot be updated without a game engine update. Would be odd to have some like this, others not
- any map bundled with game is downloaded every game update. Removing it allows it to be downlaoded once and managed by the normal maps UI.


I apologize #1492 was such a mess. I think I lost track of it and there were actually still some issues.

I believe my intent was to move the tutorial map up one folder. This was to help avoid the confusion where maps were being dropped in the '/maps' folder with the intent for them to be picked up. Really it should go to 'downloadedMaps' if we can get the game install/extractor to create that folder and move it there. Overall the way the game finds maps and resources has been pretty complex. Personally I want us to do the serialization proxy pattern so we can save game compatibility. That will let us get rid of the old jars and have a much simpler search path. https://github.com/triplea-game/triplea/issues/614 (big problem there though is that it's not backwards compatible, and it's a good bit of work to do. We gain some good benefits though, and it lets us stop passing around GameData objects all over the place. I applied the pattern in one or two classes and worked pretty well).

To be sure I answer your questions directly @ssoloff :

> I'm not sure if that could cause problems by searching what I'll call TripleA's "infrastructure" folders for maps (e.g. assets, bin, icons, etc.). Could that lead to some unintentional behavior in the future?

there is a search path for assets, but that is relative the to root already. IIRC the code is duplicated/similar'ish for it, so you can upate this copy okay (YMMV)

>  However, I think searching the root folder for zip archives is fine. So my first question is should both folders and zip archives in the root folder be searched for maps?

We only expect the tutorial.zip in the root, can simplify to only look for exactly that map in the root folder. The thinking at least is to have there be exactly one folder for maps. I suspect it might be easiest to keep it that way so there is less variability in how the game  picks up maps.

> Second, is the <root>/maps folder formally deprecated as of #1492? If so, should all references to it be removed? 

Yes

**Comment by ssoloff** [comment]
Thanks for the response, @DanVanAtta, and for providing some context.  (And +1 for pursuing "persistence ignorance" in the domain model. :+1:)

It sounds like both you and @panther2 are advocating for placing the tutorial in `downloadedMaps`, if possible.  That sounds reasonable to me, but I have two concerns:

#### Testing

In order to properly test the installer changes, I think I would need an install4j license.  It looks like they offer a 30-day trial license, but that begs the question what to do the next time I need to test an installer change? :smiley:  Is there some other method for testing the installer I'm unaware of that would avoid the need for a license?

#### User experience

This is probably an edge case, but if the tutorial is initially installed to `~/triplea/downloadedMaps`, and the user subsequently changes the Map Download Path setting, won't they have to manually copy `tutorial.zip` to the new folder to preserve it in the list of available maps?  Would @panther2's second suggestion above address this?  Namely, making the tutorial generally available for download so that the user could re-download it from the UI if they "lose" it after changing the setting.

**Comment by ssoloff** [comment]
> In order to properly test the installer changes, I think I would need an install4j license.  It looks like they offer a 30-day trial license, but that begs the question what to do the next time I need to test an installer change? :smiley:  Is there some other method for testing the installer I'm unaware of that would avoid the need for a license?

FYI for anyone who may find themselves in a similar situation...  I reached out to the sales team at ej-technologies, and they were kind enough to provide me with an install4j license key after I explained that I was not a _committer_ on TripleA (and thus didn't have access to the team's open source license key) but was simply trying to _contribute_ an installer change back to the project.  That's impressive support for OSS!
