### ISSUE TITLE
NullPointerException - TripleA Lobby bots

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#1577]
Figuring out why the bots keep crashing, but actually don't...
```
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT -> java.lang.NullPointerException
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.framework.startup.mc.ClientModel.startGameInNewThread(ClientModel.java:317)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.framework.startup.mc.ClientModel.startGame(ClientModel.java:291)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.framework.startup.mc.ClientModel.access$200(ClientModel.java:65)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.framework.startup.mc.ClientModel$2.joinGame(ClientModel.java:265)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at java.lang.reflect.Method.invoke(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$298(UnifiedMessenger.java:303)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at java.lang.Thread.run(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:62)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at com.sun.proxy.$Proxy22.joinGame(Unknown Source)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at games.strategy.engine.framework.ServerGame.lambda$addObserver$89(ServerGame.java:182)
Sat Mar 18 13:19:58 UTC 2017 INFO [Waiting on observer to finish joining: prastle] OUT ->       at java.lang.Thread.run(Thread.java:745)
```
[This Code](https://github.com/triplea-game/triplea/blob/master/src/main/java/games/strategy/engine/framework/startup/mc/ClientModel.java#L315-L320) shows that some of the used vars in the if statement can be null sometimes...
Maybe this is the reason the bots keep crashing... at least this was the last log in the bot13NJ log file... The process is still running

**Comment by prastle** [comment]
CAN we post back in the lobby that all need the .3627 stable?  Or force an update to 1.9.1.  with the ability for a screen pop up like it does if ya try to use 1.8? With an ev change that shows so that all know if they have correct version?

**Comment by prastle** [comment]
and btw above is prob me trying to check joined users so i can boot the ghosts and clean after it locked them out.
