### ISSUE TITLE
trying to get 1.8.x to 1.9.x all ready read the wiki

### ISSUE THREAD

**Issue by robinteus** [triplea-game/triplea#1667]
this is the problem 
its a map of avatar last airbender/ legend of aang
i Rather play and make map with 1.8.x than 1.9.x at this moment
but i dont know how long 1.8.x will be supported

triplea.engine.version.bin:1.9
Loading map: tutorial, from: C:\Program Files\TripleA_1.9.0.0.3627\maps\tutorial.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3627\maps\tutorial.zip, C:\Program Files\TripleA_1.9.0.0.3627\assets]
Loading map: Avatar, from: C:\Program Files\TripleA_1.9.0.0.3627\maps\Avatar.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3627\maps\Avatar.zip, C:\Program Files\TripleA_1.9.0.0.3627\assets]
Loading map: Avatar, from: C:\Program Files\TripleA_1.9.0.0.3627\maps\Avatar.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3627\maps\Avatar.zip, C:\Program Files\TripleA_1.9.0.0.3627\assets]
games.strategy.engine.data.GameParseException: Could not find rule. name:conditionAttachment_Fire_Nation_Northern_Earth_Kingdom_Open_Borders1Rounds   for: PoliticalActionAttachment attached to:PlayerID named:Fire_Nation with name:politicalActionAttachment_Fire_Nation_Ceasefire_Northern_Earth_KingdomCould not parse:jar:file:/C:/Program%20Files/TripleA_1.9.0.0.3627/maps/Avatar.zip!/games/Avatar.xml
	at games.strategy.triplea.attachments.AbstractConditionsAttachment.setConditions(AbstractConditionsAttachment.java:72)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1328)
	at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1263)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:153)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.fullyParseGameData(NewGameChooserEntry.java:77)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.selectGameFile(GameSelectorPanel.java:398)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$setupListeners$181(GameSelectorPanel.java:216)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

games.strategy.engine.data.GameParseException: MapName: jar:file:/C:/Program%20Files/TripleA_1.9.0.0.3627/maps/Avatar.zip!/games/Avatar.xml, Error setting property:conditions cause:Could not find rule. name:conditionAttachment_Fire_Nation_Northern_Earth_Kingdom_Open_Borders1Rounds   for: PoliticalActionAttachment attached to:PlayerID named:Fire_Nation with name:politicalActionAttachment_Fire_Nation_Ceasefire_Northern_Earth_Kingdom
	at games.strategy.engine.data.GameParser.setValues(GameParser.java:1335)
	at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1263)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:153)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.fullyParseGameData(NewGameChooserEntry.java:77)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.selectGameFile(GameSelectorPanel.java:398)
	at games.strategy.engine.framework.startup.ui.GameSelectorPanel.lambda$setupListeners$181(GameSelectorPanel.java:216)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by panther2** [comment]
Maps for 1.8 are incompatible, so you can't use them with the 1.9-engine.
You need to run your 1.8 maps with the 1.8 engine.
There have been a lot of changes for 1.9-maps.

See https://github.com/triplea-game/triplea/wiki/Upgrade-Maps-Information

**Comment by robinteus** [comment]
thanks i will look at that

**Comment by robinteus** [comment]
i just copy tutorial to go from there and now it works
