### ISSUE TITLE
Error when accessing "Account-Update Account" in Lobby

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#1892]
1.9.0.0.4789 (and earlier).

See:

![tralob](https://user-images.githubusercontent.com/20812775/27129061-505cefdc-5101-11e7-9975-2f1b4a6d5418.gif)

Error Console Message:

```
triplea.engine.version.bin:1.9
Loading map: , from: D:\Daten\triplea\downloadedMaps\
Loading resources from the following paths: [D:\Daten\triplea\downloadedMaps\, C:\Games\TripleA\assets]
Jun 14, 2017 12:49:38 PM games.strategy.net.nio.Decoder loop
SCHWERWIEGEND: error reading object
java.lang.ClassNotFoundException: games.strategy.engine.lobby.server.userDB.DBUser
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at java.io.ObjectInputStream.resolveClass(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at games.strategy.engine.message.RemoteMethodCallResults.readExternal(RemoteMethodCallResults.java:54)
	at games.strategy.engine.message.unifiedmessenger.InvocationResults.readExternal(InvocationResults.java:44)
	at games.strategy.net.nio.Decoder.readMessageHeader(Decoder.java:162)
	at games.strategy.net.nio.Decoder.loop(Decoder.java:75)
	at games.strategy.net.nio.Decoder.lambda$new$314(Decoder.java:49)
	at java.lang.Thread.run(Unknown Source)

games.strategy.engine.message.ConnectionLostException: Connection Lost
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.messengerInvalid(UnifiedMessenger.java:82)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$new$292(UnifiedMessenger.java:66)
	at games.strategy.net.ClientMessenger.socketError(ClientMessenger.java:237)
	at games.strategy.net.nio.NIOSocket.error(NIOSocket.java:85)
	at games.strategy.net.nio.Decoder.loop(Decoder.java:104)
	at games.strategy.net.nio.Decoder.lambda$new$314(Decoder.java:49)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Invoker Stack
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	at com.sun.proxy.$Proxy7.getUserInfo(Unknown Source)
	at games.strategy.triplea.ui.menubar.LobbyMenu.updateAccountDetails(LobbyMenu.java:379)
	at games.strategy.triplea.ui.menubar.LobbyMenu.lambda$addUpdateAccountMenu$668(LobbyMenu.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:211)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
games.strategy.engine.message.ConnectionLostException: Connection Lost
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.messengerInvalid(UnifiedMessenger.java:82)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$new$292(UnifiedMessenger.java:66)
	at games.strategy.net.ClientMessenger.socketError(ClientMessenger.java:237)
	at games.strategy.net.nio.NIOSocket.error(NIOSocket.java:85)
	at games.strategy.net.nio.Decoder.loop(Decoder.java:104)
	at games.strategy.net.nio.Decoder.lambda$new$314(Decoder.java:49)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: Invoker Stack
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	at com.sun.proxy.$Proxy7.getUserInfo(Unknown Source)
	at games.strategy.triplea.ui.menubar.LobbyMenu.updateAccountDetails(LobbyMenu.java:379)
	at games.strategy.triplea.ui.menubar.LobbyMenu.lambda$addUpdateAccountMenu$668(LobbyMenu.java:372)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:211)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by RoiEXLab** [comment]
@DanVanAtta I assume this is caused by the lates DB changes?

**Comment by DanVanAtta** [comment]
Seems like. https://github.com/triplea-game/triplea/blob/master/src/main/java/games/strategy/engine/lobby/server/userDB/DbUser.java would need to be renamed back to `DBUser.java`

**Comment by DanVanAtta** [comment]
Should be fixed with: https://github.com/triplea-game/triplea/pull/1897

**Comment by panther2** [comment]
Thanks! Fixed and closed.
