### ISSUE TITLE
Unable to download maps for v1.9

### ISSUE THREAD

**Issue by rotorhead321** [triplea-game/triplea#1944]
I just downloaded the latest version...went to get maps.
triplea.engine.version.bin:1.9
Failed while attempting to check for a new Version
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at games.strategy.engine.framework.EngineVersionProperties.getProperties(EngineVersionProperties.java:86)
	at games.strategy.engine.framework.EngineVersionProperties.<init>(EngineVersionProperties.java:35)
	at games.strategy.engine.framework.EngineVersionProperties.lambda$contactServerForEngineVersionProperties$73(EngineVersionProperties.java:64)
	at java.lang.Thread.run(Unknown Source)
Failed while attempting to check for a new Version
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at games.strategy.engine.framework.EngineVersionProperties.getProperties(EngineVersionProperties.java:86)
	at games.strategy.engine.framework.EngineVersionProperties.<init>(EngineVersionProperties.java:35)
	at games.strategy.engine.framework.EngineVersionProperties.lambda$contactServerForEngineVersionProperties$73(EngineVersionProperties.java:64)
	at java.lang.Thread.run(Unknown Source)
Setting memory for new triplea process to: 910m
triplea.engine.version.bin:1.9
Current Engine version in use: 1.8.0.9
Error - will show an empty list of downloads. Failed to get files from: http://raw.githubusercontent.com/triplea-game/triplea/master/triplea_maps.yaml?raw=true
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadUtils.getUrlFollowingRedirects(DownloadUtils.java:80)
	at games.strategy.engine.framework.map.download.DownloadUtils.downloadFile(DownloadUtils.java:74)
	at games.strategy.engine.framework.map.download.DownloadRunnable.downloadFile(DownloadRunnable.java:43)
	at games.strategy.engine.framework.map.download.DownloadRunnable.getDownloads(DownloadRunnable.java:29)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$showDownloadMapsWindow$130(DownloadMapsWindow.java:74)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$null$242(BackgroundTaskRunner.java:17)
	at java.lang.Thread.run(Unknown Source)
Error - will show an empty list of downloads. Failed to get files from: http://raw.githubusercontent.com/triplea-game/triplea/master/triplea_maps.yaml?raw=true
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadUtils.getUrlFollowingRedirects(DownloadUtils.java:80)
	at games.strategy.engine.framework.map.download.DownloadUtils.downloadFile(DownloadUtils.java:74)
	at games.strategy.engine.framework.map.download.DownloadRunnable.downloadFile(DownloadRunnable.java:43)
	at games.strategy.engine.framework.map.download.DownloadRunnable.getDownloads(DownloadRunnable.java:29)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$showDownloadMapsWindow$130(DownloadMapsWindow.java:74)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$null$242(BackgroundTaskRunner.java:17)
	at java.lang.Thread.run(Unknown Source)
Trying to play a map made for a newer version of TripleA. Map named 'Tutorial' requires at least TripleA version 1.9
Loading map: tutorial, from: C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: tutorial, from: C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Loading map: tutorial, from: C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip
Loading resources from the following paths: [C:\Program Files\TripleA_1.9.0.0.3635\maps\tutorial.zip, C:\Program Files\TripleA_1.9.0.0.3635\assets]
Error - will show an empty list of downloads. Failed to get files from: http://raw.githubusercontent.com/triplea-game/triplea/master/triplea_maps.yaml?raw=true
java.net.SocketException: Permission denied: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadUtils.getUrlFollowingRedirects(DownloadUtils.java:80)
	at games.strategy.engine.framework.map.download.DownloadUtils.downloadFile(DownloadUtils.java:74)
	at games.strategy.engine.framework.map.download.DownloadRunnable.downloadFile(DownloadRunnable.java:43)
	at games.strategy.engine.framework.map.download.DownloadRunnable.getDownloads(DownloadRunnable.java:29)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$showDownloadMapsWindow$130(DownloadMapsWindow.java:74)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner.lambda$null$242(BackgroundTaskRunner.java:17)
	at java.lang.Thread.run(Unknown Source)

**Comment by RoiEXLab** [comment]
If you installed triplea with the installer, go to your TripleA installation directory, open the TripleA.vmoptions file and add `-Djava.net.preferIPv4Stack=true` at the end of it.
This should do the trick.

**Comment by ron-murhammer** [comment]
Closing based on no activity for a week. Please re-open if you are still having issues.
