### ISSUE TITLE
Red sun over china in 1.9

### ISSUE THREAD

**Issue by idodoappo** [triplea-game/triplea#1956]
Red sun over china and Warlords FFA work like charm in 1.8 but when i download them in 1.9 and click play it loads for half a second and brings me back to the menu.

this is one of my favorite maps, please help

**Comment by panther2** [comment]
I can confirm the issue. I downloaded the map, started and got his from the error log:

```
triplea.engine.version.bin:1.9
Loading map: red_sun_over_china, from: D:\Daten\triplea\downloadedMaps\red_sun_over_china-master.zip
Loading resources from the following paths: [D:\Daten\triplea\downloadedMaps\red_sun_over_china-master.zip, C:\Games\TripleA\assets]
Loading map: red_sun_over_china, from: D:\Daten\triplea\downloadedMaps\red_sun_over_china-master.zip
Loading resources from the following paths: [D:\Daten\triplea\downloadedMaps\red_sun_over_china-master.zip, C:\Games\TripleA\assets]
No color defined for Impassable.  Edit map.properties in the map folder to set it
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.awt.EventQueue.invokeAndWait(Unknown Source)
	at javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:122)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:49)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$133(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.remove(Unknown Source)
	at games.strategy.triplea.ui.mapdata.MapData.getPlayerColor(MapData.java:463)
	at games.strategy.triplea.ui.mapdata.MapData.impassableColor(MapData.java:483)
	at games.strategy.triplea.ui.screen.drawable.LandTerritoryDrawable.draw(LandTerritoryDrawable.java:27)
	at games.strategy.triplea.ui.screen.SmallMapImageManager.updateTerritoryOwner(SmallMapImageManager.java:79)
	at games.strategy.triplea.ui.MapPanel.initSmallMap(MapPanel.java:745)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:289)
	at games.strategy.triplea.TripleA.lambda$startGame$338(TripleA.java:124)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:313)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```
The old **Impassible/Impassable** issue... 
While it is correct in the `game.xml`, the `map.properties` file has `impassible` included.


Thank you for pointing it out, @idodoappo 
When changing from version 1.8 to 1.9 all maps had to be updated, too.
I this case the error seems to be caused by that small inaccuracy.

**Comment by ron-murhammer** [comment]
This should be resolved now.
