### ISSUE TITLE
Purchase Done Button Double Click

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#210]
If you rapidly double click the purchase done button, it can double count the purchased units and warn you that you have placed too many units. With a larger map, multiplayer to introduce even more lag, the click delay requirement is less and this defect is easier to hit.

Below is a screenshot that shows the problem. 

![double_purchase_button-click_bug](https://cloud.githubusercontent.com/assets/12397753/10185606/d066c494-66fe-11e5-8fb9-d6af02d87578.png)

**Comment by DanVanAtta** [comment]
Interestingly, this can get more severe. Where the PUs are subtracted, but then the units are not placed. Clicking 'no' on the continue prompt and in this case the game did not continue, gave this error:

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Cant remove more than player has of resource: PUs. current:0 toRemove: 57
	at games.strategy.engine.data.ResourceCollection.removeResource(ResourceCollection.java:62)
	at games.strategy.engine.data.ResourceCollection.subtract(ResourceCollection.java:130)
	at games.strategy.engine.data.ResourceCollection.subtract(ResourceCollection.java:125)
	at games.strategy.engine.data.ResourceCollection.difference(ResourceCollection.java:120)
	at games.strategy.triplea.ui.ProductionPanel.calculateLimits(ProductionPanel.java:232)
	at games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:79)
	at games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:43)
	at games.strategy.triplea.ui.PurchasePanel$4.actionPerformed(PurchasePanel.java:124)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DanVanAtta** [comment]
:white_flag:
