### ISSUE TITLE
Bans do not work in latest release

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2117]
Sadly i dont know how to reopen the old post.

Noticed with Lafay this eve that bans are also broken. 

They Still work with old tool box in old stable.  I guess sadly ya had better check all mod toolbox functions for the new release.

**Comment by ssoloff** [comment]
@prastle Can you please provide additional details?  I was unable to reproduce this using a 1.9.0.0.5805 client with a 1.9.0.0.3635 lobby.  I performed the following actions:

* As an admin:
    * Select **Admin > Toolbox > Ban Username**.
    * Enter name of user to ban.
    * Select **Minute** as unit of measurement.
    * Enter **1** for length of time.
    * Perform other actions in the UI to ensure the UI isn't blocked
* As the banned user:
    * Attempt to login.
    * Receive message indicating user is banned with a remaining time of 1 minute.
    * Wait 1 minute.
    * Attempt to login again.
    * Login is successful.

Are you using a different command to perform the ban?

**Comment by prastle** [comment]
i was using the .5802 I believe and right clicking on the user in lobby.  It brought up a java error.  I reverted to .3627 and it worked.

**Comment by RoiEXLab** [comment]
@prastle could you post the exact error message?

**Comment by ssoloff** [comment]
The key to reproducing this issue is to use a ban duration of one week, as @prastle originally mentioned in #2110 (I was not able to reproduce the problem when using a ban duration of one minute).  When using a one week ban duration, the UI doesn't lock up, but rather the ban is simply not executed.  The following exception is logged in the admin's **client**:

```
java.time.temporal.UnsupportedTemporalTypeException: Unit must not have an estimated duration
	at java.time.Duration.plus(Duration.java:701)
	at java.time.Duration.of(Duration.java:308)
	at games.strategy.engine.lobby.client.ui.LobbyFrame.lambda$3(LobbyFrame.java:191)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm debugging now.

**Comment by RoiEXLab** [comment]
@ssoloff I believe you found it already, but otherwhise [this line is the problem](https://github.com/triplea-game/triplea/blob/8908c8cac16b8b20fb5c14f8b408bc16371cdbbb/src/main/java/games/strategy/engine/lobby/client/ui/LobbyFrame.java#L191).
From the [javadocs](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#of-long-java.time.temporal.TemporalUnit-):
> Only a subset of units are accepted by this method. The unit must either have an exact duration or be ChronoUnit.DAYS which is treated as 24 hours. Other units throw an exception.

Weeks seem to not have an exact duration.

**Comment by ssoloff** [comment]
@RoiEXLab Yup, neither do months nor years.  I'm writing unit tests so I can refactor this code.

**Comment by RoiEXLab** [comment]
@prastle Everything should be working fine now in the latest pre-release, please double check if this is actually the case.

**Comment by prastle** [comment]
ok thanks guys but since it is very rare anyone is ever banned anymore ill take your word for it :)

**Comment by prastle** [comment]
current java error when right clicking a hosted game to view host info

using  1.9.0.0.5841_windows-64bit

Loading map: , from: C:\Users\john\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\, C:\Program Files\TripleA\assets]
Setting memory for new triplea process to: 1G
triplea.engine.version.bin:1.9
Loading map: , from: C:\Users\john\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\, C:\Program Files\TripleA\assets]
Setting memory for new triplea process to: 1G
triplea.engine.version.bin:1.9
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA\assets]
java.lang.IllegalStateException: Not all units present in:United Kingdom.  Trying to remove:[artillery owned by British, fighter owned by British] present:[artillery owned by British, factory owned by British, aaGun owned by British, artillery owned by British]
	at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:501)
	at games.strategy.engine.history.History.changeAdded(History.java:168)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:162)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.IllegalStateException: Not all units present in:United Kingdom.  Trying to remove:[artillery owned by British, fighter owned by British] present:[artillery owned by British, factory owned by British, aaGun owned by British, artillery owned by British]
	at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:501)
	at games.strategy.engine.history.History.changeAdded(History.java:168)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:162)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Raville_lobby_watcher (1)_lobby_watcher port:63339 ip:187.227.160.85
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:220)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:120)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:97)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
	at com.sun.proxy.$Proxy6.getConnections(Unknown Source)
	at games.strategy.engine.lobby.server.ModeratorController.getHostConnections(ModeratorController.java:326)
	at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$288(UnifiedMessenger.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: remote not found
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	at com.sun.proxy.$Proxy2.getHostConnections(Unknown Source)
	at games.strategy.engine.lobby.client.ui.LobbyGamePanel.getHostInfo(LobbyGamePanel.java:356)
	at games.strategy.engine.lobby.client.ui.LobbyGamePanel.lambda$getHostInfoAction$8(LobbyGamePanel.java:249)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Raville_lobby_watcher (1)_lobby_watcher port:63339 ip:187.227.160.85
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:220)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:120)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:97)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
	at com.sun.proxy.$Proxy6.getConnections(Unknown Source)
	at games.strategy.engine.lobby.server.ModeratorController.getHostConnections(ModeratorController.java:326)
	at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$288(UnifiedMessenger.java:303)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: remote not found
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	at com.sun.proxy.$Proxy2.getHostConnections(Unknown Source)
	at games.strategy.engine.lobby.client.ui.LobbyGamePanel.getHostInfo(LobbyGamePanel.java:356)
	at games.strategy.engine.lobby.client.ui.LobbyGamePanel.lambda$getHostInfoAction$8(LobbyGamePanel.java:249)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by ssoloff** [comment]
@prastle This appears to be a different problem.  Can you please open a new issue with the content of your previous comment?  Thanks!
