### ISSUE TITLE
Mod Toolbox broken when interacting with Zombie Games

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2125]
current java error when right clicking on a hosted game to view the host info

using 1.9.0.0.5841_windows-64bit
```
Loading map: , from: C:\Users\john\triplea\downloadedMaps
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps, C:\Program Files\TripleA\assets]
Setting memory for new triplea process to: 1G
triplea.engine.version.bin:1.9
Loading map: , from: C:\Users\john\triplea\downloadedMaps
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps, C:\Program Files\TripleA\assets]
Setting memory for new triplea process to: 1G
triplea.engine.version.bin:1.9
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA\assets]
Loading map: world_war_ii_revised, from: C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip
Loading resources from the following paths: [C:\Users\john\triplea\downloadedMaps\world_war_ii_revised-master.zip, C:\Program Files\TripleA\assets]
java.lang.IllegalStateException: Not all units present in:United Kingdom. Trying to remove:[artillery owned by British, fighter owned by British] present:[artillery owned by British, factory owned by British, aaGun owned by British, artillery owned by British]
at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
at games.strategy.engine.data.GameData.performChange(GameData.java:501)
at games.strategy.engine.history.History.changeAdded(History.java:168)
at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:162)
at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
java.lang.IllegalStateException: Not all units present in:United Kingdom. Trying to remove:[artillery owned by British, fighter owned by British] present:[artillery owned by British, factory owned by British, aaGun owned by British, artillery owned by British]
at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
at games.strategy.engine.data.GameData.performChange(GameData.java:501)
at games.strategy.engine.history.History.changeAdded(History.java:168)
at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:162)
at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Raville_lobby_watcher (1)_lobby_watcher port:63339 ip:187.227.160.85
at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:220)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:120)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:97)
at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
at com.sun.proxy.$Proxy6.getConnections(Unknown Source)
at games.strategy.engine.lobby.server.ModeratorController.getHostConnections(ModeratorController.java:326)
at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$288(UnifiedMessenger.java:303)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: remote not found
at java.lang.Thread.getStackTrace(Unknown Source)
at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
at com.sun.proxy.$Proxy2.getHostConnections(Unknown Source)
at games.strategy.engine.lobby.client.ui.LobbyGamePanel.getHostInfo(LobbyGamePanel.java:356)
at games.strategy.engine.lobby.client.ui.LobbyGamePanel.lambda$getHostInfoAction$8(LobbyGamePanel.java:249)
at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Raville_lobby_watcher (1)_lobby_watcher port:63339 ip:187.227.160.85
at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:220)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:120)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:97)
at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
at com.sun.proxy.$Proxy6.getConnections(Unknown Source)
at games.strategy.engine.lobby.server.ModeratorController.getHostConnections(ModeratorController.java:326)
at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$288(UnifiedMessenger.java:303)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: remote not found
at java.lang.Thread.getStackTrace(Unknown Source)
at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
at com.sun.proxy.$Proxy2.getHostConnections(Unknown Source)
at games.strategy.engine.lobby.client.ui.LobbyGamePanel.getHostInfo(LobbyGamePanel.java:356)
at games.strategy.engine.lobby.client.ui.LobbyGamePanel.lambda$getHostInfoAction$8(LobbyGamePanel.java:249)
at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.AbstractButton.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:325)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by ssoloff** [comment]
Just pulling out the key bits from the above stack trace here:

```
games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.lobby.server.RemoteHostUtils:Raville_lobby_watcher (1)_lobby_watcher port:63339 ip:187.227.160.85
    at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
    at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:220)
    at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:120)
    at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:97)
    at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
    at com.sun.proxy.$Proxy6.getConnections(Unknown Source)
    at games.strategy.engine.lobby.server.ModeratorController.getHostConnections(ModeratorController.java:326)
    at sun.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
    at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
    at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
    at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$288(UnifiedMessenger.java:303)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: remote not found
    at java.lang.Thread.getStackTrace(Unknown Source)
    at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
    at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
    at com.sun.proxy.$Proxy2.getHostConnections(Unknown Source)
    at games.strategy.engine.lobby.client.ui.LobbyGamePanel.getHostInfo(LobbyGamePanel.java:356)
    at games.strategy.engine.lobby.client.ui.LobbyGamePanel.lambda$getHostInfoAction$8(LobbyGamePanel.java:249)
    at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:47)
    <. . . snip . . .>
```

**Comment by ssoloff** [comment]
I tried to reproduce using the following setup:

* Lobby running 1.9.0.0.3635
* Player hosting game in lobby running 1.9.0.0.3635
* Admin connected to lobby running 1.9.0.0.5841

As the admin, I was able to view the hosted game info without a problem (i.e. right click the game and select **Host Information**).

At first, I believed that somehow the game hosted by Raville at 187.227.160.85:63339 had been simply disconnected from the lobby prior to running the Host Information command.  However, after digging into the code, it looks like this exception is returned by the remote when it can't find a corresponding endpoint for the RMI request (i.e. the `IRemoteHostUtils#getConnections()` method cannot be found, in this case).  This method has been present in the code since Feb 2014, so it's unlikely Raville is hosting a game with a client that old. :smile:

@ron-murhammer @DanVanAtta In your experience, have either of you ever seen a similar exception?  Can you provide any insight into what may be the possible root cause?

**Comment by ssoloff** [comment]
For reference, the code around the location where the exception is thrown is copied below (from UnifiedMessengerHub.java:77-93):

```java
final HubInvoke invoke = (HubInvoke) msg;
final Collection<INode> endPointCols = new ArrayList<>();
synchronized (endPointMutex) {
  if (endPoints.containsKey(invoke.call.getRemoteName())) {
    endPointCols.addAll(endPoints.get(invoke.call.getRemoteName()));
  }
}
// the node will already have routed messages to local invokers
endPointCols.remove(from);
if (endPointCols.isEmpty()) {
  if (invoke.needReturnValues) {
    final RemoteMethodCallResults results =
        new RemoteMethodCallResults(new RemoteNotFoundException("Not found:" + invoke.call.getRemoteName()));
    send(new SpokeInvocationResults(results, invoke.methodCallID), from);
  }
  // no end points, this is ok, we
  // we are a channel with no implementors
} else {
  invoke(invoke, endPointCols, from);
}
```

So, I guess there really are two possibilities for `endPointCols` to be empty:

1. No remote node has registered an endpoint for the target method.
1. There are no remote nodes.

**Comment by prastle** [comment]
The problem only occurs sometimes.  I have not seen it occur in old stable.  Sorry only other 
info i can give.

**Comment by DanVanAtta** [comment]
I think this may have been an ongoing issue. I believe I've seen this error before. My hypothesis on this is it is a result of the fact we do not explicitly disconnect network games. So what has happened I believe may be a network connection was lost, a client disconnect, but the disconnect was never registered explicitly and we wound up with a zombie connection.

Moderators, for example, have to periodically remove zombie games from the lobby. They are removed normally without manual intervention too, though AFAIK the timeout or check-back period to do that is something pretty insane like several hours.

**Comment by prastle** [comment]
@DanVanAtta    Gd pt.  I should have mentioned that it was a zombie game.  I was just trying to remove the ghost. Interesting that I could remove the ghost player with the old stable tho a minute or so later when I lohgged back in with old stable.  Anyways you guys are trucking right along with releases so i guess we wait until some mods have their status back with new database and test that way.
