### ISSUE TITLE
Bids on Hard AI

### ISSUE THREAD

**Issue by gdhodder** [triplea-game/triplea#2129]
Hi..  I am playing all Good players as HUMAN all Evil as Hard AI.. each evil faction has a bid of 1.5x their base income.  The game bombs after the bid purchase before round 1.  I wanted to attach the save, but can't figure out how to...

### My Operating System: 
Windows 7

### TripleA version: 
1.9

### Map: 
Lord of the Rings Middle Earth

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Human Good players, hard AI for all evil players with each evil player having a bid equal to 1.5 times their base income

### Instead of this error, what should have happened? 
Play should begin with Saurman's move, but the error box pops and the game doesn't bring up the dialog for play to continue

**Comment by ssoloff** [comment]
@gdhodder You can attach a save game by zipping it first and then dragging & dropping it into the comment box (you can also click the "selecting them" link at the bottom of the comment box and use the file chooser to select the file you want to upload).

**Comment by DanVanAtta** [comment]
Are you able to hit the error consistently (every time) @gdhodder ? If you can, please also copy/paste the error message text that you see to this ticket.

I tried starting Middle Earth with various bid and income options set for the AI and was not able to see a crash. The AI did the bid and would start Saurmon's turn. I tried using latest development and v5129

**Comment by gdhodder** [comment]
[lotr-hard-1-5x-bid-rd1-gd.zip](https://github.com/triplea-game/triplea/files/1170867/lotr-hard-1-5x-bid-rd1-gd.zip)

I attached the file.. I only tried the setting twice.. (now 3 times) and same thing.. the dialog box come up with the message I am pasting below.. and a new window opens to select the players (human/AI) again.. but the game window is still open too... here is the Console output.

triplea.engine.version.bin:1.9
Loading map: middle_earth, from: C:\Users\Hodder Family\triplea\downloadedMaps\middle_earth-master.zip
Loading resources from the following paths: [C:\Users\Hodder Family\triplea\downloadedMaps\middle_earth-master.zip, C:\Program Files (x86)\TripleA_1.9.0.0.3566\assets]
Loading map: middle_earth, from: C:\Users\Hodder Family\triplea\downloadedMaps\middle_earth-master.zip
Loading resources from the following paths: [C:\Users\Hodder Family\triplea\downloadedMaps\middle_earth-master.zip, C:\Program Files (x86)\TripleA_1.9.0.0.3566\assets]
java.lang.NullPointerException
	at games.strategy.triplea.delegate.BidPlaceDelegate.canProduce(BidPlaceDelegate.java:40)
	at games.strategy.triplea.delegate.BidPlaceDelegate.canProduce(BidPlaceDelegate.java:33)
	at games.strategy.triplea.delegate.AbstractPlaceDelegate.isValidPlacement(AbstractPlaceDelegate.java:539)
	at games.strategy.triplea.delegate.AbstractPlaceDelegate.placeUnits(AbstractPlaceDelegate.java:201)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:148)
	at com.sun.proxy.$Proxy6.placeUnits(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:172)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:150)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:132)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:101)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:50)
	at com.sun.proxy.$Proxy6.placeUnits(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.gamePlayer.GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:162)
	at com.sun.proxy.$Proxy6.placeUnits(Unknown Source)
	at games.strategy.triplea.ai.proAI.ProBidAI.doPlace(ProBidAI.java:618)
	at games.strategy.triplea.ai.proAI.ProBidAI.placeSeaUnits(ProBidAI.java:533)
	at games.strategy.triplea.ai.proAI.ProBidAI.bidPlace(ProBidAI.java:470)
	at games.strategy.triplea.ai.proAI.ProAI.place(ProAI.java:266)
	at games.strategy.triplea.ai.AbstractAI.start(AbstractAI.java:441)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:531)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:424)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:259)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$116(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:62)
	at com.sun.proxy.$Proxy6.placeUnits(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.gamePlayer.GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:162)
	at com.sun.proxy.$Proxy6.placeUnits(Unknown Source)
	at games.strategy.triplea.ai.proAI.ProBidAI.doPlace(ProBidAI.java:618)
	at games.strategy.triplea.ai.proAI.ProBidAI.placeSeaUnits(ProBidAI.java:533)
	at games.strategy.triplea.ai.proAI.ProBidAI.bidPlace(ProBidAI.java:470)
	at games.strategy.triplea.ai.proAI.ProAI.place(ProAI.java:266)
	at games.strategy.triplea.ai.AbstractAI.start(AbstractAI.java:441)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:531)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:424)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:259)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$116(AbstractLauncher.java:43)
	at java.lang.Thread.run(Unknown Source)

**Comment by gdhodder** [comment]
Oh.. one other thing I thought of.. I did save the map options as default.. with bid amounts and HUMAN for evil, AI GOOD...  I loaded that game, then changed the players to be AI Evile, HUMAN good.. and resaved under a new name.. then the problem occured.

**Comment by ron-murhammer** [comment]
@gdhodder Can you try downloading the latest version of TripleA from: http://www.triplea-game.org/download/

Then try starting a new game with the same settings. I wasn't able to reproduce the error with your save game or starting various games with different bids on the latest version.

**Comment by gdhodder** [comment]
That seems to have worked for me.. thank you... now I can continue my work on finding a good bid level to even the scale in that scenario.. if anyone has tips related to that too.. I'll take em!  Thanks again

**Comment by ron-murhammer** [comment]
@gdhodder Glad that resolved it. In the latest version in addition to bid, you can also give players an per turn income modifier either as a percentage of their income or a flat amount. These options can be seen on the player selection screen to the right.

Also feedback on the AI is appreciated and can be submitted in our new forums here: https://forums.triplea-game.org/topic/105/ai-development-discussion-and-feedback
