### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#2507]
I just installed TripleA v1.9.0.0.7062
and got the following error message:
```
triplea.engine.version.bin:1.9
java.lang.NullPointerException
	at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getDefaultBackgroundColor(SubstanceColorUtilities.java:759)
	at org.pushingpixels.substance.internal.utils.SubstanceColorUtilities.getBackgroundFillColor(SubstanceColorUtilities.java:661)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installDefaults(SubstancePanelUI.java:74)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installDefaults(SubstancePanelUI.java)
	at java.desktop/javax.swing.plaf.basic.BasicPanelUI.installUI(Unknown Source)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.__org__pushingpixels__substance__internal__ui__SubstancePanelUI__installUI(SubstancePanelUI.java)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.installUI(SubstancePanelUI.java)
	at java.desktop/javax.swing.JComponent.setUI(Unknown Source)
	at java.desktop/javax.swing.JPanel.setUI(Unknown Source)
	at java.desktop/javax.swing.JPanel.updateUI(Unknown Source)
	at java.desktop/javax.swing.JPanel.<init>(Unknown Source)
	at java.desktop/javax.swing.JPanel.<init>(Unknown Source)
	at java.desktop/javax.swing.JPanel.<init>(Unknown Source)
	at games.strategy.engine.framework.startup.ui.SetupPanel.<init>(SetupPanel.java:25)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.<init>(MetaSetupPanel.java:45)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showSelectType(SetupPanelModel.java:33)
	at games.strategy.engine.framework.GameRunner.lambda$main$106(GameRunner.java:159)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$110(GameRunner.java:255)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:330)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
java.lang.NullPointerException
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$110(GameRunner.java:255)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:330)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

The 2 latter exceptions are caused by the first exception, the mainFrame field is not getting initialized due to the first exception and therefore we get the subsequent NullPointerException.
I tried resetting the java preferences storage, without any result.
When restarting TripleA I get an additional error message:
![grafik](https://user-images.githubusercontent.com/8350879/31610082-032327b8-b277-11e7-91d2-76ce852be70c.png)
Which can be translated to `The procedureentry point "JVM_GetLastErrorString" couldn't be found in the "C:\Program Files\Java\jre1.8.0_144\bin\java.dll" DLL`.
When clicking `OK` the error console opens with the stacktrace you see above.

I'm using Windows 10 64bit with Java 8 144 64 bit btw.
This problem only occurs when installing TripleA via the installer, in my IDE it works fine without any problems.
I'll try to figure out which version works for me

**Comment by RoiEXLab** [comment]
It seems this regression was introduced in #2396 (not 100% sure, but 90%)
It does probably not occur in my IDE, because of different settings (they are stored at a different location and therefore I didn't reset them).
But I have no idea on how to really reproduce it.
It crashes when a substance LAF is set, and doesn't crash when the "default Windows" LAF is set, which is weird.

**Comment by panther2** [comment]
Strange, I am always using `SubstanceGraphit`, I am using the windows installer, Java 8 u144, but Windows 7 64 bit. I have never experienced this with any TripleA version. So I cannot reproduce it.

**Comment by RoiEXLab** [comment]
I don't know why it's occuring either

**Comment by ssoloff** [comment]
I cannot reproduce the exception in the following environment:

* TripleA_1.9.0.0.7062_windows-64bit.exe
* Windows 8.1
* Java 8 u121

I tried both with my existing settings and after clearing them; there was no exception in either case.

> It does probably not occur in my IDE, because of different settings (they are stored at a different location and therefore I didn't reset them).

AFAIK, there should be no difference.  On Windows, user preferences are stored in the registry under `HKCU\Software\JavaSoft\Prefs`.  On Unix, user preferences are stored under `~/.java/.userPrefs`.  I suppose there may be something like an environment variable you could use to explicitly change this location, but that would probably be standing out in your IDE launch configuration.

> Which can be translated to The procedureentry point "JVM_GetLastErrorString" couldn't be found in the "C:\Program Files\Java\jre1.8.0_144\bin\java.dll" DLL.
> When clicking OK the error console opens with the stacktrace you see above.

It almost seems like your JRE binaries have been corrupted.  Did you try reinstalling Java?

**Comment by prastle** [comment]
Cant say I have seen it with windows ten either.

**Comment by RoiEXLab** [comment]
Ok I'll try to investigate further.

**Comment by DanVanAtta** [comment]
@RoiEXLab did the game still launch, or fatal on startup?

**Comment by RoiEXLab** [comment]
The game did not launch. 
It might be the case that there's an error with my java installation, I'll try to fix it and give you an update once I figured out how to fix it...

**Comment by RoiEXLab** [comment]
Ok I know the cause of this issue.
This issue occurs when java 9 is installed on your PC.
For some reason install4j always uses java 9 which causes this issue.

**Comment by ssoloff** [comment]
Nice!

Does this mean that the Substance L&Fs are incompatible with Java 9?

**Comment by RoiEXLab** [comment]
Seems like it...

**Comment by RoiEXLab** [comment]
@ssoloff I just found this comment:
https://github.com/triplea-game/triplea/blob/f9f81445911fcd99527525257af985b90475a9ac/src/main/java/games/strategy/engine/framework/lookandfeel/LookAndFeel.java#L72-L77

Digging further into this

**Comment by RoiEXLab** [comment]
The "workaround" didn't solve the issue.
I didn't found a solution either.
However I found a github project which "maintains"/keeps updating this library, unfortunately without any sort of maven repo: https://github.com/kirill-grouchnikov/substance

**Comment by ssoloff** [comment]
@ron-murhammer @DanVanAtta Just calling your attention to the previous five comments.  This may make the priority of #2317 a bit higher.  It appears the Swing client, in its current state, will not start correctly on Java 9 with the Substance L&F.  This could become a problem with the proliferation of Java 9.
