### ISSUE TITLE
Game History Error: Could Not Set Property Attack

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2606]
Here is a TWW **save game** that can reproduce: 
[1510445411381-triplea_361_us2.zip](https://github.com/triplea-game/triplea/files/1469385/1510445411381-triplea_361_us2.zip)

**Steps:**
1. Load save game
2. Open history panel
3. Click anywhere before USA's last turn

**Error:**
java.lang.IllegalStateException: Could not set property:attack subject:UnitAttachment attached to:UnitType{name=americanBattleship} with name:unitAttachment new value:7
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:19)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:34)
	at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:512)
	at games.strategy.engine.history.History.gotoNode(History.java:121)
	at games.strategy.triplea.ui.history.HistoryPanel.gotoNode(HistoryPanel.java:260)
	at games.strategy.triplea.ui.history.HistoryPanel.treeSelectionChanged(HistoryPanel.java:250)
	at games.strategy.triplea.ui.history.HistoryPanel.lambda$2(HistoryPanel.java:171)
	at javax.swing.JTree.fireValueChanged(JTree.java:2927)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at javax.swing.JTree.setSelectionPath(JTree.java:1634)
	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:279)
	at java.awt.Component.processMouseEvent(Component.java:6532)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: java.lang.ClassCastException@1206461
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:17)
	... 54 more

**Comment by ron-murhammer** [comment]
I think this is similar to #1743. I think the problem is actually that a while back many of the UnitAttachment setters were changed to primitives (int) instead of objects (Integer). Can someone else take a look to confirm that is the issue?

**Comment by ssoloff** [comment]
I was able to reproduce using 1.9.0.0.7522 and the attached save game.

I'm also seeing numerous occurrences of the following errors:

```
MISSING IMAGE (this unit or image will be invisible): UnitType{name=Train}
MISSING IMAGE (this unit or image will be invisible): UnitType{name=Rail}
```

Are you using a pre-release TWW map?

**Comment by ssoloff** [comment]
As suggested, I confirmed the following change results in no error:

```diff
diff --git a/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java b/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
index 982adb811..0e76dae80 100644
--- a/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
+++ b/src/main/java/games/strategy/triplea/attachments/UnitAttachment.java
@@ -1444,7 +1444,7 @@ public class UnitAttachment extends DefaultAttachment {
   }
 
   @GameProperty(xmlProperty = true, gameProperty = true, adds = false)
-  public void setAttack(final int s) {
+  public void setAttack(final Integer s) {
     m_attack = s;
   }
 
```

**Comment by ron-murhammer** [comment]
@ssoloff Yeah, its a pre-release so you are missing some image assets (not a real error). I have a feeling there are a number of property setters across various attachments that need reverted to Integer instead of int.

**Comment by ron-murhammer** [comment]
@ssoloff @RoiEXLab I believe we need to essentially revert the portions of #1078 which changed attachments setters to primitives.
