### ISSUE TITLE
Game keeps crashing

### ISSUE THREAD

**Issue by jred1990** [triplea-game/triplea#2608]
### Do you have the exact error text? Please copy/paste if so:
```
triplea.engine.version.bin:1.9
Loading map: middle_earth, from: C:\Users\Joshua\triplea\downloadedMaps\middle_earth-master.zip
Loading resources from the following paths: [C:\Users\Joshua\triplea\downloadedMaps\middle_earth-master.zip, C:\Program Files (x86)\TripleA\assets]
Loading map: middle_earth, from: C:\Users\Joshua\triplea\downloadedMaps\middle_earth-master.zip
Loading resources from the following paths: [C:\Users\Joshua\triplea\downloadedMaps\middle_earth-master.zip, C:\Program Files (x86)\TripleA\assets]
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy12.selectCasualties(Unknown Source)
	at games.strategy.triplea.delegate.BattleCalculator.selectCasualties(BattleCalculator.java:514)
	at games.strategy.triplea.delegate.Fire.selectCasualties(Fire.java:161)
	at games.strategy.triplea.delegate.Fire.access$100(Fire.java:21)
	at games.strategy.triplea.delegate.Fire$2.execute(Fire.java:221)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:41)
	at games.strategy.triplea.delegate.MustFightBattle.fight(MustFightBattle.java:380)
	at games.strategy.triplea.delegate.BattleTracker.fightBattleIfOnlyOne(BattleTracker.java:1176)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:97)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:506)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:401)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:266)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$169(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.delegate.DelegateExecutionManager.lambda$createOutboundImplementation$113(DelegateExecutionManager.java:116)
	... 15 more
Caused by: games.strategy.engine.message.RemoteNotFoundException: Not found:games.strategy.engine.framework.ServerGame.PLAYER_REMOTE.Neutral
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:89)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:224)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWaitRemote(UnifiedMessenger.java:122)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:99)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:51)
	at com.sun.proxy.$Proxy12.selectCasualties(Unknown Source)
	... 20 more
Caused by: java.lang.IllegalStateException: remote not found
	at java.lang.Thread.getStackTrace(Unknown Source)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	... 21 more
```

**Comment by RoiEXLab** [comment]
@jred1990 Thanks for your bug report, we are aware of this issue.
Fortunately it has been fixed in the latest release that has been released just now and is now available on our [official website](http://triplea-game.org).

If you are still experiencing issues after updating, please continue to report them here, if nobody reports issues, they can't be fixed.
