### ISSUE TITLE
.7611 does not seem to run headless exe anymore

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2636]
### Any additional information that may help:
Exception in thread "main" java.lang.IllegalArgumentException: Too much arguments: [triplea.game.host.console=false, triplea.game=, triplea.server=true, triplea.port=3363, triplea.lobby.host=45.79.144.53, triplea.lobby.port=3304, triplea.name=Bot25_Pras1, triplea.lobby.game.hostedBy=Bot25_Pras1, triplea.lobby.game.supportEmail=prastle5@hotmail.com, triplea.lobby.game.comments=automated_host, triplea.lobby.game.reconnection=172800]
        at games.strategy.engine.framework.ArgParser.parseRemaining(ArgParser.java:72)
        at games.strategy.engine.framework.ArgParser.handleCommandLineArgs(ArgParser.java:49)
        at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.main(HeadlessGameServer.java:655)
Press any key to continue . . .

**Comment by RoiEXLab** [comment]
@prastle This is a configuration issue on your end:
Due to internal CLI parsing changes you now need to prefix the arguments in your batch file (assuming you have one) with `-P`
See https://github.com/triplea-game/lobby/pull/46/files for clarification
