### ISSUE TITLE
Mac - automatic map missing download does not work, map missing case generally broken.

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2647]
Repro:
- 1. install game
- 2. join lobby
- 3. join any game in progress
- 4. click 'cancel'
- 5. click 'yes' to download missing map

Notice:
- Notice, it appears there is a new player that has joined the game (verify this more, but there are more problems)
- Notice that after step 3 there are error messages and a NPE, and a connect to game dialog window. None of these should be visible. The correct "would you like to download" dialog is only shown on step 4.
- On step 5, after saying yes to map download, nothing happens! IN error console, the request is intentionally ignored for some reason:
```
Nov 26, 2017 3:57:53 PM games.strategy.engine.framework.map.download.DownloadMapsWindow logMapDownloadRequestIgnored
INFO: ignoring request to download maps because window initialization has already started
```

Screenshot after connecting to map missing game:

<img width="1448" alt="screen shot 2017-11-26 at 3 53 20 pm" src="https://user-images.githubusercontent.com/12397753/33245849-408df004-d2c2-11e7-9285-74ea2a2dedfd.png">

-----

If you click 'cancel' on the above join dialog, *then* you see the expected dialog. 

<img width="699" alt="screen shot 2017-11-26 at 3 53 34 pm" src="https://user-images.githubusercontent.com/12397753/33245869-87bcdd46-d2c2-11e7-8a67-c881650c01f3.png">

---------

NPE errro message:
```
triplea.engine.version.bin:1.9
java.lang.NullPointerException
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.filterMaps(DownloadMapsWindow.java:330)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.<init>(DownloadMapsWindow.java:234)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.<init>(DownloadMapsWindow.java:46)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.createAndShow(DownloadMapsWindow.java:169)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.initialize(DownloadMapsWindow.java:158)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.showAndDownload(DownloadMapsWindow.java:131)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindowAndDownload(DownloadMapsWindow.java:104)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:68)
	at swinglib.JButtonBuilder.lambda$build$1090(JButtonBuilder.java:49)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.filterMaps(DownloadMapsWindow.java:330)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.<init>(DownloadMapsWindow.java:234)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.<init>(DownloadMapsWindow.java:46)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.createAndShow(DownloadMapsWindow.java:169)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.initialize(DownloadMapsWindow.java:158)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow$SingletonManager.showAndDownload(DownloadMapsWindow.java:131)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindowAndDownload(DownloadMapsWindow.java:104)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.showDownloadMapsWindow(DownloadMapsWindow.java:68)
	at swinglib.JButtonBuilder.lambda$build$1090(JButtonBuilder.java:49)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Failed to start Game
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:122)
	at games.strategy.engine.framework.startup.mc.ClientModel.lambda$startGameInNewThread$130(ClientModel.java:324)
	at java.lang.Thread.run(Thread.java:748)
Caused by: games.strategy.engine.framework.startup.launcher.MapNotFoundException
	at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:62)
	at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:71)
	at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:228)
	at games.strategy.triplea.TripleA.lambda$startGame$382(TripleA.java:124)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Nov 26, 2017 3:57:53 PM games.strategy.engine.framework.map.download.DownloadMapsWindow logMapDownloadRequestIgnored
INFO: ignoring request to download maps because window initialization has already started

```

**Comment by ssoloff** [comment]
Hmm, I'm getting slightly different results when running this scenario on Linux.

1. Join lobby game for a map not installed locally (NWO in my case).
1. TripleA main menu is displayed.
1. The following appear to happen nearly simultaneously:
    1. **TripleA Console** is opened with `InvocationTargetException` caused by `MapNotFoundException` as above.
    1. **Download Map?** dialog is displayed prompting to download NWO map.
    1. **Client options** dialog is displayed as above.
1. Click **Cancel** in **Client options** dialog.
1. Click **Yes** in **Download Map?** dialog.
1. **Download Maps** window is opened with NWO map download in progress.
1. Close **Download Maps** window.
1. **Quit** TripleA main menu and return to lobby.
1. Join same lobby game as in (1).
1. Lobby game displayed as expected.

The NPEs seem to be caused by a `null` entry in the list returned from `ClientContext#getMapDownloadList()`.  That seems odd and is what's not happening on my system to repro the NPEs.  Additional repro steps to get that to happen would be helpful.

The presence of that `INFO` message basically means someone called `DownloadMapsWindow#showDownloadMapsWindowAndDownload()` while a previous call to the same method is already in progress.  It's intent was simply to flag a potential programmer error because such a situation shouldn't occur.  However, my guess is the NPEs are somehow triggering a second invocation of `showDownloadMapsWindowAndDownload()`, which causes the `INFO`message.  I would focus on the NPEs first before digging into why `showDownloadMapsWindowAndDownload()` is being called multiple times.  The latter is most likely being caused by us catching a runtime exception (the NPE in this case) and not letting it bubble up and crash the process.

**Comment by ssoloff** [comment]
> The NPEs seem to be caused by a null entry in the list returned from `ClientContext#getMapDownloadList()`

Correction...   The NPEs seem to be raised because the _list_ returned by `ClientContext#getMapDownloadList()` is `null`.  If one of the elements were `null`, the NPE message would say something like, "Maps list contained null element" (see `DownloadMapsWindow.java:330`).

**Comment by ssoloff** [comment]
Actually, what I said about that error message in the NPE is not true.  The `checkNotNull()` call on `DownloadMapsWindow.java:330` is malformed: it's passing the error message as the first parameter and the argument to check for `null` as the second parameter, which is the opposite of what it's supposed to be.  So that `checkNotNull()` call will always succeed.  I'll submit a PR to fix that.

That would also seem to confirm that it's `maps` itself that is `null`.  However, from a quick walk of the call tree starting in `ClientContext#getMapDownloadList()`, I can't seem to find a code path that could result in a `null` return value from this method. 🤔
