### ISSUE TITLE
Bot Joining Issue with 1.9.0.0.7652

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#2662]
### My Operating System:
Win 10
### TripleA version:
.7652
### Map:
any
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try joining a bot
### Do you have the exact error text? Please copy/paste if so
```
triplea.engine.version.bin:1.9
java.lang.NoClassDefFoundError: com/google/common/collect/FluentIterable
	at games.strategy.net.MacFinder.convertMacBytesToString(MacFinder.java:190)
	at games.strategy.net.MacFinder.getMacAddress(MacFinder.java:46)
	at games.strategy.net.MacFinder.getHashedMacAddress(MacFinder.java:28)
	at games.strategy.engine.framework.startup.mc.ClientModel.createClientMessenger(ClientModel.java:150)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showClient(SetupPanelModel.java:61)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$118(GameRunner.java:274)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.FluentIterable
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at sun.misc.Resource.getBytes(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	... 28 more
java.lang.NoClassDefFoundError: com/google/common/collect/FluentIterable
	at games.strategy.net.MacFinder.convertMacBytesToString(MacFinder.java:190)
	at games.strategy.net.MacFinder.getMacAddress(MacFinder.java:46)
	at games.strategy.net.MacFinder.getHashedMacAddress(MacFinder.java:28)
	at games.strategy.engine.framework.startup.mc.ClientModel.createClientMessenger(ClientModel.java:150)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showClient(SetupPanelModel.java:61)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$118(GameRunner.java:274)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:346)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.FluentIterable
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.util.zip.ZipException: invalid distance too far back
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at sun.misc.Resource.getBytes(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	... 28 more
```
### Instead of this error, what should have happened?
You should be able to join the bot.
### Any additional information that may help:
Does not occur with .7621

**Comment by ssoloff** [comment]
I tried reproducing this on both Linux and Windows x64 by joining bot 60 using a 7652 client, but I was able to join the game without a problem.  Can someone else try it?  It almost looks like a corrupt Jar in the installation.

**Comment by prastle** [comment]
could be @ssoloff i can try later with reinstall

**Comment by ssoloff** [comment]
@prastle If you still happen to have the 7652 installer that you used, you can check its integrity using the `certutil` command on Windows:

<pre>
C:\Users\me\Downloads><b>certutil -hashfile TripleA_1.9.0.0.7652_windows-64bit.exe SHA1</b>
SHA1 hash of file TripleA_1.9.0.0.7652_windows-64bit.exe:
5d 09 60 2a d6 71 ca c3 98 07 3e 76 66 87 11 a8 21 c3 6d 2e
CertUtil: -hashfile command completed successfully.
</pre>

As shown above, the SHA-1 hash of this file should match `5d09602ad671cac398073e76668711a821c36d2e`.

**Comment by RoiEXLab** [comment]
I agree @ssoloff, really looks like a corrupt jar, given that this is a NoClassDefFoundError and not an exception

**Comment by prastle** [comment]
@RoiEXLab  and @ssoloff  reinstalled with .7667 hopefully corrupt dl feel free to delete

**Comment by prastle** [comment]
Works fine with .7667
