### ISSUE TITLE
Can't Join Lobby

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#2801]
Get this error when trying to join lobby with 8230:
```
Failed while setting up logging
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at games.strategy.net.nio.SocketWriteData.<init>(SocketWriteData.java:39)
	at games.strategy.net.nio.Encoder.write(Encoder.java:39)
	at games.strategy.net.nio.NioSocket.send(NioSocket.java:68)
	at games.strategy.net.nio.ClientQuarantineConversation.send(ClientQuarantineConversation.java:161)
	at games.strategy.net.nio.ClientQuarantineConversation.<init>(ClientQuarantineConversation.java:49)
	at games.strategy.net.ClientMessenger.<init>(ClientMessenger.java:98)
	at games.strategy.net.ClientMessenger.<init>(ClientMessenger.java:49)
	at games.strategy.engine.lobby.client.login.LobbyLogin.login(LobbyLogin.java:80)
```

**Comment by ron-murhammer** [comment]
The problem appears to be related to building with JDK9 while targeting and running on JDK9: https://github.com/plasma-umass/doppio/issues/497

**Comment by ssoloff** [comment]
Confirmed I can't reproduce the issue when running from a Java 8 build.

I'll switch Travis to produce releases from the Java 8 build instead of the Java 9 build.  Standby.

**Comment by ssoloff** [comment]
I believe the linked issue points out a defect in our Java 9 build setup (which, coincidentally, I now remember running into several years ago when trying to use JDK 7/8 to build for Java 6).  Basically, we need to specify the `-bootclasspath` option pointing to a Java 8 runtime so the compiler uses the correct signatures.

The poster in the linked issue also raised awareness of a relatively new option ([`--release`](http://openjdk.java.net/jeps/247)) that is supposed to handle what the three previously-required command line options did.  It appears it simply standardizes the location of the alternate runtimes (and uses a stripped-down class file format to keep the size reasonable).

There's probably some issues that need to be worked out to achieve this in a straightforward way on both Travis and a dev's machine.  I'll open a new issue for discussion.

**Comment by ssoloff** [comment]
Confirmed I can connect to the lobby using build 8233.
