### ISSUE TITLE
error message pop-up text is blank with `null` input

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2919]
Ran into an initialization error, can be repro'd by mangling the name of `game_engine.properties`:

![can_get_null](https://user-images.githubusercontent.com/12397753/35478442-7fb7f198-0392-11e8-942f-0d5bd1d155ce.png)

Notice in the above we have an error message box with no text. We would expect instead to see some text, perhaps boiler plate, but very ideally we'd see "Caused by: java.lang.IllegalArgumentException: Property file not found: /home/dan/work/triplea/game_engine.properties"

**Comment by ssoloff** [comment]
I'm getting a bit more of a stack trace when I repro:

```
org.pushingpixels.substance.api.UiThreadingViolationException: Component creation must be done on Event Dispatch Thread
	at org.pushingpixels.substance.internal.utils.SubstanceCoreUtilities.testComponentCreationThreadingViolation(SubstanceCoreUtilities.java:1878)
	at org.pushingpixels.substance.internal.ui.SubstancePanelUI.createUI(SubstancePanelUI.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:769)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at javax.swing.JRootPane.createGlassPane(JRootPane.java:546)
	at javax.swing.JRootPane.<init>(JRootPane.java:366)
	at javax.swing.JFrame.createRootPane(JFrame.java:286)
	at javax.swing.JFrame.frameInit(JFrame.java:267)
	at javax.swing.JFrame.<init>(JFrame.java:234)
	at games.strategy.debug.ErrorMessage.<init>(ErrorMessage.java:32)
	at games.strategy.debug.ErrorMessage.<clinit>(ErrorMessage.java:30)
	at games.strategy.debug.ClientLogger.showErrorMessage(ClientLogger.java:98)
	at games.strategy.debug.ClientLogger.logError(ClientLogger.java:74)
	at games.strategy.triplea.ui.ErrorHandler.handle(ErrorHandler.java:36)
	at games.strategy.triplea.ui.ErrorHandler.uncaughtException(ErrorHandler.java:23)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
UIDefaults.getUI() failed: createUI() failed for javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.FlowLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=] java.lang.reflect.InvocationTargetException
java.lang.Error
	at javax.swing.UIDefaults.getUIError(UIDefaults.java:730)
	at javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:130)
	at javax.swing.UIDefaults.getUI(UIDefaults.java:775)
	at javax.swing.UIManager.getUI(UIManager.java:1016)
	at javax.swing.JPanel.updateUI(JPanel.java:126)
	at javax.swing.JPanel.<init>(JPanel.java:86)
	at javax.swing.JPanel.<init>(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:117)
	at javax.swing.JRootPane.createGlassPane(JRootPane.java:546)
	at javax.swing.JRootPane.<init>(JRootPane.java:366)
	at javax.swing.JFrame.createRootPane(JFrame.java:286)
	at javax.swing.JFrame.frameInit(JFrame.java:267)
	at javax.swing.JFrame.<init>(JFrame.java:234)
	at games.strategy.debug.ErrorMessage.<init>(ErrorMessage.java:32)
	at games.strategy.debug.ErrorMessage.<clinit>(ErrorMessage.java:30)
	at games.strategy.debug.ClientLogger.showErrorMessage(ClientLogger.java:98)
	at games.strategy.debug.ClientLogger.logError(ClientLogger.java:74)
	at games.strategy.triplea.ui.ErrorHandler.handle(ErrorHandler.java:36)
	at games.strategy.triplea.ui.ErrorHandler.uncaughtException(ErrorHandler.java:23)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1959)
```

Looks like the reason the window is empty is because, somehow, the UI component creation is occurring off the EDT.

**Comment by DanVanAtta** [comment]
Ah, I simplified repro step, exact repo can be done with this branch:  https://github.com/triplea-game/triplea/pull/2920, without this commit: https://github.com/triplea-game/triplea/pull/2920/commits/16364ecb5c2b193df95a4481db317d9e40cfb09d

It's interesting that just renaming the `game_engine.properties` file woudl not repro exactly.

**Comment by ssoloff** [comment]
Here's a hack fix for the off-EDT component creation:

```diff
diff --git a/src/main/java/games/strategy/debug/ClientLogger.java b/src/main/java/games/strategy/debug/ClientLogger.java
index 4b6322ca6..6c5ae34bc 100644
--- a/src/main/java/games/strategy/debug/ClientLogger.java
+++ b/src/main/java/games/strategy/debug/ClientLogger.java
@@ -7,6 +7,7 @@ import java.io.PrintStream;
 import java.util.concurrent.ExecutionException;
 
 import javax.annotation.Nullable;
+import javax.swing.SwingUtilities;
 
 import com.google.common.annotations.VisibleForTesting;
 
@@ -95,6 +96,6 @@ public final class ClientLogger {
       return;
     }
 
-    ErrorMessage.show(msg);
+    SwingUtilities.invokeLater(() -> ErrorMessage.show(msg));
   }
 }
```

![null-error-dialog](https://user-images.githubusercontent.com/4826349/35478765-6dde69bc-03b4-11e8-9acf-befb36b251a6.png)

The error message itself is `null` for the reason given in the original stack trace.  The root cause (`IllegalArgumentException`) is being wrapped in an `ExceptionInInitializerError` because the exception is being thrown in the class initializer for `ClientContext`.  And when the JVM throws the `ExceptionInInitializerError`, it doesn't set the detail message, so that `getMessage()` returns `null`.

Strange, because I thought `Throwable` delegated to the cause if its detail message was `null`, but after looking at the code, it apparently does not.

**Comment by ssoloff** [comment]
Switching from `Throwable#getMessage()` to `Throwable#toString()` in `ErrorHandler#handle()` at least provides a non-`null` message to display to the user:

![null-error-dialog-fixed](https://user-images.githubusercontent.com/4826349/35478829-dde0e28e-03b5-11e8-9ce7-af8d7188c529.png)

Then **Show Details** will reveal the root cause in the console's stack trace.
