### ISSUE TITLE
Problem with 1 round of battle and only air units left in an abandoned territory

### ISSUE THREAD

**Issue by WCSumpton** [triplea-game/triplea#2959]
Window 10 Operating System:

1.9.0.0.7922 Engine version:

Under Siege: America (Invasion USA - Mod) Map name and version:

Land Battle Rounds are set to 1.  Player-A attacks and defeats all defending units except air units from AI_Player-B so territory is considered contested. During AI_Player-B's next CM no new units are moved into the contested territory and air unit is not moved out.  So on AI_Player-B's combat phase you get Should not be possible to have a normal battle in: XXXXX and have abandoned or only bombing there too.

### Do you have the exact error text? Please copy/paste if so
```
triplea.engine.version.bin:1.9
Loading map: invasion_usa, from: C:\Users\WC_Su\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\WC_Su\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA\assets]
Loading map: invasion_usa, from: C:\Users\WC_Su\triplea\downloadedMaps\invasion_usa-master.zip
Loading resources from the following paths: [C:\Users\WC_Su\triplea\downloadedMaps\invasion_usa-master.zip, C:\Program Files\TripleA\assets]
java.lang.IllegalStateException: Should not be possible to have a normal battle in: Houston and have abandoned or only bombing there too.
	at games.strategy.triplea.delegate.BattleDelegate.setupTerritoriesAbandonedToTheEnemy(BattleDelegate.java:600)
	at games.strategy.triplea.delegate.BattleDelegate.doInitialize(BattleDelegate.java:176)
	at games.strategy.triplea.delegate.BattleDelegate.start(BattleDelegate.java:76)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:502)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:397)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:266)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$157(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by General-Dru-Zod** [comment]
#2549 is related to contested territory buggy behaviors as well.

**Comment by WCSumpton** [comment]
Setting property: "Abandoned Territories May Be Taken Over Immediately" to false allows the air unit to battle in the territory.  Ownership of the territory does until end of turn.

**Comment by ron-murhammer** [comment]
@WCSumpton Can we close this issue then?

**Comment by WCSumpton** [comment]
I believe this can be closed


________________________________
