### ISSUE TITLE
Could not set property:turns subject:RulesAttachment  - Stack trace on WWII Europe

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#2973]
Set game to all AI's and let them play on "World War II Europe 1940 Original". I got a stack trace after some time... 
```
Feb 10, 2018 3:02:54 AM games.strategy.engine.message.unifiedmessenger.UnifiedMessenger invoke
WARNING: Could not set property:turns subject:RulesAttachment attached to:PlayerID named:French with name:conditionAttachment_French_1_Liberation new value:1-+
java.lang.IllegalStateException: Could not set property:turns subject:RulesAttachment attached to:PlayerID named:French with name:conditionAttachment_French_1_Liberation new value:1-+
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:19)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:34)
	at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.framework.ServerGame$1.gameDataChanged(ServerGame.java:98)
	at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:155)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:48)
	at com.sun.proxy.$Proxy10.gameDataChanged(Unknown Source)
	at games.strategy.engine.framework.ServerGame.addChange(ServerGame.java:605)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:86)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:81)
	at games.strategy.triplea.delegate.GameDelegateBridge.addChange(GameDelegateBridge.java:68)
	at games.strategy.triplea.attachments.TriggerAttachment.triggerPlayerPropertyChange(TriggerAttachment.java:1711)
	at games.strategy.triplea.attachments.TriggerAttachment.fireTriggers(TriggerAttachment.java:222)
	at games.strategy.triplea.attachments.TriggerAttachment.collectAndFireTriggers(TriggerAttachment.java:168)
	at games.strategy.triplea.delegate.BaseTripleADelegate.triggerWhenTriggerAttachments(BaseTripleADelegate.java:90)
	at games.strategy.triplea.delegate.BaseTripleADelegate.end(BaseTripleADelegate.java:59)
	at games.strategy.triplea.delegate.BattleDelegate.end(BattleDelegate.java:117)
	at games.strategy.engine.framework.ServerGame.endStep(ServerGame.java:454)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:418)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:266)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:58)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:17)
	... 29 more

Failed while setting up logging
java.lang.IllegalStateException: Could not set property:turns subject:RulesAttachment attached to:PlayerID named:French with name:conditionAttachment_French_1_Liberation new value:1-+
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:19)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:34)
	at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at games.strategy.engine.framework.GameRunner$1.dispatchEvent(GameRunner.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:17)
	... 21 more
```

**Comment by ron-murhammer** [comment]
I'm pretty sure this issue is due to some type changes on m_turns in #2582

**Comment by ron-murhammer** [comment]
Almost positive the problem is that the getter/setter types don't match up:
public void setTurns(final HashMap<Integer, Integer> value)
public Map<Integer, Integer> getTurns()
