### ISSUE TITLE
Beta Swing UI unusable

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#3005]
Not that important, but I noticed that the beta Swing UI is currently throwing an exception whenever I try to use it:
```
Error: java.lang.IllegalArgumentException: URI is not absolute
java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
	at org.triplea.client.launch.screens.LaunchScreenWindow.parseGameData(LaunchScreenWindow.java:102)
	at org.triplea.client.launch.screens.LaunchScreenWindow.draw(LaunchScreenWindow.java:91)
	at org.triplea.client.launch.screens.InitialLaunchScreen.lambda$1(InitialLaunchScreen.java:44)
	at swinglib.JButtonBuilder.lambda$0(JButtonBuilder.java:51)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at games.strategy.util.UrlStreams.openStream(UrlStreams.java:39)
	at games.strategy.engine.framework.ui.GameChooserEntry.<init>(GameChooserEntry.java:39)
	at games.strategy.engine.framework.ui.GameChooserEntry.newGameChooserEntry(GameChooserEntry.java:30)
	at org.triplea.client.launch.screens.LaunchScreenWindow.parseGameData(LaunchScreenWindow.java:97)
	... 40 more
```
The passed URI string is empty, that's what causing the exception

**Comment by DanVanAtta** [comment]
Download a few maps, it's a work around. @RoiEXLab

**Comment by RoiEXLab** [comment]
@DanVanAtta I have downloaded all maps there are, it's still not working :(

**Comment by DanVanAtta** [comment]
Oh, I'm not seeing that on main screen when clicking 'launch new UI'. Just to be sure, that is the button that throws this error?

**Comment by RoiEXLab** [comment]
@DanVanAtta This is the exception that occurs when selecting a game option like "play singleplayer" or "Play By Forum"
