### ISSUE TITLE
Can't Host with new .9191

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3120]
### My Operating System:
Win 10
### Engine version:
1.9.0.0.9191
### Map name and version:
N/A
### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try to host
### Do you have the exact error text? Please copy/paste if so
Error.java.lang.NullPointerException
```
TripleA engine version 1.9.0.0.9191
Feb 23, 2018 11:28:58 AM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:prastle port:3300 ip:24.53.234.237 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Error: java.lang.NullPointerException
java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at java.util.Properties.setProperty(Unknown Source)
	at java.lang.System.setProperty(Unknown Source)
	at games.strategy.engine.framework.startup.ui.InGameLobbyWatcher.newInGameLobbyWatcher(InGameLobbyWatcher.java:101)
	at games.strategy.engine.framework.startup.ui.ServerSetupPanel.createLobbyWatcher(ServerSetupPanel.java:75)
	at games.strategy.engine.framework.startup.ui.ServerSetupPanel.<init>(ServerSetupPanel.java:65)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showServer(SetupPanelModel.java:55)
	at games.strategy.engine.framework.GameRunner.lambda$showMainFrame$3(GameRunner.java:285)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

### Instead of this error, what should have happened?
Host should open
### Any additional information that may help:
Can host fine with 1.9.0.0.8941

**Comment by ssoloff** [comment]
I think this is a regression from #3096.  The system property is now being cleared before being read.  Sometimes the IDE thinks it's smarter than it is. :smile:

I'll fix shortly.

**Comment by prastle** [comment]
Curro also lost host ability but regained when reverting to .8941
All good you guys are getting there 😄

**Comment by RoiEXLab** [comment]
@ssoloff Yeah, just noticed this as well. Already assumed it was this PR, but I wanted to verify it first ^^

**Comment by ssoloff** [comment]
@prastle Sorry about this; we let it slip by during the review.  It should be fixed in build 9199 or later.

**Comment by prastle** [comment]
Relax all good
Bots running fine on 8941

**Comment by DanVanAtta** [comment]
> @prastle Sorry about this; we let it slip by during the review. It should be fixed in build 9199 or later.

I disagree a bit, review is not so humans can act like compilers and testers. We let this slip in testing, and that was my responsibility for the PR that caused this. As a project, we've restored some brittle code to "fix" this problem, I'm surprised there was no code coverage on this; seems the NPE should have been detected automatically.

**Comment by prastle** [comment]
To be BLUNT you guys have done amazing jobs getting us this far.  Thus we have testers.  Hopefully we all catch the probs.  Relax @DanVanAtta  😄   its getting there bro

**Comment by ssoloff** [comment]
> I'm surprised there was no code coverage on this

We have 20% unit test coverage.  It should not be surprising. :smile:

**Comment by DanVanAtta** [comment]
> Relax @DanVanAtta 😄 its getting there bro

All good, my tone is 100 times more worried than I actually am; a small problem with written communication; I feel very matter of fact about this rather than more upset or anything else.

It is a bit troubling though that we got into trouble with brittle code, and to fix it we put the brittle code back how it was instead of doing something more that would have prevented a repeat of this problem. At the same time I understand the motivation for doing that to not invest too much effort beyond a break-fix. Part of my thinking though is that if a problem *can* happen again, we have not really fixed it
