### ISSUE TITLE
Java Issue?

### ISSUE THREAD

**Issue by justwantotoplaytriplea2** [triplea-game/triplea#3224]
I am having a problem where the game starts but have no way to use the buttons and have this error.

```
triplea.engine.version.bin:1.9
Failed while attempting to check for a new VersionWarning!! 1 system checks failed. Some game features may not be available or may not work correctly.
Can connect to github.com (check network connection): false
Can create temporary files (check disk usage, file permissions): true

javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
at java.net.URL.openStream(URL.java:1045)
at games.strategy.engine.framework.EngineVersionProperties.getProperties(EngineVersionProperties.java:77)
at games.strategy.engine.framework.EngineVersionProperties.<init>(EngineVersionProperties.java:35)
at games.strategy.engine.framework.EngineVersionProperties.lambda$contactServerForEngineVersionProperties$107(EngineVersionProperties.java:53)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
at sun.security.validator.Validator.getInstance(Validator.java:179)
at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
... 11 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
... 23 more

java.lang.RuntimeException: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at games.strategy.engine.framework.systemcheck.LocalSystemChecker.lambda$defaultNetworkCheck$275(LocalSystemChecker.java:39)
at games.strategy.engine.framework.systemcheck.SystemCheck.<init>(SystemCheck.java:24)
at games.strategy.engine.framework.systemcheck.LocalSystemChecker.defaultNetworkCheck(LocalSystemChecker.java:31)
at games.strategy.engine.framework.systemcheck.LocalSystemChecker.<init>(LocalSystemChecker.java:22)
at games.strategy.engine.framework.GameRunner.checkLocalSystem(GameRunner.java:299)
at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1959)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1916)
at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1899)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
at games.strategy.engine.framework.systemcheck.LocalSystemChecker.lambda$defaultNetworkCheck$275(LocalSystemChecker.java:37)
... 5 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
at sun.security.validator.Validator.getInstance(Validator.java:179)
at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
... 10 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
... 22 more
```

I read in another location to clear and go to properties.

```
SYSTEM PROPERTIES
awt.toolkit sun.awt.X11.XToolkit
exe4j.moduleName /home/jason/TripleA/TripleA
file.encoding UTF-8
file.encoding.pkg sun.io
file.separator /
i4j.vpt true
i4jv 0
install4j.appDir /home/jason/TripleA/
install4j.exeDir /home/jason/TripleA/
install4j.jvmDir /usr/lib/jvm/java-1.8.0-openjdk-amd64
install4j.launcherId 33
install4j.swt false
java.awt.graphicsenv sun.awt.X11GraphicsEnvironment
java.awt.printerjob sun.print.PSPrinterJob
java.class.path /home/jason/TripleA/.install4j/i4jruntime.jar:/home/jason/TripleA/bin/triplea.jar
java.class.version 52.0
java.endorsed.dirs /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
java.ext.dirs /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
java.home /usr/lib/jvm/java-8-openjdk-amd64/jre
java.io.tmpdir /tmp
java.library.path /usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
java.runtime.name OpenJDK Runtime Environment
java.runtime.version 1.8.0_151-8u151-b12-0ubuntu0.17.10.2-b12
java.specification.name Java Platform API Specification
java.specification.vendor Oracle Corporation
java.specification.version 1.8
java.vendor Oracle Corporation
java.vendor.url http://java.oracle.com/
java.vendor.url.bug http://bugreport.sun.com/bugreport/
java.version 1.8.0_151
java.vm.info mixed mode
java.vm.name OpenJDK 64-Bit Server VM
java.vm.specification.name Java Virtual Machine Specification
java.vm.specification.vendor Oracle Corporation
java.vm.specification.version 1.8
java.vm.vendor Oracle Corporation
java.vm.version 25.151-b12
javax.accessibility.assistive_technologies org.GNOME.Accessibility.AtkWrapper
line.separator

os.arch amd64
os.name Linux
os.version 4.13.0-36-generic
path.separator :
sun.arch.data.model 64
sun.awt.enableExtraMouseButtons true
sun.awt.exception.handler games.strategy.triplea.ui.ErrorHandler
sun.boot.class.path /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
sun.boot.library.path /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
sun.cpu.endian little
sun.cpu.isalist
sun.desktop gnome
sun.font.fontmanager sun.awt.X11FontManager
sun.io.unicode.encoding UnicodeLittle
sun.java.command com.install4j.runtime.launcher.UnixLauncher launch ab9dd710 /home/jason/TripleA/error.log+ games.strategy.engine.framework.GameRunner
sun.java.launcher SUN_STANDARD
sun.jnu.encoding UTF-8
sun.management.compiler HotSpot 64-Bit Tiered Compilers
sun.os.patch.level unknown
triplea.engine.version.bin 1.9
user.country US
user.dir /home/jason/TripleA
user.home /home/jason
user.language en
user.name jason
user.timezone America/Chicago
```

But I do not have an answer to solving it. What do I need to do?
Just want to play.

**Comment by ssoloff** [comment]
@justwantotoplaytriplea2 I've never seen this error before when running TripleA, but a quick search seems to indicate there may be a problem with your Java installation's truststore (possibly corrupt or missing).  This [SO question](https://stackoverflow.com/questions/6784463/error-trustanchors-parameter-must-be-non-empty) has a ton of answers that cover various platforms.  It looks like you're using Ubuntu, so [this answer](https://stackoverflow.com/a/30699960/3900879) may be the best place to start.

Some other straightforward things you can try:

##### Update JRE to latest

You're running the standard OpenJDK JRE that is packaged with your Linux distro, but the build (151) is a bit out of date.  You could try using your package manager to update to the latest OpenJDK JRE and see if that updates and/or fixes the truststore.

##### Use Oracle JRE

It's kind of recommended to run TripleA using an Oracle JRE.  So if updating your OpenJDK JRE doesn't work, you can install the latest Java 8 JRE from Oracle and run TripleA using that instead.  That will guarantee you get a fresh _cacerts_ file.

Assuming you use the Oracle portable install (_.tar.gz_ file), you can force TripleA to use it by doing the following:

* Open a terminal and change to the folder where you installed TripleA.
* Run the command:
  `$ PATH=<path/to/oracle/jre>/bin:$PATH ./TripleA`
  where you replace `<path/to/oracle/jre>` with the absolute path to the folder where you exploded the _.tar.gz_ file.

You can confirm TripleA is using the JRE you think it is by displaying the system properties in the console as you did above, and look for the `java.home` variable.  The path after that variable should point to your Oracle JRE instead of the OpenJDK JRE.

**Comment by RoiEXLab** [comment]
Closing due to inactivity.
We will reopen this issue if you respond and your issues still persists
