### ISSUE TITLE
Purchasing Bug

### ISSUE THREAD

**Issue by erik542** [triplea-game/triplea#3308]
### Engine version
1.9.0.0.9687

### My Operating System
Windows 10 with Creators Update

### Map name
Happened on at least NWO, NML, WAW, so it's likely all of them.

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Join a game hosted by a bot, open up a map, get to purchase phase, attempt to increment up any unit.

### Do you have the exact error text? Please copy/paste if so
TripleA engine version 1.9.0.0.9687
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Warning: serialization de-serialization error, m_name in DefaultNamed.java is null.
Loading map: new_world_order, from: C:\Users\Erik\triplea\downloadedMaps\new_world_order-master.zip
Loading resources from the following paths: [C:\Users\Erik\triplea\downloadedMaps\new_world_order-master.zip, C:\Program Files\TripleA\assets]
Loading map: new_world_order, from: C:\Users\Erik\triplea\downloadedMaps\new_world_order-master.zip
Loading resources from the following paths: [C:\Users\Erik\triplea\downloadedMaps\new_world_order-master.zip, C:\Program Files\TripleA\assets]
Error: Max cant be less than min. Current Min: 0, Current Max: 2147483647, New Max: -2147483648
java.lang.IllegalArgumentException: Max cant be less than min. Current Min: 0, Current Max: 2147483647, New Max: -2147483648
	at games.strategy.ui.IntTextField.setMax(IntTextField.java:85)
	at games.strategy.ui.ScrollableTextField.setMax(ScrollableTextField.java:130)
	at games.strategy.triplea.ui.ProductionPanel$Rule.setMax(ProductionPanel.java:366)
	at games.strategy.triplea.ui.ProductionPanel.calculateLimits(ProductionPanel.java:216)
	at games.strategy.triplea.ui.ProductionPanel$Rule$1.changedValue(ProductionPanel.java:375)
	at games.strategy.ui.ScrollableTextField.notifyListeners(ScrollableTextField.java:190)
	at games.strategy.ui.ScrollableTextField.lambda$new$0(ScrollableTextField.java:112)
	at games.strategy.ui.IntTextField.notifyListeners(IntTextField.java:179)
	at games.strategy.ui.IntTextField.access$300(IntTextField.java:18)
	at games.strategy.ui.IntTextField$IntegerDocument.insertString(IntTextField.java:142)
	at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.setText(Unknown Source)
	at games.strategy.ui.IntTextField.setValue(IntTextField.java:79)
	at games.strategy.ui.ScrollableTextField$1.actionPerformed(ScrollableTextField.java:53)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:104)
	at games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:41)
	at games.strategy.triplea.ui.PurchasePanel$1.actionPerformed(PurchasePanel.java:119)
	at games.strategy.triplea.ui.PurchasePanel.lambda$waitForPurchase$2(PurchasePanel.java:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Error: Max cant be less than min. Current Min: 0, Current Max: 2147483647, New Max: -2147483648
java.lang.IllegalArgumentException: Max cant be less than min. Current Min: 0, Current Max: 2147483647, New Max: -2147483648
	at games.strategy.ui.IntTextField.setMax(IntTextField.java:85)
	at games.strategy.ui.ScrollableTextField.setMax(ScrollableTextField.java:130)
	at games.strategy.triplea.ui.ProductionPanel$Rule.setMax(ProductionPanel.java:366)
	at games.strategy.triplea.ui.ProductionPanel.calculateLimits(ProductionPanel.java:216)
	at games.strategy.triplea.ui.ProductionPanel$Rule$1.changedValue(ProductionPanel.java:375)
	at games.strategy.ui.ScrollableTextField.notifyListeners(ScrollableTextField.java:190)
	at games.strategy.ui.ScrollableTextField.lambda$new$0(ScrollableTextField.java:112)
	at games.strategy.ui.IntTextField.notifyListeners(IntTextField.java:179)
	at games.strategy.ui.IntTextField.access$300(IntTextField.java:18)
	at games.strategy.ui.IntTextField$IntegerDocument.insertString(IntTextField.java:142)
	at java.desktop/javax.swing.text.AbstractDocument.replace(Unknown Source)
	at java.desktop/javax.swing.text.JTextComponent.setText(Unknown Source)
	at games.strategy.ui.IntTextField.setValue(IntTextField.java:79)
	at games.strategy.ui.ScrollableTextField$1.actionPerformed(ScrollableTextField.java:53)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.desktop/java.awt.Dialog.show(Unknown Source)
	at java.desktop/java.awt.Component.show(Unknown Source)
	at java.desktop/java.awt.Component.setVisible(Unknown Source)
	at java.desktop/java.awt.Window.setVisible(Unknown Source)
	at java.desktop/java.awt.Dialog.setVisible(Unknown Source)
	at games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:104)
	at games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:41)
	at games.strategy.triplea.ui.PurchasePanel$1.actionPerformed(PurchasePanel.java:119)
	at games.strategy.triplea.ui.PurchasePanel.lambda$waitForPurchase$2(PurchasePanel.java:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

### Instead of this error, what should have happened?
I should have been able to change my purchase smoothly.

### Any additional information that may help
My Java: version 8 update 161.
This only occurs on games hosted by bots. It does not occur when I play locally or in games hosted by other people.
On the purchase screen, most, but not all, units are shown to cost 0.
Something that started happening at the side time, was that in a game hosted by someone else sometimes the TUV would show to be a very large negative number..

[bug.zip](https://github.com/triplea-game/triplea/files/1839660/bug.zip)

**Comment by ron-murhammer** [comment]
@erik542 Are you sure about your Java version? We've seen a few similar errors recently for users that are running Java 9 and we are working on a few fixes for Java 9.

**Comment by ron-murhammer** [comment]
@erik542 Can you try downloading and installing the latest pre-release TripleA version here: https://github.com/triplea-game/triplea/releases/tag/1.9.0.0.9866

**Comment by erik542** [comment]
That works.

**Comment by ron-murhammer** [comment]
I think its still pulling in Java 9 from your system somewhere but the latest pre-release fixed a few bugs we had with Java 9 so should be all good. If you have any other issues just let me know.
