### ISSUE TITLE
Bot logs:  java.lang.NullPointerException at DefaultNamed.java:33

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3369]
Looking at logs, ran across the following:

```
Apr 14 17:32:00 localhost run_bot[28113]: Apr 14, 2018 5:32:00 PM games.strategy.net.ServerMessenger socketUnqaurantined
Apr 14 17:32:00 localhost run_bot[28113]: INFO: Connection added to:akaroadman port:50970 ip:xx.xx.xxx.xxx
Apr 14 17:32:00 localhost run_bot[28113]: Apr 14, 2018 5:32:00 PM games.strategy.engine.chat.ChatController joinChat
Apr 14 17:32:00 localhost run_bot[28113]: INFO: Chatter:akaroadman port:50970 ip:96.59.217.232 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Apr 14 17:32:02 localhost run_bot[28113]: Failed to join game
Apr 14 17:32:02 localhost run_bot[28113]: java.lang.NullPointerException
Apr 14 17:32:02 localhost run_bot[28113]:         at games.strategy.engine.data.DefaultNamed.equals(DefaultNamed.java:33)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashMap.putVal(HashMap.java:635)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashMap.put(HashMap.java:612)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.util.HashSet.readObject(HashSet.java:342)
Apr 14 17:32:02 localhost run_bot[28113]:         at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
Apr 14 17:32:02 localhost run_bot[28113]:         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.lang.reflect.Method.invoke(Method.java:564)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
Apr 14 17:32:02 localhost run_bot[28113]:         at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2082)
```

### Engine version
9480

### My Operating System
Bot

### Map name
n/a

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
unknown

**Comment by prastle** [comment]
Which bot was this out of curiosity?

**Comment by DanVanAtta** [comment]
botserver60_GA_USA

**Comment by prastle** [comment]
yup that was one of them

**Comment by RoiEXLab** [comment]
Looking at the code this NullPointerException should not occur at all, because the `m_name` field is a constant and can't be initialized with null.
So the only way the field can be null is by deserializing and "invalid" object.
