### ISSUE TITLE
Can't connect to lobby with latest

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3373]
### Engine version
9687
10111

### My Operating System
Mac

### Map name
N/A

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try to join the lobby, after the login credentials window and click 'join', there is a delay then an error message.

### Do you have the exact error text? Please copy/paste if so
```
Error: Connection Lost
games.strategy.engine.message.ConnectionLostException: Connection Lost
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.messengerInvalid(UnifiedMessenger.java:86)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$new$0(UnifiedMessenger.java:69)
	at games.strategy.net.ClientMessenger.socketError(ClientMessenger.java:231)
	at games.strategy.net.nio.NioSocket.error(NioSocket.java:91)
	at games.strategy.net.nio.NioReader.loop(NioReader.java:127)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Invoker Stack
	at java.lang.Thread.getStackTrace(Thread.java:1559)
	at games.strategy.engine.message.MessengerException.fillInInvokerStackTrace(MessengerException.java:19)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:56)
	at com.sun.proxy.$Proxy0.isAdmin(Unknown Source)
	at games.strategy.engine.lobby.client.LobbyClient.isAdmin(LobbyClient.java:24)
	at games.strategy.triplea.ui.menubar.LobbyMenu.<init>(LobbyMenu.java:63)
	at games.strategy.engine.lobby.client.ui.LobbyFrame.<init>(LobbyFrame.java:58)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.connectToLobby(MetaSetupPanel.java:161)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.lambda$setupListeners$5(MetaSetupPanel.java:137)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Instead of this error, what should have happened?
Connect to lobby, lobby window should appear.

### Any additional information that may help
Might be more widespread than just Mac OS.

**Comment by DanVanAtta** [comment]
This also impacts 9687, it is a production problem.
Given the lobby is not available at all for an entire OS, perhaps more widespread. This is a P0.

**Comment by ron-murhammer** [comment]
@DanVanAtta Not sure I follow. We weren't having any issues with at least 9687 connecting to 9687 so this would most likely be something with the latest pre-release or something with the infra changes. I'm a little skeptical that all MacOS users can't connect to the lobby.

**Comment by DanVanAtta** [comment]
Looks like network is dead for that port not responding. 


```
$ telnet 45.79.144.153 3304
Trying 45.79.144.153...


telnet: connect to address 45.79.144.153: Operation timed out
telnet: Unable to connect to remote host
```

This should not be mac related, but maybe the network I'm on.. Could be impacting only new connections.

I am able to ssh to the machine though, so port 22 is listening

**Comment by DanVanAtta** [comment]
Can you connect to lobby @ron-murhammer ?

infra changes were only for bots, nothing touched server. Server maybe given the updates went into some sort of crash, but looking at those logs nothing stands out.

**Comment by ron-murhammer** [comment]
@DanVanAtta Yep, along with about 50 other users :)

**Comment by DanVanAtta** [comment]
okay, that knocks this down then at least. The fact it works for some and not all is still a problem. I cannot connect to that port for lobby.

**Comment by DanVanAtta** [comment]
Hmm, I see that i am connecting:
```
Apr 16 20:47:17 tripleawarclub run_lobby[3476]: INFO: Connection added to:LaFayette_ port:15766 ip:170.173.8.12
```
But no response locally on client, so seems packets are not making it back to my machine for whatever reason.

**Comment by DanVanAtta** [comment]
to clarify, 'connecting' means I see a message on lobby logs, but client is not getting anything, still freezes and then errors out with the same stack trace printed above.

**Comment by DanVanAtta** [comment]
Dropping out of a P1 as there is no confirmed widespread impact.

Trying to connect from a new network, I now have no issue. Seems there was something very special with that last wifi I was connected to where packets being sent back from a specific port were not making it.
