### ISSUE TITLE
Negative Coordinates Not Anymore Supported (1.9.0.0.10153)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#3386]
I see that you have disabled the possibility of loading negative coordinates, from the skin.
That can be argued one way or the other, I think, but fact is that you will get a few broken games.
For example, "Rome Total War"; you will get this:

Failed to start game
java.lang.IllegalStateException: No where to place units:RomanRepublicBox
	at games.strategy.triplea.ui.screen.TileManager.drawUnits(TileManager.java:337)
	at games.strategy.triplea.ui.screen.TileManager.drawTerritory(TileManager.java:275)
	at games.strategy.triplea.ui.screen.TileManager.resetTiles(TileManager.java:194)
	at games.strategy.triplea.ui.MapPanel.setGameData(MapPanel.java:428)
	at games.strategy.triplea.ui.MapPanel.<init>(MapPanel.java:109)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:268)
	at games.strategy.triplea.ui.TripleAFrame.lambda$create$0(TripleAFrame.java:229)
	at games.strategy.ui.SwingAction.lambda$invokeAndWaitResult$1(SwingAction.java:114)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Practically I assume all maps having negative coordinates will be unplayable.
I would keep supporting negative coordinates, but I'm not strong on it, not being a fan of cutting stuff myself.
Just a notice.

**Comment by ron-murhammer** [comment]
@Cernelius Guessing this was unintentional during some refactoring.

@RoiEXLab Any insight here as I think most likely some of your tile changes probably affected this?

**Comment by RoiEXLab** [comment]
@ron-murhammer This is unrelated to the Tile Refactoring, this error just happens to occur during the initialization of the map.
Nevertheless this issue is my fault, opened #3387

**Comment by ron-murhammer** [comment]
@Cernelius This should be fixed in the latest pre-release.

**Comment by Cernelius** [comment]
Since the wording in here:
https://github.com/triplea-game/triplea/pull/3387/commits/dc6d9d6800d8c99663b41be0a915397f2ae4e3c4
appears to refer to the polygons only, I want to point out that this regression applied to probably all loaded coordinates, or at least not only to the polygons. For example, you could not have negative coordinates anymore in the "territory_effects.txt", when I tested for this issue.

**Comment by RoiEXLab** [comment]
@Cernelius It's just the wording. This issue should be fixed for all kinds of points and point lists
