### ISSUE TITLE
History Wrong Thread Error

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3400]
**Version:** current master

**Steps:**
- All Hard AI except last player is human game of Feudal Japan, this error is thrown at the end of initial placements: 
[Wrong_Thread_Error.zip](https://github.com/triplea-game/triplea/files/1948005/Wrong_Thread_Error.zip)

**Error:**
```
Error: Wrong thread
java.lang.IllegalStateException: Wrong thread
	at games.strategy.engine.history.History.assertCorrectThread(History.java:39)
	at games.strategy.engine.history.History.getLastNode(History.java:63)
	at games.strategy.triplea.ui.history.HistoryPanel.goToEnd(HistoryPanel.java:360)
	at games.strategy.triplea.ui.TripleAFrame.showGame(TripleAFrame.java:1831)
	at games.strategy.triplea.ui.TripleAFrame.updateStep(TripleAFrame.java:1452)
	at games.strategy.triplea.ui.TripleAFrame.lambda$0(TripleAFrame.java:1401)
	at games.strategy.engine.framework.AbstractGame.notifyGameStepListeners(AbstractGame.java:89)
	at games.strategy.engine.framework.ServerGame.notifyGameStepChanged(ServerGame.java:532)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:492)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:395)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:263)
	at java.util.Optional.ifPresent(Optional.java:159)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:36)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Thread.java:748)
```

@RoiEXLab My guess is this has something to do with some of the loading changes you've done recently.

**Comment by RoiEXLab** [comment]
@ron-murhammer #3401
The UI code is too tied to the game logic code. The History class seems to hold the Data at the same time as being a swing UI model

**Comment by ron-murhammer** [comment]
@RoiEXLab Yeah, its definitely not a great design as the data portion and UI portion should really be separated.
