### ISSUE TITLE
AI Neutrals - Null Pointer Exception

### ISSUE THREAD

**Issue by General-Dru-Zod** [triplea-game/triplea#3404]
### Engine version
10042, 10211

### My Operating System
win10

### Map name
Bad-Ass 4-Nation FFA v.1.6.0.20

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Set british, germans, Japanese, russians to hardAI, and the rest to do-nothingAI. and launch game.

### Instead of this error, what should have happened?
It either gives error on game load with 10211, or plays 1 round and errors with 10042.

### Any additional information that may help

[BA.FFA_null.pointer.exception_04.26.2018.txt](https://github.com/triplea-game/triplea/files/1950052/BA.FFA_null.pointer.exception_04.26.2018.txt)

[BA.FFA_null.pointer.exception_10042.zip](https://github.com/triplea-game/triplea/files/1950054/BA.FFA_null.pointer.exception_10042.zip)

![ba_ffa_null pointer exception_10042_04 26 2018](https://user-images.githubusercontent.com/17499403/39290788-c459d51c-48fe-11e8-8444-c2f553b70074.PNG)

**Comment by RoiEXLab** [comment]
@ron-murhammer I believe this is related to #3389

**Comment by General-Dru-Zod** [comment]
@ron-murhammer 
I ran a few more tests, the error with 10042 is resolved if I set the Chinese to hardAI as well. However this does not help in 10211 error. 

Note they seemed to be caused by 2 different reasons, but with same end result or "nullpointer exception".

**Comment by General-Dru-Zod** [comment]
@ron-murhammer 
Some additional information for you. If I set british, germans, japanese, russians set to human, chinese set to hardAI, rest set to doesNothing AI (as a normal game would be played). I get the following error on Chinese placement. With 10042 is this setup is ok.

Error: java.lang.NullPointerException
java.lang.NullPointerException
	at games.strategy.triplea.ai.pro.util.ProUtils.isNeutralPlayer(ProUtils.java:240)
	at games.strategy.triplea.ai.pro.util.ProUtils.isNeutralLand(ProUtils.java:231)
	at games.strategy.triplea.ai.pro.util.ProTerritoryValueUtils.findLandValue(ProTerritoryValueUtils.java:240)
	at games.strategy.triplea.ai.pro.util.ProTerritoryValueUtils.findTerritoryValues(ProTerritoryValueUtils.java:64)
	at games.strategy.triplea.ai.pro.util.ProTerritoryValueUtils.findTerritoryValues(ProTerritoryValueUtils.java:48)
	at games.strategy.triplea.ai.pro.ProPurchaseAi.place(ProPurchaseAi.java:389)
	at games.strategy.triplea.ai.pro.ProAi.place(ProAi.java:253)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:477)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:515)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:404)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:263)
	at java.util.Optional.ifPresent(Unknown Source)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:36)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)

Here is a save game of this scenario.

[BA.FFA_null.pointer.exception_10211.zip](https://github.com/triplea-game/triplea/files/1950339/BA.FFA_null.pointer.exception_10211.zip)

**Comment by prastle** [comment]
Also possibly why Headless bots needed more memory?  Noob ?

**Comment by ron-murhammer** [comment]
@General-Dru-Zod Yeah, this a bug related to the neutral changes that I made. Should be resolved once #3405 is merged.

**Comment by hispublic** [comment]
I think this may similar and points to something in the new update?  Since updating to the new release, every map I've tried (except and after the long game) is giving an error.  Here is the latest.

TripleA engine version 1.9.0.0.10192
Loading map: ww2_phillipines, from: C:\Users\C\triplea\downloadedMaps\ww2_phillipines-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\ww2_phillipines-master.zip, D:\TripleA\assets]
Loading map: ww2_phillipines, from: C:\Users\C\triplea\downloadedMaps\ww2_phillipines-master.zip
Loading resources from the following paths: [C:\Users\C\triplea\downloadedMaps\ww2_phillipines-master.zip, D:\TripleA\assets]
Error: java.lang.NullPointerException
java.lang.NullPointerException
	at games.strategy.triplea.ai.pro.util.ProUtils.isNeutralPlayer(ProUtils.java:240)
	at games.strategy.triplea.ai.pro.util.ProUtils.isNeutralLand(ProUtils.java:231)
	at games.strategy.triplea.ai.pro.data.ProTerritoryManager.removeTerritoriesThatCantBeConquered(ProTerritoryManager.java:142)
	at games.strategy.triplea.ai.pro.data.ProTerritoryManager.removeTerritoriesThatCantBeConquered(ProTerritoryManager.java:105)
	at games.strategy.triplea.ai.pro.ProCombatMoveAi.doCombatMove(ProCombatMoveAi.java:85)
	at games.strategy.triplea.ai.pro.ProAi.purchase(ProAi.java:222)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:460)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:515)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:404)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:263)
	at java.util.Optional.ifPresent(Unknown Source)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:36)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)

**Comment by ron-murhammer** [comment]
@hispublic Yeah that should be fixed in the latest pre-release.

**Comment by General-Dru-Zod** [comment]
@ron-murhammer Tested 10216, It's fixed.
