### ISSUE TITLE
Newly added map, Alagaesia fails to start

### ISSUE THREAD

**Issue by alkexr** [triplea-game/triplea#3444]
Tried to download the map from the repository to replace the folder in which I developed it. (Moved the development folder away, it's existence shouldn't interfere.) It fails to start, and it also can't find the images that are supposed to show up in game notes.

### Engine version
1.9.0.9747

### My Operating System
Windows 10

### Map name
Alagaesia

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
Try to start game.

### Do you have the exact error text? Please copy/paste if so
`
Loading map: Alagaesia, from: C:\Users\alkexr\triplea\downloadedMaps\alagaesia-master.zip
Loading resources from the following paths: [C:\Users\alkexr\triplea\downloadedMaps\alagaesia-master.zip, D:\Programok\TripleA\triplea_1_9_0_0_9747\assets]
Failed to start game
java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip
	at games.strategy.triplea.ui.mapdata.MapData.<init>(MapData.java:146)
	at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:77)
	at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:232)
	at games.strategy.triplea.TripleA.lambda$startGame$0(TripleA.java:121)
	at games.strategy.ui.SwingAction.lambda$invokeAndWait$0(SwingAction.java:86)
	at games.strategy.ui.SwingAction.lambda$invokeAndWaitResult$1(SwingAction.java:114)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Loading map: Alagaesia, from: C:\Users\alkexr\triplea\downloadedMaps\alagaesia-master.zip
Loading resources from the following paths: [C:\Users\alkexr\triplea\downloadedMaps\alagaesia-master.zip, D:\Programok\TripleA\triplea_1_9_0_0_9747\assets]
Could not find: Alagaesia/doc/images/title.png
Could not find: Alagaesia/doc/images/human.png
Could not find: Alagaesia/doc/images/dwarf.png
Could not find: Alagaesia/doc/images/urgal.png
Could not find: Alagaesia/doc/images/kull.png
Could not find: Alagaesia/doc/images/elf.png
Could not find: Alagaesia/doc/images/cavalry.png
Could not find: Alagaesia/doc/images/feldunost_rider.png
Could not find: Alagaesia/doc/images/werecat.png
Could not find: Alagaesia/doc/images/laughing_dead.png
Could not find: Alagaesia/doc/images/mage.png
Could not find: Alagaesia/doc/images/elven_spellweaver.png
Could not find: Alagaesia/doc/images/shade.png
Could not find: Alagaesia/doc/images/razac.png
Could not find: Alagaesia/doc/images/dragon_rider.png
Could not find: Alagaesia/doc/images/ship.png
Could not find: Alagaesia/doc/images/wall.png
Could not find: Alagaesia/doc/images/city.png
`

### Instead of this error, what should have happened?
The game should have started, I suppose?

### Any additional information that may help
The game worked before I uploaded it, so the problem should be related to folder structure or something like that

**Comment by panther2** [comment]
@alkexr 

No, the folder structure is correct.

The problem is in the game.xml files.

In both xml files you have

`    <property name="mapName" value="Alagaesia" editable="false">`

The map name value must be identical to the folder name, and it does not allow capitals here.

So change it to 

`    <property name="mapName" value="alagaesia" editable="false">`

and it will load fine.

**Comment by alkexr** [comment]
Thanks, resolved now. Probably no one has downloaded it so far, so I think increasing version number in the triplea_maps.yaml is not necessary.
