### ISSUE TITLE
Civil War, unit movements not showing

### ISSUE THREAD

**Issue by wirkey** [triplea-game/triplea#3490]
### Engine version
1.9.0.0.8847

### My Operating System
Win10 Home

### Map name
Civil War: A House divided, Version 3.2.4 @bot101 and bot501

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
If you move units, those units don't move on the map, but the move is listed in the action tab.
[image](https://forums.triplea-game.org/assets/uploads/files/1530267489169-e19c096b-16ce-4bfc-ae40-4c102a913480-image-resized.png)

If you are the opposing player, you get an error message
[error](https://forums.triplea-game.org/assets/uploads/files/1530206909946-d9055f08-151d-490f-95a8-745dbfba847d-image-resized.png)

**Comment by ron-murhammer** [comment]
This looks like an engine compatibility issue. Can you try updating your engine to at least the latest stable. The issue appears to be related to all the fuel changes that I made recently.

**Comment by wirkey** [comment]
with 9687

TripleA engine version 1.9.0.0.8847
Loading map: , from: C:\Users\pilzf\triplea\downloadedMaps\
Loading resources from the following paths: [C:\Users\pilzf\triplea\downloadedMaps\, C:\Program Files\TripleA\assets]
Loading map: civil_war, from: C:\Users\pilzf\triplea\downloadedMaps\civil_war-master.zip
Loading resources from the following paths: [C:\Users\pilzf\triplea\downloadedMaps\civil_war-master.zip, C:\Program Files\TripleA\assets]
Loading map: civil_war, from: C:\Users\pilzf\triplea\downloadedMaps\civil_war-master.zip
Loading resources from the following paths: [C:\Users\pilzf\triplea\downloadedMaps\civil_war-master.zip, C:\Program Files\TripleA\assets]
Error: No method called:setChargedFlatFuelCost on:artillery owned by Confederate
java.lang.IllegalStateException: No method called:setChargedFlatFuelCost on:artillery owned by Confederate
	at games.strategy.util.PropertyUtil.getSetter(PropertyUtil.java:128)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:14)
	at games.strategy.engine.data.changefactory.ObjectPropertyChange.perform(ObjectPropertyChange.java:46)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Error: No method called:setChargedFlatFuelCost on:infantry owned by Confederate
java.lang.IllegalStateException: No method called:setChargedFlatFuelCost on:infantry owned by Confederate
	at games.strategy.util.PropertyUtil.getSetter(PropertyUtil.java:128)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:14)
	at games.strategy.engine.data.changefactory.ObjectPropertyChange.perform(ObjectPropertyChange.java:46)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Error: No method called:setChargedFlatFuelCost on:train owned by Confederate
java.lang.IllegalStateException: No method called:setChargedFlatFuelCost on:train owned by Confederate
	at games.strategy.util.PropertyUtil.getSetter(PropertyUtil.java:128)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:14)
	at games.strategy.engine.data.changefactory.ObjectPropertyChange.perform(ObjectPropertyChange.java:46)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Error: Not all units present in:Corinth Station.  Trying to remove:[infantry owned by Confederate] present:[]
java.lang.IllegalStateException: Not all units present in:Corinth Station.  Trying to remove:[infantry owned by Confederate] present:[]
	at games.strategy.engine.data.changefactory.RemoveUnits.perform(RemoveUnits.java:38)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Error: No method called:setChargedFlatFuelCost on:artillery owned by Confederate
java.lang.IllegalStateException: No method called:setChargedFlatFuelCost on:artillery owned by Confederate
	at games.strategy.util.PropertyUtil.getSetter(PropertyUtil.java:128)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:14)
	at games.strategy.engine.data.changefactory.ObjectPropertyChange.perform(ObjectPropertyChange.java:46)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Error: No method called:setChargedFlatFuelCost on:infantry owned by Confederate
java.lang.IllegalStateException: No method called:setChargedFlatFuelCost on:infantry owned by Confederate
	at games.strategy.util.PropertyUtil.getSetter(PropertyUtil.java:128)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:14)
	at games.strategy.engine.data.changefactory.ObjectPropertyChange.perform(ObjectPropertyChange.java:46)
	at games.strategy.engine.data.CompositeChange.perform(CompositeChange.java:49)
	at games.strategy.engine.data.GameData.performChange(GameData.java:517)
	at games.strategy.engine.history.History.changeAdded(History.java:162)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:155)
	at games.strategy.engine.framework.HistorySynchronizer$1.lambda$gameDataChanged$0(HistorySynchronizer.java:50)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by wirkey** [comment]
just tried it with 10440 and it works fine.
The loan notification error still shows, however

**Comment by Cernelius** [comment]
The 1.9.0.0.9687 is the current stable, so I guess some/all regular players are unable to play Civil War in automated hosts, currently.
