### ISSUE TITLE
Adding Units in Edit Mode Causes Concurrent Modification Exception (1.9.0.0.10538)

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3536]
@RoiEXLab I get this error when trying to add units to a territory in edit mode and it appears related to the tile changes:
```
Error: java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:91)
	at games.strategy.triplea.ui.screen.Tile.drawImage(Tile.java:76)
	at games.strategy.triplea.ui.MapPanel.lambda$drawTiles$6(MapPanel.java:578)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by RoiEXLab** [comment]
#3538
