### ISSUE TITLE
Tile Draw ConcurrentModificationException (1.9.0.0.10558)

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3557]
https://forums.triplea-game.org/topic/73/iron-war-official-thread/377

```
Error: java.util.ConcurrentModificationException
java.util.ConcurrentModificationException
at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
at java.util.TreeMap$ValueIterator.next(Unknown Source)
at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:90)
at games.strategy.triplea.ui.screen.Tile.drawImage(Tile.java:76)
at games.strategy.triplea.ui.MapPanel.lambda$drawTiles$6(MapPanel.java:578)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
java.util.ConcurrentModificationException
at java.util.TreeMap$PrivateEntryIterator.nextEntry(Unknown Source)
at java.util.TreeMap$ValueIterator.next(Unknown Source)
at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:90)
at games.strategy.triplea.ui.screen.Tile.drawImage(Tile.java:76)
at games.strategy.triplea.ui.MapPanel.lambda$drawTiles$6(MapPanel.java:578)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
```

**Comment by General-Dru-Zod** [comment]
Yes I just got this error too. In addition the map is not drawn completely/correctly.

![ww2 global_concurrentmodificationexception_error_07 17 2018](https://user-images.githubusercontent.com/17499403/42823027-8075439e-89aa-11e8-8e2e-3497f6672f7a.PNG)

**Comment by RoiEXLab** [comment]
#3567
