### ISSUE TITLE
Game of Thrones map has error starting in multiplayer

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#3573]
Game of Thrones map has error starting in multiplayer.

Unfortunately, I don't have the exact error message or exception handy. But whenever I tried to play this over the net with other human players (and most countries set to Hard AI), we would get an error starting up. I think it said something like "something went wrong".

Unfortunately, I've not been able to reproduce this myself locally - when starting multiple clients and connecting to localhost.

**Comment by Cernelius** [comment]
Playing Game of Thrones might not be a very good choice, as that map has all of a series of bugs, beside the fact that the rosters are of disputable quality, with several units not really worth buying and, sometimes, even absolutely inferior to other available choices.

The matter has been discussed several times in the old Sourceforge forum, and it is currently mostly tracked here (not sure if you want to consolidate this one there too):
https://github.com/triplea-game/triplea/issues/3160

**Comment by asvitkine** [comment]
That other issue seems to be talking about specifics of the map, territories, etc. This one is a different issue. I got an error log from the person I was playing with. The error appears to be this:

java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt, the error is that either we did not find the correct path to load. Check the resource loader to make sure the map zip or dir was added. Failing that, the path in this error message should be available relative to the map folder, or relative to the root of the map zip
at games.strategy.triplea.ui.mapdata.MapData.<init>(MapData.java:149)
at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:79)
at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
at games.strategy.triplea.ui.TripleAFrame.create(TripleAFrame.java:227)
at games.strategy.triplea.TripleA.startGame(TripleA.java:126)
at games.strategy.engine.framework.startup.mc.ClientModel.lambda$startGameInNewThread$8(ClientModel.java:353)
at java.lang.Thread.run(Unknown Source)

Interestingly, I don't get this error. I wonder why there's a difference. I was on Mac and the other player was on Windows.

**Comment by Cernelius** [comment]
Just in case you didn't already do this, first thing I would do is suggesting your mate to delete and redownload the map.

**Comment by Cernelius** [comment]
Off topic, if you are determined to play this map, I strongly suggest you take only countries in the west continent, leaving the east to AI. The east continent is so broken and bugged it's not really playable.

**Comment by DanVanAtta** [comment]
Closing due to lack of activity and lack of repro steps.

The error message "java.lang.IllegalStateException: Error in resource loading. Unable to load expected resource: polygons.txt" IIRC is an older one when a map is missing
