### ISSUE TITLE
Cannot join a network game

### ISSUE THREAD

**Issue by ssoloff** [triplea-game/triplea#3614]
### Engine version
1.9.0.0.10744

### My Operating System
Linux localhost.localdomain 4.17.3-200.fc28.x86_64 <span>#</span>1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
1. Using one client, host a network game.
1. Using a second client, joint the network game started in (1).

**Expected:** The second client should join the network game.

**Actual:** The second client opens the error console with the stack trace below.  The second client remains on the main menu.  To the first client, it appears the second client has joined (second client is still listed in the player list).

_Note:_ Using same engine version for both clients.

### Do you have the exact error text? Please copy/paste if so
```
TripleA engine version 1.9.0.0.10744
Jul 23, 2018 2:32:36 PM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:host port:3300 ip:172.17.0.1 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Jul 23, 2018 2:32:48 PM games.strategy.net.ServerMessenger socketUnqaurantined
INFO: Connection added to:client port:52520 ip:127.0.0.1
Jul 23, 2018 2:32:48 PM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:client port:52520 ip:127.0.0.1 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Loading map: , from: /home/ssoloff/triplea/downloadedMaps/
Loading resources from the following paths: [/home/ssoloff/triplea/downloadedMaps/, /home/ssoloff/Downloads/triplea-1.9.0.0.10744-all_platforms/assets]
Jul 23, 2018 2:32:49 PM games.strategy.net.nio.Encoder write
SEVERE: Error writing object:Message header. msg:Invocation results for method id:GUID:1dd81faf5b021474:5f3693f0:164c869d6ec:-8000:167 results:Return value: 'PlayerListingMessage:{Germans=host, British=host, Russians=host, Japanese=host, Americans=host}', exception: none to:client port:52520 ip:127.0.0.1 from:host port:3300 ip:172.17.0.1
java.io.NotSerializableException: com.google.common.collect.AbstractMapBasedMultimap$WrappedSet
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at java.util.LinkedHashMap.internalWriteEntries(LinkedHashMap.java:333)
	at java.util.HashMap.writeObject(HashMap.java:1363)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at games.strategy.engine.message.RemoteMethodCallResults.writeExternal(RemoteMethodCallResults.java:43)
	at games.strategy.engine.message.unifiedmessenger.InvocationResults.writeExternal(InvocationResults.java:39)
	at games.strategy.net.nio.Encoder.write(Encoder.java:79)
	at games.strategy.net.nio.Encoder.lambda$write$0(Encoder.java:38)
	at games.strategy.io.IoUtils.writeToMemory(IoUtils.java:77)
	at games.strategy.net.nio.Encoder.write(Encoder.java:38)
	at games.strategy.net.nio.NioSocket.send(NioSocket.java:68)
	at games.strategy.net.ServerMessenger.send(ServerMessenger.java:140)
	at games.strategy.engine.message.UnifiedMessengerHub.send(UnifiedMessengerHub.java:47)
	at games.strategy.engine.message.UnifiedMessengerHub.sendResultsToCaller(UnifiedMessengerHub.java:119)
	at games.strategy.engine.message.UnifiedMessengerHub.results(UnifiedMessengerHub.java:110)
	at games.strategy.engine.message.UnifiedMessengerHub.messageReceived(UnifiedMessengerHub.java:99)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.send(UnifiedMessenger.java:217)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$1(UnifiedMessenger.java:281)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### Any additional information that may help
From the stack trace, it appears the `Set` view returned from a Guava `Multimap` made its way into the serialized object graph.  Such a `Set` is not serializable.

**Comment by ssoloff** [comment]
Bisected first observation of failure to 1.9.0.0.10686 (#3592).  1.9.0.0.10673 works as expected.

**Comment by DanVanAtta** [comment]
I believe I found the problem, assigning to myself.

FWIW the current version of master works with the latest release, previous testing was focused on that variant
