### ISSUE TITLE
Bot Startup Regression

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#3629]
Seeing the following in logs, looks like latest prerelease will have trouble getting bots to start:

```
Jul 25 04:00:18 prerelease_staging run_bot.sh:  Key triplea.game.host.console is unknown
Jul 25 04:00:18 prerelease_staging run_bot.sh:  Jul 25, 2018 4:00:18 AM games.strategy.engine.framework.headlessGameServer.HeadlessGameServer usage
Jul 25 04:00:18 prerelease_staging run_bot.sh:  INFO:
Jul 25 04:00:18 prerelease_staging run_bot.sh:  Usage and Valid Arguments:
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.game=<FILE_NAME>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.server=true
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.port=<PORT>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.name=<PLAYER_NAME>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.host=<LOBBY_HOST>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.port=<LOBBY_PORT>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.game.comments=<LOBBY_GAME_COMMENTS>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.game.hostedBy=<LOBBY_GAME_HOSTED_BY>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.game.supportEmail=<youremail@emailprovider.com>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.game.supportPassword=<password for remote actions, such as remote stop game>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     triplea.lobby.game.reconnection=<seconds between refreshing lobby connection [min 21600]>
Jul 25 04:00:18 prerelease_staging run_bot.sh:     mapFolder=mapFolder
Jul 25 04:00:18 prerelease_staging run_bot.sh:     You must start the Name and HostedBy with "Bot".
Jul 25 04:00:18 prerelease_staging run_bot.sh:     Game Comments must have this string in it: "automated_host".
Jul 25 04:00:18 prerelease_staging run_bot.sh:     You must include a support email for your host, so that you can be alerted by lobby admins when your host has an error. (For example they may email you when your host is down and needs to be restarted.)
Jul 25 04:00:18 prerelease_staging run_bot.sh:     Support password is a remote access password that will allow lobby admins to remotely take the following actions: ban player, stop game, shutdown server. (Please email this password to one of the lobby moderators, or private message an admin on the TripleaWarClub.org website forum.)
```

I'm working in this area, assigning to myself to follow up.

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/infrastructure/pull/99 is one problem, using deprecated CLI args that were removed.

I'm seeing additional problems  launching headless instances, looks like there is more to fix.

```
Exception in thread "Initialize Headless Server Setup Model" java.lang.NullPointerException
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.setGameTypePanel(SetupPanelModel.java:92)
	at games.strategy.engine.framework.headlessGameServer.HeadlessServerSetupPanelModel.showSelectType(HeadlessServerSetupPanelModel.java:23)
	at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.lambda$new$1(HeadlessGameServer.java:95)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by DanVanAtta** [comment]
This is not a problem in an earlier rev: 01f827da63a8953efa85b434b46ac58ff8032eb1

Debugging through that, we have no listeners attached to the panel, so looks like we are just missing a NPE check.

**Comment by RoiEXLab** [comment]
@DanVanAtta has this been fixed so far?

**Comment by DanVanAtta** [comment]
There were a few fixes for this, it looks fixed, but I'm unable to login to prerelease lobby to confirm :|

Confirmation is blocked until we can do that to really verify the bot is running well and can launch a game. #3648

**Comment by DanVanAtta** [comment]
Bot is running again.

Let's chalk one up for deployment automation to catch this on a prerelease level. Ideally though we'd be able to bring detection of this problem closer to dev and test for it.
