### ISSUE TITLE
What should the new scripts be for Headless Bot Hosting?

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#3683]
### Engine version

10937
### My Operating System
Win 10
### Map name
N/A
### Do you have the exact error text? Please copy/paste if so
G:\10937\TripleA>SET PORT=3363

G:\10937\TripleA>SET BOT_NUMBER=25

G:\10937\TripleA>SET LOBBY_HOST=45.79.144.53

G:\10937\TripleA>SET LOBBY_PORT=3304

G:\10937\TripleA>java -Xmx900m -Xss4m -Djava.awt.headless=true -classpath bin/triplea-1.9.0.0.10937-all.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer -Ptriplea.game.host.console=false -Ptriplea.game= -Ptriplea.server=true -Ptriplea.port=3363 -Ptriplea.lobby.host=45.79.144.53 -Ptriplea.lobby.port=3304 -Ptriplea.name=Bot25_Pras2 -Ptriplea.lobby.game.hostedBy=Bot25_Pras2 -Ptriplea.lobby.game.supportEmail=prastle5@hotmail.com -Ptriplea.lobby.game.comments="automated_host" -Ptriplea.lobby.game.reconnection=172800
Aug 02, 2018 12:41:50 PM games.strategy.engine.framework.headlessGameServer.HeadlessGameServer handleHeadlessGameServerArgs
WARNING: Invalid 'mapFolder' param, map folder must exist: ''
Aug 02, 2018 12:41:50 PM games.strategy.engine.framework.headlessGameServer.HeadlessGameServer usage
INFO:
Usage and Valid Arguments:
   triplea.game=<FILE_NAME>
   triplea.server=true
   triplea.port=<PORT>
   triplea.name=<PLAYER_NAME>
   triplea.lobby.host=<LOBBY_HOST>
   triplea.lobby.port=<LOBBY_PORT>
   triplea.lobby.game.comments=<LOBBY_GAME_COMMENTS>
   triplea.lobby.game.hostedBy=<LOBBY_GAME_HOSTED_BY>
   triplea.lobby.game.supportEmail=<youremail@emailprovider.com>
   triplea.lobby.game.supportPassword=<password for remote actions, such as remote stop game>
   triplea.lobby.game.reconnection=<seconds between refreshing lobby connection [min 21600]>
   mapFolder=mapFolder
   You must start the Name and HostedBy with "Bot".
   Game Comments must have this string in it: "automated_host".
   You must include a support email for your host, so that you can be alerted by lobby admins when your host has an error. (For example they may email you when your host is down and needs to be restarted.)
   Support password is a remote access password that will allow lobby admins to remotely take the following actions: ban player, stop game, shutdown server. (Please email this password to one of the lobby moderators, or private message an admin on the TripleaWarClub.org website forum.)

G:\10937\TripleA>pause
Press any key to continue . . .
Press any key to continue . . .
### Instead of this error, what should have happened?
Bot should have connected.
### Any additional information that may help
This script works fine using engine 10182.

G:\10182\TripleA>SET PORT=3363

G:\10182\TripleA>SET BOT_NUMBER=25

G:\10182\TripleA>SET LOBBY_HOST=45.79.144.53

G:\10182\TripleA>SET LOBBY_PORT=3304

G:\10182\TripleA>java -Xmx900m -Xss4m -Djava.awt.headless=true -classpath bin/triplea-1.9.0.0.10182-all.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer -Ptriplea.game.host.console=false -Ptriplea.game= -Ptriplea.server=true -Ptriplea.port=3363 -Ptriplea.lobby.host=45.79.144.53 -Ptriplea.lobby.port=3304 -Ptriplea.name=Bot25_Pras2 -Ptriplea.lobby.game.hostedBy=Bot25_Pras2 -Ptriplea.lobby.game.supportEmail=prastle5@hotmail.com -Ptriplea.lobby.game.comments="automated_host" -Ptriplea.lobby.game.reconnection=172800
triplea.game.host.console:false
triplea.lobby.host:45.79.144.53
triplea.lobby.game.hostedBy:Bot25_Pras2
triplea.game:
triplea.lobby.port:3304
triplea.lobby.game.supportEmail:prastle5@hotmail.com
triplea.name:Bot25_Pras2
triplea.server:true
triplea.lobby.game.reconnection:172800
triplea.lobby.game.comments:automated_host
triplea.port:3363
Exception while parsing: jar:file:/C:/Users/prast/triplea/downloadedMaps/iron_war-master.zip!/iron_war-master/map/games/iron_war.xml
games.strategy.engine.data.GameParseException: map name: 'jar:file:/C:/Users/prast/triplea/downloadedMaps/iron_war-master.zip!/iron_war-master/map/games/iron_war.xml', game name: 'Iron War', Missing property definition for option 'costResources' in attachment 'userActionAttachment_1_Balkan_receive_financial_support'
        at games.strategy.engine.data.GameParser.newGameParseException(GameParser.java:102)
        at games.strategy.engine.data.GameParser.newGameParseException(GameParser.java:96)
        at games.strategy.engine.data.GameParser.lambda$setValues$13(GameParser.java:1250)
        at java.util.Optional.orElseThrow(Unknown Source)
        at games.strategy.engine.data.GameParser.setValues(GameParser.java:1250)
        at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1206)
        at games.strategy.engine.data.GameParser.parseMapDetails(GameParser.java:194)
        at games.strategy.engine.data.GameParser.parse(GameParser.java:91)
        at games.strategy.engine.data.GameParser.parse(GameParser.java:85)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.addToAvailableGames(AvailableGames.java:115)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.populateFromZip(AvailableGames.java:91)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.lambda$newGameRepository$0(AvailableGames.java:60)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Use of twoIfBySea delegates is discouraged and will be removed in a future version of TripleA.
Exception while parsing: jar:file:/C:/Users/prast/triplea/downloadedMaps/iron_war_europe-master.zip!/iron_war_europe-master/map/games/iron_war_europe.xml
games.strategy.engine.data.GameParseException: map name: 'jar:file:/C:/Users/prast/triplea/downloadedMaps/iron_war_europe-master.zip!/iron_war_europe-master/map/games/iron_war_europe.xml', game name: 'Iron War: Europe', Missing property definition for option 'costResources' in attachment 'userActionAttachment_1_Slovakia_receive_financial_support'
        at games.strategy.engine.data.GameParser.newGameParseException(GameParser.java:102)
        at games.strategy.engine.data.GameParser.newGameParseException(GameParser.java:96)
        at games.strategy.engine.data.GameParser.lambda$setValues$13(GameParser.java:1250)
        at java.util.Optional.orElseThrow(Unknown Source)
        at games.strategy.engine.data.GameParser.setValues(GameParser.java:1250)
        at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1206)
        at games.strategy.engine.data.GameParser.parseMapDetails(GameParser.java:194)
        at games.strategy.engine.data.GameParser.parse(GameParser.java:91)
        at games.strategy.engine.data.GameParser.parse(GameParser.java:85)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.addToAvailableGames(AvailableGames.java:115)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.populateFromZip(AvailableGames.java:91)
        at games.strategy.engine.framework.headlessGameServer.AvailableGames.lambda$newGameRepository$0(AvailableGames.java:60)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Headless Start
Aug 02, 2018 1:44:36 PM games.strategy.engine.framework.headlessGameServer.HeadlessGameServer <init>
INFO: Game Server initialized
Aug 02, 2018 1:44:37 PM games.strategy.engine.chat.ChatController joinChat
INFO: Chatter:Bot25_Pras2 port:3363 ip:24.53.234.237 is joining chat:games.strategy.engine.framework.ui.ServerStartup.CHAT_NAME
Aug 02, 2018 1:44:37 PM games.strategy.engine.message.unifiedmessenger.UnifiedMessenger invoke
WARNING: null
java.lang.NullPointerException
        at games.strategy.engine.chat.Chat$1.speakerAdded(Chat.java:295)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
        at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:152)
        at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:48)
        at com.sun.proxy.$Proxy2.speakerAdded(Unknown Source)
        at games.strategy.engine.chat.ChatController.joinChat(ChatController.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:157)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
        at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:126)
        at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:105)
        at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
        at com.sun.proxy.$Proxy1.joinChat(Unknown Source)
        at games.strategy.engine.chat.Chat.<init>(Chat.java:83)
        at games.strategy.engine.chat.HeadlessChat.<init>(HeadlessChat.java:33)
        at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:280)
        at games.strategy.engine.framework.startup.mc.ServerModel.lambda$createServerMessenger$1(ServerModel.java:250)
        at java.util.Optional.map(Unknown Source)
        at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:250)
        at games.strategy.engine.framework.headlessGameServer.HeadlessServerSetupPanelModel.showSelectType(HeadlessServerSetupPanelModel.java:24)
        at games.strategy.engine.framework.headlessGameServer.HeadlessGameServer.lambda$new$1(HeadlessGameServer.java:95)
        at java.lang.Thread.run(Unknown Source)

host:45.79.144.53 port:3304
Waiting for users to connect.

**Comment by prastle** [comment]
It also works in 10484

**Comment by prastle** [comment]
After a bit of legwork it has been narrowed down to above post @ssoloff @RoiEXLab @ron-murhammer

**Comment by ssoloff** [comment]
@prastle Due to recent changes (#3609 and #3632), you need to remove `-Ptriplea.game.host.console=false` and add `-PmapFolder=C:/Users/prast/triplea/downloadedMaps`.

Using your command line from above, please try the following with the latest prerelease (I used 10949):

> java -Xmx900m -Xss4m -Djava.awt.headless=true -classpath bin/triplea-1.9.0.0.10949-all.jar games.strategy.engine.framework.headlessGameServer.HeadlessGameServer -Ptriplea.game= -Ptriplea.server=true -Ptriplea.port=3363 -Ptriplea.lobby.host=45.79.144.53 -Ptriplea.lobby.port=3304 -Ptriplea.name=Bot25_Pras2 -Ptriplea.lobby.game.hostedBy=Bot25_Pras2 -Ptriplea.lobby.game.supportEmail=prastle5@hotmail.com -Ptriplea.lobby.game.comments="automated_host" -Ptriplea.lobby.game.reconnection=172800 -PmapFolder=C:/Users/prast/triplea/downloadedMaps

**Comment by prastle** [comment]
Ty it worked perfectly @ssoloft

**Comment by DanVanAtta** [comment]
@prastle this will always be kept working: https://github.com/triplea-game/infrastructure/blob/master/roles/bot/files/run_bot.sh, so you can refer there for latest parameters when needed.

**Comment by prastle** [comment]
The problem is all other bot hosters don't know this.  Including Cernel.  Thus why the forum needs to be kept updated.  Just My Humble opinion.  Hopefully someone can help Scousemart. @DanVanAtta either way feel free to close this

**Comment by Cernelius** [comment]
So, it worked for me rewording what @ssoloff posted, but I crash when I try to start a game in it.

This is my current folder:

D:/Programs/TripleA/downloadedMaps

thus:

-PmapFolder=D:/Programs/TripleA/downloadedMaps

This is the error I got:

TripleA engine version 1.9.0.0.10908
Failed to start Game
games.strategy.engine.framework.startup.launcher.MapNotFoundException
	at games.strategy.triplea.ResourceLoader.getMapResourceLoader(ResourceLoader.java:66)
	at games.strategy.triplea.ui.HeadedUiContext.internalSetMapDir(HeadedUiContext.java:69)
	at games.strategy.triplea.ui.AbstractUiContext.setDefaultMapDir(AbstractUiContext.java:104)
	at games.strategy.triplea.ui.TripleAFrame.create(TripleAFrame.java:225)
	at games.strategy.triplea.TripleA.startGame(TripleA.java:106)
	at games.strategy.engine.framework.startup.mc.ClientModel.lambda$startGameInNewThread$9(ClientModel.java:336)
	at java.lang.Thread.run(Unknown Source)

I believe this is the forum post for giving anyone the info (I guess it needs to be updated):

https://forums.triplea-game.org/topic/593/how-to-host-a-bot/2

Not interested myself, just reporting what happened since @prastle asked me to try this out: I don't actually plan to host bots, so whatever.

**Comment by prastle** [comment]
@DanVanAtta  Without being rude but in an attempt to be blunt …  I will explain the problem in a nutshell.  Old triplea it was easy to host new triplea is not.  Old triplea any peeps that could host could host bots with the scripts included in triplea no guesswork... they have been removed from the download.  The included hosting script has been removed and now sends them to the tutorial instead of asking them if they wish to attempt to host… (as if that has anything to do with hosting).  Meanwhile the few bot hosters and people we did have that hosted live have basically quit because it is a PIA to work through the setup.  Thus since you often complain about the cost and slimming. This is what you need to fix first.  Since in the old days we almost all could host and we didn't have any bots.  Just my final two cents.  I hope this inspires the dev team to work on this.  Sincerely Pras

**Comment by DanVanAtta** [comment]
@prastle how about we keep a location that is not forum post up to date with the information? Then the forum post should then just link there and we'll keep the link up to date?

**Comment by DanVanAtta** [comment]
Like, it's pretty easy to give someone a chunk of text and say copy/paste this into a file, it needs modifications anyways, so that will help guide a person through that. It then saves on the complexity of including a file for download.

**Comment by DanVanAtta** [comment]
Heh, just noticed a catch-22 that *would* prevent bot startup on the latest prerelease. 

We need: https://github.com/triplea-game/triplea/pull/3693 merged and 'mapFolder' renamed to 'triplea.map.folder'

**Comment by prastle** [comment]
@DanVanAtta  the normal user clicks host and receives your tutorial map
lets tie it to that

**Comment by DanVanAtta** [comment]
@prastle this looks like an old/resolved issue,
