### ISSUE TITLE
ConcurrentModificationException While Playing Civil War (1.9.0.0.11131)

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#3847]
games.strategy.engine.message.unifiedmessenger.UnifiedMessenger invoke
WARNING: null
java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(Unknown Source)
	at games.strategy.engine.data.GameData.notifyGameDataChanged(GameData.java:280)
	at games.strategy.engine.data.GameData.performChange(GameData.java:484)
	at games.strategy.engine.framework.ServerGame$1.gameDataChanged(ServerGame.java:99)
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:151)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:134)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:120)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:146)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:48)
	at com.sun.proxy.$Proxy12.gameDataChanged(Unknown Source)
	at games.strategy.engine.framework.ServerGame.addChange(ServerGame.java:622)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:86)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:81)
	at games.strategy.triplea.attachments.TriggerAttachment.removeUnits(TriggerAttachment.java:1314)
	at games.strategy.triplea.attachments.TriggerAttachment.triggerUnitRemoval(TriggerAttachment.java:2151)
	at games.strategy.triplea.attachments.TriggerAttachment.fireTriggers(TriggerAttachment.java:246)
	at games.strategy.triplea.attachments.TriggerAttachment.collectAndFireTriggers(TriggerAttachment.java:173)
	at games.strategy.triplea.delegate.BaseTripleADelegate.triggerWhenTriggerAttachments(BaseTripleADelegate.java:82)
	at games.strategy.triplea.delegate.BaseTripleADelegate.start(BaseTripleADelegate.java:35)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:520)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:418)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:287)
	at java.util.Optional.ifPresent(Unknown Source)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:41)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)

**Comment by ssoloff** [comment]
`GameData#dataChangeListeners` is a `CopyOnWriteArrayList`, and so should be immune to `ConcurrentModificationException`s:

https://github.com/triplea-game/triplea/blob/3763fb14ddaff037d75476f1e855271ece5e9dd1/game-core/src/main/java/games/strategy/engine/data/GameData.java#L83

However, it looks like this field is initialized with an `ArrayList` upon deserialization:

https://github.com/triplea-game/triplea/blob/3763fb14ddaff037d75476f1e855271ece5e9dd1/game-core/src/main/java/games/strategy/engine/data/GameData.java#L333-L336

Looks like the change to `ArrayList` in `postDeserialize()` was made in 11996448c, but I missed reverting it in 57309ff61.
