### ISSUE TITLE
String Parsing Error When Posting PBF Turn 1.9.0.0.11945

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#4020]
If I load save with current stable (1.9.0.0.9687) then I can successfully post. Here is the save: https://forums.triplea-game.org/topic/990/battle-for-arda-2-0-6-alkexr-evil-vs-redrum-good/59

At a quick glance this probably was introduced in #3975

**Error**
```
games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(Unknown Source)
	at games.strategy.triplea.ui.history.HistoryLog.parsePlayerNameFromDiceRollMessage(HistoryLog.java:408)
	at games.strategy.triplea.ui.history.HistoryLog.printRemainingTurn(HistoryLog.java:239)
	at games.strategy.triplea.ui.history.HistoryLog.printFullTurn(HistoryLog.java:130)
	at games.strategy.engine.pbem.ForumPosterComponent.updateHistoryLog(ForumPosterComponent.java:136)
	at games.strategy.engine.pbem.ForumPosterComponent.post(ForumPosterComponent.java:74)
	at games.strategy.engine.pbem.ForumPosterComponent.lambda$new$6(ForumPosterComponent.java:61)
	at games.strategy.ui.SwingAction$1.actionPerformed(SwingAction.java:65)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by ron-murhammer** [comment]
It appears that " roll " in the string may not exist and should just return the entire string rather than try to split on it:  https://github.com/triplea-game/triplea/blob/master/game-core/src/main/java/games/strategy/triplea/ui/history/HistoryLog.java#L408

Probably just want something like
`return message.contains(" roll ") ? message.substring(0, message.indexOf(" roll ")) : message;`

**Comment by ssoloff** [comment]
@ron-murhammer Thanks for fixing.  It looks like it's a message similar to `siege fire in Hornburg :` that's tripping it up.

I guess the bigger question is should the code go down a different path in this case?  For example, the code's already switching on tech rolls so it doesn't hit this branch.  (Is a "siege fire" some kind of territory effect?)  There's some statistics that are being updated on this branch (the `hitDifferentialMap`).  If the player name can't be parsed, is that going to skew the results?

**Comment by ron-murhammer** [comment]
@ssoloff This is really only used to add some expected vs actual hit information to PBF/PBEM posting. The siege fire is actually AA type attacks which end up just getting categorized separately. You can see the result of this logic in this post: https://forums.triplea-game.org/topic/990/battle-for-arda-2-0-6-alkexr-evil-vs-redrum-good/59. Its not perfect and probably could be better.

Regular roll: `Lorien roll dice for 1 ent and 1 huorn in South Fangorn, round 2 : 2/1 hits, 1.42 expected hits`

AA roll: `flank fire in East Vales of Anduin : 0/1 hits, 0.75 expected hits`

Turn hit summary:
```
Saruman : -0.33
Lorien : 0.25
Orcs : -1.00
flank fire in East Vales of Anduin : : -1.75
```

**Comment by ssoloff** [comment]
@ron-murhammer Yeah, I saw that, and it was the double colon in the AA-type stats that made me think this branch was not supposed to handle this type of `DiceRoll`.  But I guess the only real problem is simply how it's formatted.  Thanks for clarifying.

**Comment by ron-murhammer** [comment]
Yeah, the "AA type" rolls weren't really considered for this parsing and stats as most maps have just basic AA guns on defense against air so don't really matter much. But some newer maps use "AA type" rolls extensively to simulate targeted attacks.

**Comment by ssoloff** [comment]
@ron-murhammer Out of curiosity, what would be the ideal key in the hit differential map for AA-type attacks?  Is having both the AA type (`flank` in this case) and territory desirable, or would just the AA type be sufficient since (at least in this case) an ancestor node in the history already contains the territory name?

That is, would `flank fire : -1.75` be sufficient or does it open up the possibility of aliasing if AA-type attacks can come from territories other than the one in which the battle is being fought?

**Comment by ssoloff** [comment]
Closed by #4021.

**Comment by ron-murhammer** [comment]
@ssoloff I believe just like regular rolls that the AA rolls would always have a parent node that already specifies the territory (so the territory name is completely unnecessary but I'm not 100% sure). Ideally the key for them would be `player + AA type`, this would essentially combine all AA rolls of the same type together across battles just like regular rolls are.

So let's say I had 2 battles were there were regular and AA rolls so something like this:
```
        Battle in East Vales of Anduin
            Lorien attack with 6 elven_wardens, 4 galadhrim_longbowmen and 1 huorn
            Orcs defend with 1 troll, 1 warg_rider and 3 warg_scouts; DolGuldur defend with 1 bat
                flank fire in East Vales of Anduin : 0/1 hits, 0.75 expected hits
                formation fire in East Vales of Anduin : 1/1 hits, 0.75 expected hits
                Lorien roll dice for 6 elven_wardens, 4 galadhrim_longbowmen and 1 huorn in East Vales of Anduin, round 2 : 3/1 hits, 3.17 expected hits
        Battle in West Vales of Anduin
            Lorien attack with 6 elven_wardens, 4 galadhrim_longbowmen and 1 huorn
            Orcs defend with 1 troll, 1 warg_rider and 3 warg_scouts; DolGuldur defend with 1 bat
                flank fire in East Vales of Anduin : 0/1 hits, 0.75 expected hits
                Lorien roll dice for 6 elven_wardens, 4 galadhrim_longbowmen and 1 huorn in East Vales of Anduin, round 2 : 3/1 hits, 3.17 expected hits
```

Then I'd have the end report show this for orcs:
```
Orcs regular: -0.34
Orcs flank: -1.50
Orcs formation: 0.25
```

**Comment by ssoloff** [comment]
@ron-murhammer Thanks, that makes sense.  I'll add this on my back burner list because the current `HistoryLog` code is now confusing given the name I picked for the `parsePlayerNameFromDiceRollMessage()` method. :smile:
