### ISSUE TITLE
Pre-release installs with error.log

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#4186]
### Engine version
1.9.0.0.12430

### My Operating System
Windows 7 64 bit

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

After installing there was a file error.log within the installation directory.

### Do you have the exact error text? Please copy/paste if so

```
In action "Remove Windows Protocol Handler [Delete a key or value in the Windows registry]" (screen "Uninstallation"), property "Condition expression":
java.lang.NullPointerException
	at com.install4j.script.I4jScript_Internal_30.eval(I4jScript_Internal_30.java:1)
	at com.install4j.script.I4jScript_Internal_30.evaluate(I4jScript_Internal_30.java:*25)
	at com.install4j.runtime.installer.helper.Script.evaluate(Script.java:33)
	at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:201)
	at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:195)
	at com.install4j.runtime.installer.ContextImpl.runBooleanScript(ContextImpl.java:57)
	at com.install4j.runtime.installer.ContextImpl.runBooleanScript(ContextImpl.java:234)
	at com.install4j.runtime.installer.controller.Controller.executeAction(Controller.java:369)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Controller.java:343)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Controller.java:204)
	at com.install4j.runtime.installer.controller.Controller.start(Controller.java:103)
	at com.install4j.runtime.installer.Uninstaller.runInProcess(Uninstaller.java:36)
	at com.install4j.runtime.installer.Uninstaller.main(Uninstaller.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:81)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

```

During installation nothing "visible" occurred. Apart from this issue, the prerelease seems to run fine.

**Comment by RoiEXLab** [comment]
Looks like something went wrong when trying to setup the url handler that allows users to download maps via the website.
I'll have a look into this
