### ISSUE TITLE
MARTI give errors using latest Java 8 updates

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#4594]
First noted on https://www.axisandallies.org/forums/topic/32820/

### Engine version
1.9.0.0.13066
Java 8 Update 191

Marti gives this error:
````
Test
Contacting  dice.tripleawarclub.org
An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit https://forums.triplea-game.org/  for extra help
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
	at games.strategy.engine.random.PropertiesDiceRoller.postRequest(PropertiesDiceRoller.java:147)
	at games.strategy.engine.random.PbemDiceRoller$HttpDiceRollerDialog.rollInSeperateThread(PbemDiceRoller.java:222)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 22 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	... 28 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Jan 17 16:05:28 CET 2019
	at sun.security.x509.CertificateValidity.valid(Unknown Source)
	at sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
	at sun.security.provider.certpath.BasicChecker.check(Unknown Source)
	... 33 more
````

Update to Java 8 update 201 gives this error:
```
Test
Contacting  dice.tripleawarclub.org
An error has occured!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit https://forums.triplea-game.org/  for extra help
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118)
	at games.strategy.engine.random.PropertiesDiceRoller.postRequest(PropertiesDiceRoller.java:147)
	at games.strategy.engine.random.PbemDiceRoller$HttpDiceRollerDialog.rollInSeperateThread(PbemDiceRoller.java:222)
	at java.lang.Thread.run(Unknown Source)
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.validator.PKIXValidator.doValidate(Unknown Source)
	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
	at sun.security.validator.Validator.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
	... 22 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(Unknown Source)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(Unknown Source)
	at java.security.cert.CertPathValidator.validate(Unknown Source)
	... 28 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Thu Jan 17 16:05:28 CET 2019
	at sun.security.x509.CertificateValidity.valid(Unknown Source)
	at sun.security.x509.X509CertImpl.checkValidity(Unknown Source)
	at sun.security.provider.certpath.BasicChecker.verifyValidity(Unknown Source)
	at sun.security.provider.certpath.BasicChecker.check(Unknown Source)
	... 33 more
```

**Comment by ssoloff** [comment]
Looks like our TLS certificate expired today.

**Comment by panther2** [comment]
@ssoloff 
How (fast) can this be updated?

**Comment by ssoloff** [comment]
> How (fast) can this be updated?

I believe it's simply a matter of running the Let's Encrypt Certbot command to renew the certificate (but I'm not positive because I've never done it).  Unfortunately, the machine on which my SSH keys are stored is indisposed, so I can't login to `tripleawarclub.org` right now.

/cc: @RoiEXLab

**Comment by panther2** [comment]
@ssoloff 
Running it with the latest 1.10 prerelease runs just fine.
It sitll occurs with 1.9.0.0.13066, unfortunately.

**Comment by RoiEXLab** [comment]
Ohh I think the cert is only renewing for the triplea-game domain then
I'll have a look in 10 minutes

**Comment by RoiEXLab** [comment]
Ok, works again.
The certificate was correctly renewed, but nginx wasn't reloaded afterwards. Adding the hook now

**Comment by panther2** [comment]
@RoiEXLab @ssoloff 

Great news. Thank you!

**Comment by RoiEXLab** [comment]
@panther2 Thanks for forwarding the issue to us ^^
Always @ us on "time-critical" issues.
Although I check github a couple of times daily I read almost all emails just when I get them on my phone (as long as I'm not sleeping or doing something important IRL)

**Comment by RoiEXLab** [comment]
Ahh I know where the problem comes from. The folder has changed where certbot searches for post hooks, but the script hasn't moved.
Because the triplea-game domain certificate uses the nginx plugin (which didn't exist back when I initially setup certificates for this server) to set everything up the config was correctly reloaded there.
I wonder if I should just migrate to the nginx instead of webroot procedure.

**Comment by RoiEXLab** [comment]
I decided to keep everything as-is for now. I simply moved the post hook script to the correct folder so we don't run into the same problem in march instead of potentially breaking something with no real benefit.

**Comment by ssoloff** [comment]
> Running it with the latest 1.10 prerelease works just fine.

If it wasn't clear from what @RoiEXLab wrote above, I just wanted to note that the reason MARTI continued to work in 1.10 was that the URLs for MARTI were changed in #4373 from the `dice.tripleawarclub.org` domain (whose certificate expired today) to the `dice.marti.triplea-game.org` domain (whose certificate doesn't expire until Feb. 20).
