### ISSUE TITLE
Download Length Notifications Failures (1.10.13838)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#4595]
Downloading all maps in the repository almost at once, I'm getting a lot of "failed to get download length".

For example:
failed to get download length for 'https://github.com/triplea-maps/1914-cow-empires/archive/master.zip'

Show Details:
```
failed to get download length for 'https://github.com/triplea-maps/1914-cow-empires/archive/master.zip'
java.io.IOException: unexpected status code (429)
	at games.strategy.engine.framework.map.download.DownloadLengthReader.getDownloadLengthFromHost(DownloadLengthReader.java:76)
	at games.strategy.engine.framework.map.download.DownloadLengthReader.getDownloadLengthFromHost(DownloadLengthReader.java:63)
	at games.strategy.engine.framework.map.download.DownloadLengthReader.lambda$getDownloadLengthFromCache$0(DownloadLengthReader.java:53)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadLengthReader.getDownloadLengthFromCache(DownloadLengthReader.java:53)
	at games.strategy.engine.framework.map.download.DownloadLengthReader.getDownloadLength(DownloadLengthReader.java:46)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.newLabelText(DownloadMapsWindow.java:484)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$updateMapUrlAndSizeLabel$8(DownloadMapsWindow.java:469)
	at java.lang.Thread.run(Unknown Source)
```

Just a bunch of stuff to click through. Not a big deal for me, but I can see casual users not understanding what's the problem and being annoyed and worried if something is going wrong with the downloads.

**Comment by ssoloff** [comment]
@Cernelius FYI, the error code you're getting (429) means that you're making too many requests to GitHub in a short period of time.  GitHub basically keeps track of your IP address, and, if it sees you're making more than X requests per minute, it will deny your requests in the event you happen to be a Bad Guy trying to perform a denial-of-service attack.

In a nutshell, the root cause here is

> Downloading all maps in the repository almost at once

I'm not sure if that scenario is common enough for us to specifically handle the 429 case and display a custom message such as, "Hey, you're trying to download too many maps at once.  Slow down!" :smile:

**Comment by Cernelius** [comment]
If feasible, I suggest the 429 message being never given to the users (just tracked in the log, but not given popping up).

No idea really how many people would just go downloading all available maps after having installed the program.

**Comment by DanVanAtta** [comment]
I would recommend for the software to rate-limit on behalf of the user. We attempt to do that a bit already by capping parallel download counts, but that seems to be an incomplete solution.

Since we allow users to download-all maps, the software should not error out when a user tries that.  I wouldn't be surprised if a number of users do try to download at least all maps from a single category.

**Comment by DanVanAtta** [comment]
Haven't been able to reproduce this problem. Seems maybe we've improved the code or it's very difficult to hit. If we can get a repro case or a new example, it'll give us a lead to track down. Closing this for now in favor of waiting of new examples.
