### ISSUE TITLE
UnknownHostException - when localhost is not in /etc/hosts

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#464]
Error message can be improved. Operative part is: 
```Caused by: java.net.UnknownHostException: dan-desk: unknown error```
If the local host name is not in `/etc/hosts`, then this error is thrown when hosting a game:

```
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at games.strategy.net.ServerMessenger.<init>(ServerMessenger.java:72)
	at games.strategy.engine.framework.startup.mc.ServerModel.createServerMessenger(ServerModel.java:233)
	at games.strategy.engine.framework.startup.mc.SetupPanelModel.showServer(SetupPanelModel.java:46)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel$3.actionPerformed(MetaSetupPanel.java:147)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:124)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalStateException: java.net.UnknownHostException: dan-desk: dan-desk: unknown error
	at games.strategy.net.Node.<clinit>(Node.java:25)
	... 42 more
Caused by: java.net.UnknownHostException: dan-desk: dan-desk: unknown error
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
	at games.strategy.net.Node.<clinit>(Node.java:23)
	... 42 more
Caused by: java.net.UnknownHostException: dan-desk: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	... 43 more
```

**Comment by DanVanAtta** [comment]
Either this is an unhandled code path bug, or when in /etc/hosts is in this state it's really impossible to determine the local IP. I would suspect it's the first rather than the later. Worst case we can at the very least  improve the error message.

**Comment by DanVanAtta** [comment]
A bit esoteric, probably not worth fixing for some time.
