### ISSUE TITLE
FileNotFoundException: game_engine.properties

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#480]
Tester reported issue with 1.8.0.10.988: http://tripleadev.1671093.n2.nabble.com/Next-release-1-8-0-11-testers-wanted-td7590912i20.html

I installed the triplea_windows-x64_1.8.0.10.988.exe on my Windows 7.64 SP1. Java is Version 8, Update 73, 64bit. 

After launching TripleA I get this: 

java.lang.ExceptionInInitializerError 
        at games.strategy.engine.framework.GameRunner2.<clinit>(GameRunner2.java:85) 
        at games.strategy.engine.framework.GameRunner.main(GameRunner.java:54) 
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
        at java.lang.reflect.Method.invoke(Unknown Source) 
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:62) 
        at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:101) 
        at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:16) 
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: game_engine.properties (Das System kann die angegebene Datei nicht finden) 
        at com.google.common.base.Throwables.propagate(Throwables.java:160) 
        at games.strategy.engine.config.GameEnginePropertyFileReader.readProperty(GameEnginePropertyFileReader.java:43) 
        at games.strategy.engine.framework.mapDownload.MapListingSource.<init>(MapListingSource.java:21) 
        at games.strategy.engine.ClientContext.<init>(ClientContext.java:50) 
        at games.strategy.engine.ClientContext.<clinit>(ClientContext.java:36) 
        ... 9 more 
Caused by: java.io.FileNotFoundException: game_engine.properties (Das System kann die angegebene Datei nicht finden) 
        at java.io.FileInputStream.open0(Native Method) 
        at java.io.FileInputStream.open(Unknown Source) 
        at java.io.FileInputStream.<init>(Unknown Source) 
        at games.strategy.engine.config.GameEnginePropertyFileReader.readProperty(GameEnginePropertyFileReader.java:33) 
        ... 12 more

**Comment by DanVanAtta** [comment]
Fix in version 1.8.0.10.999  with PR#481
