### ISSUE TITLE
Exception during AI's turn.

### ISSUE THREAD

**Issue by MelvinWM** [triplea-game/triplea#4817]
### Engine version

1.10.dev
Commit: 5603af128ee8f066c700882325a01c80332b79b3

### My Operating System

Linux

### Map name

Lord of the Rings: Middle Earth

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)

Reproducing:
- Select game "Lord of the Rings: Middle Earth".
- Select local game.
- Set all players to "Hard AI", set one of the players except for Saruman to human.
- Start game.
- Exception will occur during Saruman's turn.

### Do you have the exact error text? Please copy/paste if so

		SEVERE: Cannot determine combat or not: sarumanPlace
		java.lang.IllegalStateException: Cannot determine combat or not: sarumanPlace
				    at games.strategy.triplea.delegate.GameStepPropertiesHelper.isCombatMove(GameStepPropertiesHelper.java:112)
				    at games.strategy.triplea.delegate.MoveValidator.checkCanalStepAndOwnership(MoveValidator.java:1307)
				    at games.strategy.triplea.delegate.MoveValidator.canPassThroughCanal(MoveValidator.java:1294)
				    at games.strategy.triplea.delegate.MoveValidator.validateCanal(MoveValidator.java:250)
				    at games.strategy.triplea.delegate.MoveValidator.validateCanal(MoveValidator.java:232)
				    at games.strategy.triplea.ai.pro.data.ProTerritoryManager.findNavalMoveOptions(ProTerritoryManager.java:591)
				    at games.strategy.triplea.ai.pro.data.ProTerritoryManager.findAirMoveOptions(ProTerritoryManager.java:741)
				    at games.strategy.triplea.ai.pro.data.ProTerritoryManager.findAttackOptions(ProTerritoryManager.java:395)
				    at games.strategy.triplea.ai.pro.data.ProTerritoryManager.findEnemyAttackOptions(ProTerritoryManager.java:456)
				    at games.strategy.triplea.ai.pro.data.ProTerritoryManager.populateEnemyAttackOptions(ProTerritoryManager.java:97)
				    at games.strategy.triplea.ai.pro.ProPurchaseAi.purchase(ProPurchaseAi.java:259)
				    at games.strategy.triplea.ai.pro.ProAi.purchase(ProAi.java:237)
				    at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:455)
				    at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:533)
				    at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:423)
				    at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:286)
				    at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:47)
				    at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:28)
				    at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:18)
				    at java.base/java.lang.Thread.run(Thread.java:844)

**Comment by ron-murhammer** [comment]
Good catch. I didn't happen to do any AI testing after the updates in #4816. And this error pretty much occurs on any map that sets at least 1 player to Fast/Hard AI. It should be resolved with #4819.
