### ISSUE TITLE
Game Over Exception

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5027]
### Engine version
1.10.15353

### Map name
Experienced with Napoleonic Empires

### Can you describe how to trigger the error? (eg: what sequence of actions will recreate it?)
While testing the solution to https://github.com/triplea-game/triplea/issues/5022 I noticed this:
Load the map. Start a local game. Exit the game.
![gameover](https://user-images.githubusercontent.com/20812775/63410212-0df2dc80-c3f3-11e9-9c78-a2ba3204e868.png)

### Do you have the exact error text? Please copy/paste if so

```
Aug. 21, 2019 9:01:31 VORM. org.triplea.game.client.HeadedGameRunner lambda$main$0
SCHWERWIEGEND: Game Over
games.strategy.engine.GameOverException: Game Over
	at games.strategy.engine.player.DefaultPlayerBridge.getRemoteDelegate(DefaultPlayerBridge.java:58)
	at games.strategy.triplea.TripleAPlayer.canUnitsFight(TripleAPlayer.java:385)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:339)
	at games.strategy.triplea.TripleAPlayer.start(TripleAPlayer.java:142)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:580)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:450)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:307)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:56)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:29)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ron-murhammer** [comment]
I noticed this as well.
