### ISSUE TITLE
Press Ctrl+Z while in full screen mode causes an error

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5121]
**Describe the bug**

Press ctrl+z once, and then a second or subsequent times and get an error:

```
Aug 29, 2019 10:20:32 AM org.triplea.game.client.HeadedGameRunner lambda$main$0
SEVERE: proportional location must be between 0.0 and 1.0.
java.lang.IllegalArgumentException: proportional location must be between 0.0 and 1.0.
	at java.desktop/javax.swing.JSplitPane.setDividerLocation(JSplitPane.java:759)
	at games.strategy.triplea.ui.TripleAFrame.lambda$get$10(TripleAFrame.java:730)
	at org.triplea.swing.SwingComponents.lambda$addKeyBinding$4(SwingComponents.java:459)
	at org.triplea.swing.SwingAction$2.actionPerformed(SwingAction.java:84)
```
**Expected behavior**
No error, should toggle between "full screen" mode and non-full-screen.

**Additional context**
Release blocker if this is new since the last release.

**Comment by DanVanAtta** [comment]
Duplicate of: https://github.com/triplea-game/triplea/issues/5847

The newer bug report has more details on it, deferring the newer issue.
