### ISSUE TITLE
capture illegal unit bug

### ISSUE THREAD

**Issue by doctored** [triplea-game/triplea#523]
i noticed this in no mans land when Arabia captures an AA gun which it cannot produce and therefore can't find the graphic for from what the bug console looks like to my non programmer eyes:

`triplea.engine.version.bin:1.8.0.9
Exception in thread "Map panel background drawer" java.lang.IllegalStateException: Cant load: aaGun  looking in: units/Arabia/aaGun.png
	at games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:146)
	at games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:137)
	at games.strategy.triplea.image.UnitImageFactory.getBaseImage(UnitImageFactory.java:152)
	at games.strategy.triplea.image.UnitImageFactory.getImage(UnitImageFactory.java:117)
	at games.strategy.triplea.ui.screen.UnitsDrawer.draw(UnitsDrawer.java:77)
	at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:122)
	at games.strategy.triplea.ui.screen.Tile.getImage(Tile.java:78)
	at games.strategy.triplea.ui.BackgroundDrawer.run(MapPanel.java:986)
	at java.lang.Thread.run(Thread.java:695)
java.lang.IllegalStateException: Cant load: aaGun  looking in: units/Arabia/aaGun.png
	at games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:146)
	at games.strategy.triplea.image.UnitImageFactory.getBaseImageURL(UnitImageFactory.java:137)
	at games.strategy.triplea.image.UnitImageFactory.getBaseImage(UnitImageFactory.java:152)
	at games.strategy.triplea.image.UnitImageFactory.getIcon(UnitImageFactory.java:187)
:
:

**Comment by ron-murhammer** [comment]
Yep that would be a missing unit image.

**Comment by DanVanAtta** [comment]
Related: http://tripleadev.1671093.n2.nabble.com/Unify-unit-images-between-countries-td7591578.

We should see what the game engine can do, this is not an isolated problem. Another facet to this is also a scaling problem where the requirements for unit images does not scale well. Specifically it is O(u*c) where `u` is the count of all distinct units and `c` is the number of countries. So WaW is ballpark around 80 or 100 unit images.. The color shading suggestion in the forum post, basically use neutral units and alter the color hue, would alleviate  the growth factor to O(u)

Next issue, the game engine should not crash all map rendering just because of one missing image. We need to handle it more gracefully. Again, forum post with no-image image is the most obvious solution.

**Comment by doctored** [comment]
well should there be a generic fallback for all units anyway? i mean before we supported custom team based units graphics wasn't it just generic unit graphic plus color?

**Comment by DanVanAtta** [comment]
Moving the action item for generic nation colors here: https://github.com/triplea-game/triplea/issues/925

@doctored , not quite sure I understand exactly what is being asked. Does #925 cover everything?

**Comment by doctored** [comment]
yup looks god to me :)
