### ISSUE TITLE
NPE in Unit Scroller

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5233]
**Describe the bug**
- Running latest pre-release with an all AI game on revised, I got the following NPE which appears to have to do with a potential null player:
```
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.attachments.TechAttachment.get(TechAttachment.java:63)
	at games.strategy.triplea.delegate.TechTracker.hasRocket(TechTracker.java:117)
	at games.strategy.triplea.image.UnitImageFactory.getBaseImageName(UnitImageFactory.java:239)
	at games.strategy.triplea.image.UnitImageFactory.getImageDimensions(UnitImageFactory.java:304)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.createUnitStackImage(AvatarPanelFactory.java:79)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.buildPanel(AvatarPanelFactory.java:51)
	at games.strategy.triplea.ui.unit.scroller.UnitScroller.lambda$6(UnitScroller.java:167)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Seeing a most likely related error for missing unit images when running an all AI game on Dragon War:
```
SEVERE: No image for unit type: UnitType{name=Spearmen}, player: PlayerId named:Pirates
java.lang.RuntimeException: No image for unit type: UnitType{name=Spearmen}, player: PlayerId named:Pirates
	at games.strategy.triplea.image.UnitImageFactory.lambda$2(UnitImageFactory.java:309)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at games.strategy.triplea.image.UnitImageFactory.getImageDimensions(UnitImageFactory.java:307)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.createUnitStackImage(AvatarPanelFactory.java:79)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.buildPanel(AvatarPanelFactory.java:51)
	at games.strategy.triplea.ui.unit.scroller.UnitScroller.lambda$6(UnitScroller.java:167)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by ron-murhammer** [comment]
So I just glanced at this. The issue is that the unit scroller logic assumes you always have a non-null player which isn't the case. An example is during an initialize step that has no player:
```
<step name="gameInitDelegate" delegate="initDelegate" maxRunCount="1"/>
```
Verses most steps have a player:
```
<step name="russianPurchase" delegate="purchase" player="Russians"/>
```

**Comment by ron-murhammer** [comment]
Closing based on merged PR.
