### ISSUE TITLE
Crash when ending turn in TWW after improved Aircraft Carrier Tech is enabled

### ISSUE THREAD

**Issue by GeoffBuchan** [triplea-game/triplea#534]
In the attached game the UK player rolled for improved aircraft tech at the start of this turn. When I end the turn, an error window appears, and the opening "Play" window listing each nation and whether it is played by Human or some AI. The program does not fully crash, but the game in progress is no longer running.

I've attached the file dtwcrash.tsvg.gz (gzip compressed version of the game state file).

gunzip the file, then load that game, and end the placement phase. The game should then exhibit the behavior I describe above.

I see these errors in the console:
triplea.engine.version.bin:1.8.0.9
Exception in thread "Triplea start thread" java.lang.IllegalStateException: No such Property Field: m_isTwoHit for Subject: UnitAttachment attached to:games.strategy.engine.data.UnitType called britishCarrier with name:unitAttatchment
    at games.strategy.util.PropertyUtil.getPropertyFieldObject(PropertyUtil.java:77)
    at games.strategy.engine.data.DefaultAttachment.getRawPropertyString(DefaultAttachment.java:81)
    at games.strategy.triplea.attatchments.TriggerAttachment.triggerUnitPropertyChange(TriggerAttachment.java:2004)
    at games.strategy.triplea.delegate.TechActivationDelegate.start(TechActivationDelegate.java:76)
    at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:546)
    at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:454)
    at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:281)
    at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:74)
    at games.strategy.engine.framework.startup.launcher.AbstractLauncher$1.run(AbstractLauncher.java:47)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No such Property Field: m_isTwoHit
    at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:60)
    at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
    at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
    at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
    at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:56)
    at games.strategy.util.PropertyUtil.getPropertyFieldObject(PropertyUtil.java:75)
    ... 9 more
[dtwcrash.tsvg.gz](https://github.com/triplea-game/triplea/files/178904/dtwcrash.tsvg.gz)

**Comment by GeoffBuchan** [comment]
I saw a similar thing happen when a Chinese player activated improved defensive structures, but I no longer have a .tsvg from that crash.

**Comment by DanVanAtta** [comment]
Fundamentally looks like a missing XML definition error. The fact the error is possible is a result of the XML data structure, which could potentially better enforce that rules/attachments are consistent. 

To note some possible fixes/update:
- Allowing the game to continue would help.
- Check for this situation either at map launch, or static
- Update XML so the relationship is better enforced, make the error less likely to happen

**Comment by DanVanAtta** [comment]
Belay that, I misread the stack trace, this is more interesting than a bad configuration..

**Comment by GeoffBuchan** [comment]
Thanks for the update... I now also have a game file that reaches the same state when activating improved defensive structures. Attaching dtw.tsvg.gz
[dtw.tsvg.gz](https://github.com/triplea-game/triplea/files/179435/dtw.tsvg.gz)

The behavior is similar to the Improved Carriers state. Once you complete the Chinese placement phase (unfortunately this time the file was from the beginning of the Chinese turn, so you'll need to end other phases also), the game brings up the start window and a sequence of similar errors:
triplea.engine.version.bin:1.8.0.9
Exception in thread "Triplea start thread" java.lang.IllegalStateException: No such Property Field: m_isTwoHit for Subject: UnitAttachment attached to:games.strategy.engine.data.UnitType called chineseEntrenchment with name:unitAttatchment
	at games.strategy.util.PropertyUtil.getPropertyFieldObject(PropertyUtil.java:77)
	at games.strategy.engine.data.DefaultAttachment.getRawPropertyString(DefaultAttachment.java:81)
	at games.strategy.triplea.attatchments.TriggerAttachment.triggerUnitPropertyChange(TriggerAttachment.java:2004)
	at games.strategy.triplea.delegate.TechActivationDelegate.start(TechActivationDelegate.java:76)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:546)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:454)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:281)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:74)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher$1.run(AbstractLauncher.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No such Property Field: m_isTwoHit
	at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:60)
	at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
	at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
	at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:66)
	at games.strategy.util.PropertyUtil.getFieldIncludingFromSuperClasses(PropertyUtil.java:56)
	at games.strategy.util.PropertyUtil.getPropertyFieldObject(PropertyUtil.java:75)
	... 9 more

**Comment by DanVanAtta** [comment]
This might be fixed in the latest prerelease. Engine was updated to strip the 'm_' when looking for properties.
