### ISSUE TITLE
Latest Version Check Log Message When Launching From IDE

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5500]
I see this in the logs when launching pre-release from IDE:
```
Nov 16, 2019 10:56:32 PM org.triplea.live.servers.LiveServersFetcher latestVersion
INFO: (No network connection?) Failed to get server properties
java.io.IOException: Unexpected status code (404)
	at games.strategy.engine.framework.map.download.ContentDownloader.<init>(ContentDownloader.java:64)
	at games.strategy.engine.framework.map.download.ContentDownloader.<init>(ContentDownloader.java:43)
	at org.triplea.live.servers.LiveServersFetcher.lambda$0(LiveServersFetcher.java:29)
	at org.triplea.live.servers.FetchingCache.fetchLiveServers(FetchingCache.java:53)
	at org.triplea.live.servers.FetchingCache.get(FetchingCache.java:31)
	at org.triplea.live.servers.FetchingCache.get(FetchingCache.java:1)
	at org.triplea.live.servers.LiveServersFetcher.latestVersion(LiveServersFetcher.java:44)
	at games.strategy.engine.auto.update.EngineVersionCheck.checkForLatestEngineVersionOut(EngineVersionCheck.java:28)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:26)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by DanVanAtta** [comment]
The live file is referenced by a typo 'yaml' vs 'yml' suffix.
We could have avoided this by pushing the configuration file to live first, but that would have been a bit odd/risky as the file format was not fully vetted and it would have been unused.. 

#5506 has a fix for this problem and updates the build to verify we won't have any bad links. Interestingly a number of links had a redirect and we had a second one that was also broken.
