### ISSUE TITLE
Unloading Units Causes Crash (Pre-Release)

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5502]
**Describe the bug**
Opened up a revised game and tried loading a bunch of units then unloading them during combat move and the game crashed with this error:
```
SEVERE: Exception on remote
java.lang.RuntimeException: Exception on remote
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:57)
	at com.sun.proxy.$Proxy9.move(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.player.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:152)
	at com.sun.proxy.$Proxy9.move(Unknown Source)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:346)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.move(TripleAPlayer.java:354)
	at games.strategy.triplea.TripleAPlayer.start(TripleAPlayer.java:142)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:575)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:445)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:306)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:56)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:1)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$0(AbstractLauncher.java:16)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at games.strategy.triplea.delegate.MoveValidator.validateBasic(MoveValidator.java:699)
	at games.strategy.triplea.delegate.MoveValidator.validateMove(MoveValidator.java:100)
	at games.strategy.triplea.delegate.MoveDelegate.move(MoveDelegate.java:628)
	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:120)
	at com.sun.proxy.$Proxy9.move(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:146)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:129)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:114)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:94)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	... 23 more
```

**To Reproduce**
1. Start new revised game
2. Edit a bunch of transport into a sea zone
3. Move a bunch of units into the transports
4. Try unloading into enemy territory and it crashes

**Comment by asvitkine** [comment]
Thanks, will take a look!

**Comment by asvitkine** [comment]
Should be fixed by https://github.com/triplea-game/triplea/pull/5504/files along with another issue I discovered while working on the follow-up refactoring.
