### ISSUE TITLE
Stack trace: SEVERE: Not in an event or step, but trying to add change

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5560]
**Describe the bug**

stack trace in somewhere in round 50 in AI vs AI game, (AI continued to play seemingly unaffected):

```
SEVERE: Not in an event or step, but trying to add change: Property change, unit:artillery owned by Russians property:alreadyMoved newValue:2 oldValue:0. Current history node is: null
Nov 21, 2019 8:22:54 PM games.strategy.engine.message.unifiedmessenger.UnifiedMessenger invoke
WARNING: Not in a step, but trying to add event: Filler event for change: Property change, unit:artillery owned by Russians property:alreadyMoved newValue:2 oldValue:0. Current history node is: null
java.lang.IllegalStateException: Not in a step, but trying to add event: Filler event for change: Property change, unit:artillery owned by Russians property:alreadyMoved newValue:2 oldValue:0. Current history node is: null
	at games.strategy.engine.history.HistoryWriter.startEvent(HistoryWriter.java:123)
	at games.strategy.engine.history.HistoryWriter.addChange(HistoryWriter.java:168)
	at games.strategy.engine.framework.ServerGame$1.gameDataChanged(ServerGame.java:96)
	at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:146)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:129)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:114)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:150)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:51)
	at com.sun.proxy.$Proxy7.gameDataChanged(Unknown Source)
	at games.strategy.engine.framework.ServerGame.addChange(ServerGame.java:676)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:93)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:88)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:88)
	at games.strategy.triplea.delegate.GameDelegateBridge.addChange(GameDelegateBridge.java:62)
	at games.strategy.triplea.delegate.BattleTracker.addBattle(BattleTracker.java:327)
	at games.strategy.triplea.delegate.BattleTracker.addBattle(BattleTracker.java:285)
	at games.strategy.triplea.delegate.MovePerformer$3.execute(MovePerformer.java:273)
	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:34)
	at games.strategy.triplea.delegate.MovePerformer.populateStack(MovePerformer.java:334)
	at games.strategy.triplea.delegate.MovePerformer.moveUnits(MovePerformer.java:76)
	at games.strategy.triplea.delegate.MoveDelegate.performMove(MoveDelegate.java:690)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.delegate.DelegateExecutionManager$1.invoke(DelegateExecutionManager.java:120)
	at com.sun.proxy.$Proxy2.performMove(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:146)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:129)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:114)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invokeAndWait(UnifiedMessenger.java:94)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:55)
	at com.sun.proxy.$Proxy2.performMove(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor41.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.player.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:152)
	at com.sun.proxy.$Proxy2.performMove(Unknown Source)
	at games.strategy.triplea.ai.pro.util.ProMoveUtils.doMove(ProMoveUtils.java:453)
	at games.strategy.triplea.ai.pro.ProCombatMoveAi.doMove(ProCombatMoveAi.java:157)
	at games.strategy.triplea.ai.pro.ProAi.move(ProAi.java:150)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:514)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:575)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:445)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:306)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:56)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:29)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by ron-murhammer** [comment]
@DanVanAtta I've seen this a few times as well. It has something to do with the history not currently pointing to a node or an expected node while its trying to write something to it. The most likely reason is some sort of race condition and this has happened even in non-AI games. Unfortunately, I think the easiest and possibly best thing to do is make this error message at a lesser level as its a primarily harmless error (fails to write some text to the history).

**Comment by DanVanAtta** [comment]
Would certainly be nice to RC it.  Given it is recoverable, I'd also certainly understand declaring it a logging bug and ensuring good recovery from the problem.

**Comment by ron-murhammer** [comment]
Agree. I've glanced at it a bit a while back just wanted to point out that it is mostly harmless.

**Comment by DanVanAtta** [comment]
Duplicate of : https://github.com/triplea-game/triplea/issues/5501

**Comment by DanVanAtta** [comment]
Actually, maybe not a duplicate of #5501 (TBD)

**Comment by DanVanAtta** [comment]
Duplicate of: https://github.com/triplea-game/triplea/issues/5501
