### ISSUE TITLE
java.lang.NullPointerException: at org.triplea.thread.LockUtil.releaseLock(LockUtil.java:80)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#5561]
**To Reproduce**
Not sure.. seemingly:
- stopped an in-progress game with a debugger, 
- mid-debug, closed the game.
- game closed down and brought me back to to the launch screen 
- launched a new game again, saw stack trace on startup

That sequence does not make sense to me.. Regardless anything like it should not have resulted in a NPE when launching a new game.

**Stack Trace*

```
  public void releaseLock(final Lock lock) {
    int count = locksHeld.get().get(lock);  // << NPE on this line
```

```
SEVERE: null
java.lang.NullPointerException
	at org.triplea.thread.LockUtil.releaseLock(LockUtil.java:80)
	at games.strategy.engine.data.GameData.releaseReadLock(GameData.java:343)
	at games.strategy.triplea.ui.StatPanel$StatTableModel.getRowCount(StatPanel.java:246)
	at java.desktop/javax.swing.JTable.getRowCount(JTable.java:2650)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.createTableSize(BasicTableUI.java:1732)
	at java.desktop/javax.swing.plaf.basic.BasicTableUI.getPreferredSize(BasicTableUI.java:1773)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:795)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validateTree(Container.java:1731)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/java.awt.Container.validateUnconditionally(Container.java:1694)
	at java.desktop/java.awt.Window.show(Window.java:1050)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1031)
	at games.strategy.engine.framework.startup.mc.HeadedLaunchAction.lambda$startGame$2(HeadedLaunchAction.java:69)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ron-murhammer** [comment]
Haven't seen anything like that before. The trace is essentially saying one of the UI panels had a read lock on game data and somehow the lock became null.

**Comment by RoiEXLab** [comment]
So I had a quick look at the actual source, and it looks like the only way this line can throw a NPE is if the lock wasn't present in the map and the Integer object returned by `Map#get` was null.
When converting null to an int, a NPE is thrown by the JVM.
It might help putting an explicit presence check in place that maybe to strings the lock or something when missing
