### ISSUE TITLE
File must exist at path: .../triplea/game-headed/assets/unit_scroller/center.png

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5566]
**Describe the bug**
When starting a game I get this exception:

```
java.lang.IllegalArgumentException: File must exist at path: .../triplea/game-headed/assets/unit_scroller/center.png
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at games.strategy.triplea.image.ImageLoader.getImage(ImageLoader.java:21)
        at games.strategy.triplea.ui.unit.scroller.UnitScrollerIcon.get(UnitScrollerIcon.java:32)
        at games.strategy.triplea.ui.unit.scroller.UnitScroller.build(UnitScroller.java:192)
        at games.strategy.triplea.ui.MovePanel.getUnitScrollerPanel(MovePanel.java:1694)
        at games.strategy.triplea.ui.AbstractMovePanel.lambda$display$2(AbstractMovePanel.java:242)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Engine Version or SHA**
Synced to 703f363c37ecef97092517370e715913a92c99f1

**Comment by DanVanAtta** [comment]
Try: `./gradlew clean downloadAssets`

If you're using eclipse, it would be excellent if we could solve running the `downloadAssets` command as part of the headed game launcher.

**Comment by asvitkine** [comment]
That seemed to have fixed it. Any idea why that's needed? (I don't use eclipse, just gradlew from the command line usually.)

**Comment by RoiEXLab** [comment]
@asvitkine We keep the assets in a different repository (triple-game/assets), this build step downloads the assets from there into the right directory.

> just gradlew from the command line usually.

Ok, that's some hardcore coding there 😅
