### ISSUE TITLE
NPE in AI code when running an all-AI game on WW2 Global 1940 2nd edition

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5655]
**Describe the bug**
The following NPE is seen when running an all-AI game on WW2 Global 1940 2nd edition:
```
java.lang.NullPointerException
        at games.strategy.triplea.ai.pro.ProNonCombatMoveAi.moveUnitsToBestTerritories(ProNonCombatMoveAi.java:1661)
        at games.strategy.triplea.ai.pro.ProNonCombatMoveAi.doNonCombatMove(ProNonCombatMoveAi.java:151)
        at games.strategy.triplea.ai.pro.ProAi.move(ProAi.java:144)
        at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:514)
        at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:575)
        at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:445)
        at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:306)
        at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:56)
        at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:29)
        at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

This happened on ANZAC move on round 4.

**Engine Version or SHA**
On tip of tree 117653f27fb52197b8006d571e0f2b83e7250b0b with https://github.com/triplea-game/triplea/pull/5653 patched that fixes other issue.

**Comment by asvitkine** [comment]
It seems the code in question has not changed in a while.

And I also don't know it well enough to understand what this is meant to be doing. The most obvious thing is to just add an entry to the moveMap if it doesn't exist yet, but I'm not sure if that's the intention - or why it's not there to begin with.

**Comment by asvitkine** [comment]
Here's save game that repros this:

[NPE_save.tsvg.zip](https://github.com/triplea-game/triplea/files/3920118/NPE_save.tsvg.zip)

**Comment by asvitkine** [comment]
Adding a logging statement shows:

transport owned by ANZAC moved to safest territory at 61 Sea Zone and unloading to South Australia with [], strengthDifference=0.0
transport owned by ANZAC moved to safest territory at 51 Sea Zone and unloading to Samoa with [], strengthDifference=0.0

So it seems amphibUnits is empty? Perhaps this is why moveMap wasn't filled?

But why is it empty? The code is:

```
          if (TransportTracker.isTransporting(transport)) {
            final List<Unit> amphibUnits = TransportTracker.transporting(transport);
```

**Comment by asvitkine** [comment]
Oh, looks like I reversed the condition on isTransporting() in https://github.com/triplea-game/triplea/pull/5578.

Fix coming up, and I'll add a test.
