### ISSUE TITLE
NPE in forum poster component

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#5809]
```
java.lang.NullPointerException
        at games.strategy.engine.pbem.ForumPosterComponent.getHasPostedTurnSummary(ForumPosterComponent.java:161)
        at games.strategy.triplea.ui.EndTurnPanel.performDone(EndTurnPanel.java:19)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at games.strategy.triplea.ui.ActionButtons.lambda$get$2(ActionButtons.java:288)
        at org.triplea.swing.SwingComponents.lambda$addKeyBinding$5(SwingComponents.java:491)
        at org.triplea.swing.SwingAction$2.actionPerformed(SwingAction.java:84)
        at java.desktop/javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1810)
        at java.desktop/javax.swing.JComponent.processKeyBinding(JComponent.java:2900)
        at java.desktop/javax.swing.KeyboardManager.fireBinding(KeyboardManager.java:311)
        at java.desktop/javax.swing.KeyboardManager.fireKeyboardAction(KeyboardManager.java:253)
        at java.desktop/javax.swing.JComponent.processKeyBindingsForAllComponents(JComponent.java:2993)
        at java.desktop/javax.swing.JComponent.processKeyBindings(JComponent.java:2985)
        at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2862)
        at java.desktop/java.awt.Component.processEvent(Component.java:6409)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1950)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:870)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1139)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1009)
        at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:835)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**How can the problem be recreated?**

**When the problem is fixed, what should have happened instead?**

**Which Engine Version are you using?** 

**Expected behavior**

**Screenshots** 

**Zipped Save Game**

**Comment by asvitkine** [comment]
This was by just playing Revised while testing with human as Russians and Hard AI for others. Happened at end of Russia's turn.

**Comment by RoiEXLab** [comment]
Any chance you pressed Shift+D there?
Looks like it has something to do with @DanVanAtta's #5084 PR which added key listeners for this type of action, however this particular action requires that `AbstractForumPosterPanel#waitForDone` is run first, but it could be just a race-condition as well, the "required" layoutComponents method is run asynchronously

**Comment by asvitkine** [comment]
Not 100% sure, but yes it's likely I was using Shift-D there.

**Comment by DanVanAtta** [comment]
The key listener is simulating a button click, is this not just an existing problem?

**Comment by RoiEXLab** [comment]
@DanVanAtta I assume that the button is disabled/unclickable until the component layout is there, but that's just my assumption

**Comment by DanVanAtta** [comment]
The key listener should be a no-op if the button is not enabled, but perhaps there could be such a check missing.

**Comment by DanVanAtta** [comment]
Seems a NPE check is about as good as we can do here.

This turns out to be easy to repro:
- play a local game
- set all players except first to be AI
- play through the first turn
- when it's not your turn, press 'shift+d', the 'perform done' hotkey
- observe error

There is a complicating issues here that prevent a better fix:
- endTurn panel is hidden yet swing thinks it's visible and the done button enabled, even on single player games.  The panel ideally would not even be instantiated unless we were actually playing a forum or PBEM game.
