### ISSUE TITLE
Null Pointer Exception , Version 17560

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#5837]
```
Jan 11, 2020 11:18:28 AM org.triplea.game.client.HeadedGameRunner lambda$main$0
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.ai.pro.util.ProOddsCalculator.setData(ProOddsCalculator.java:31)
	at games.strategy.triplea.ai.pro.ProAi.purchase(ProAi.java:210)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:507)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:538)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:408)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:56)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:29)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**How can the problem be recreated?**
Error occurs immediately when AI moves.

**When the problem is fixed, what should have happened instead?**

**Which Engine Version are you using?** 
17560
**Expected behavior**

**Screenshots** 

**Zipped Save Game**

[autosaveBeforeEndTurn.zip](https://github.com/triplea-game/triplea/files/4049519/autosaveBeforeEndTurn.zip)

**Comment by ron-murhammer** [comment]
@RogerCooper Yeah, something is definitely broken here as the game essentially immediately crashes if you have an AI player.

**Comment by ron-murhammer** [comment]
@RogerCooper This should be fixed now in the next pre-release that is pushed out. Thanks for the report!
