### ISSUE TITLE
Unit Scroller Missing Image Error

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5840]
Happens frequently on current pre-release. I was testing New World Order specifically in this case. Might have to do with unique units that only certain nations have as it seems to flag things like Panzer for Russia which doesn't have a Panzer unit type (only Germany does).

Stack trace:
```
SEVERE: No image for unit type: UnitType{name=Panzer}, player: PlayerId named:Russians
java.lang.RuntimeException: No image for unit type: UnitType{name=Panzer}, player: PlayerId named:Russians
	at games.strategy.triplea.image.UnitImageFactory.lambda$2(UnitImageFactory.java:315)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at games.strategy.triplea.image.UnitImageFactory.getImageDimensions(UnitImageFactory.java:313)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.createUnitStackImage(AvatarPanelFactory.java:75)
	at games.strategy.triplea.ui.unit.scroller.AvatarPanelFactory.buildPanel(AvatarPanelFactory.java:52)
	at games.strategy.triplea.ui.unit.scroller.UnitScroller.lambda$6(UnitScroller.java:173)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by DanVanAtta** [comment]
Leaving open, don't have the bandwidth to look into this. Let's assign to people when they are actively working a problem or will be.

**Comment by ron-murhammer** [comment]
@DanVanAtta That's fine just wanted to at least tag you to see if you had seen it or had any insight.

**Comment by DanVanAtta** [comment]
No special insight here, it's a surprise to me, AFAIK the scroller logic renders unit images owned by a given country and also present on the board.

**Comment by ron-murhammer** [comment]
So it looks like the issue is that the unit scroller uses invoke later where its taking `matchedUnits` but using `currentPlayerSupplier` for the player. This can cause a mismatch if the current player's turn ends before the `invokeLater` fires.

To fix this I believe either matched Units should be pushed into the `invokeLater `or the player should be set into a temp variable as well before the `invokeLater`.

Code:
```
  private void drawUnitAvatarPane(final Territory t) {
    final List<Unit> matchedUnits =
        UnitScrollerModel.getMoveableUnits(
            t, movePhaseSupplier.get(), currentPlayerSupplier.get(), getAllSkippedUnits());

    SwingUtilities.invokeLater(
        () -> {
          selectUnitImagePanel.removeAll();
          if (currentPlayerSupplier.get() != null) {
            selectUnitImagePanel.add(
                avatarPanelFactory.buildPanel(matchedUnits, currentPlayerSupplier.get()));
          }
          selectUnitImagePanel.revalidate();
          selectUnitImagePanel.repaint();
        });
  }
```

@DanVanAtta Any thoughts on this? Not sure what you were going for here.

**Comment by DanVanAtta** [comment]
Good sleuthing work @ron-murhammer .

Likely I was minimizing the code being run in the `invokeLater` thread. Moving `matchedUnits` inside the invokeLater seems on the face of it to be a good move to help keep the values in-sync.
