### ISSUE TITLE
Unit Scroller NPE on Game Start

### ISSUE THREAD

**Issue by ron-murhammer** [triplea-game/triplea#5869]
Start a game with the latest pre-release with World At War and all Fast AIs. You get an immediate NPE as soon as the map launches:
```
SEVERE: null
java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:878)
	at games.strategy.triplea.ui.unit.scroller.UnitScrollerModel.getMoveableUnits(UnitScrollerModel.java:25)
	at games.strategy.triplea.ui.unit.scroller.UnitScroller.lambda$6(UnitScroller.java:167)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ron-murhammer** [comment]
@DanVanAtta Any insight on this? Or have you seen it?

**Comment by DanVanAtta** [comment]
Took a quick look. There was certainly a fight with the code on how to handle the initial case when a player's turn has started. Typically the current player's capital is selected, that was meant to be the first territory considered as selected.

I notice that when world at war launches, the map does not center on the first players capital. It seems like we then get a 'unit move' event before capitol focus. Considering capitols do not get automatic centering at all, it's still a surprise we get a unit move event right away, but the cause of the problem is at least more clear.

Is it another but that WatW does not auto-scroll to a the current players capitol?

Regardless, https://github.com/triplea-game/triplea/pull/5878 has a fix to handle 'unit move' event being fired before or without capitol being focused.
