### ISSUE TITLE
Invalid value for MonthOfYear (valid values 1-12): 0

### ISSUE THREAD

**Issue by dlmartin36** [triplea-game/triplea#5891]
Getting error when loading TripleA using latest build 1.9.0.0.13066 64 windows 64 bit.
```
Invalid value for MonthOfYear (valid values 1-12): 0

Error in subdirectory of TripleA:

Jan 29, 2020 9:06:21 PM games.strategy.engine.framework.GameRunner lambda$start$0
[error.log](https://github.com/triplea-game/triplea/files/4131844/error.log)

SEVERE: Invalid value for MonthOfYear (valid values 1 - 12): 0
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(Unknown Source)
	at java.time.temporal.ChronoField.checkValidValue(Unknown Source)
	at java.time.LocalDate.of(Unknown Source)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.parseUpdateCheckDate(UpdatedMapsCheck.java:45)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:30)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:16)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:28)
	at java.lang.Thread.run(Unknown Source)

Jan 29, 2020 9:06:57 PM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: Invalid value for MonthOfYear (valid values 1 - 12): 0
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(Unknown Source)
	at java.time.temporal.ChronoField.checkValidValue(Unknown Source)
	at java.time.LocalDate.of(Unknown Source)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.parseUpdateCheckDate(UpdatedMapsCheck.java:45)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:30)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:16)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:28)
	at java.lang.Thread.run(Unknown Source)

Jan 29, 2020 9:12:53 PM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: Invalid value for MonthOfYear (valid values 1 - 12): 0
java.time.DateTimeException: Invalid value for MonthOfYear (valid values 1 - 12): 0
	at java.time.temporal.ValueRange.checkValidValue(Unknown Source)
	at java.time.temporal.ChronoField.checkValidValue(Unknown Source)
	at java.time.LocalDate.of(Unknown Source)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.parseUpdateCheckDate(UpdatedMapsCheck.java:45)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:30)
	at games.strategy.engine.auto.update.UpdatedMapsCheck.isMapUpdateCheckRequired(UpdatedMapsCheck.java:16)
	at games.strategy.engine.auto.update.UpdateChecks.checkForUpdates(UpdateChecks.java:28)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by RoiEXLab** [comment]
Interesting Problem.
Definitely something we should look into, but could you double check this problem does still happen?
I could imagine that the problem might solve itself because we have February now.

**Comment by RoiEXLab** [comment]
@DanVanAtta I have looked into this and it seems like it's an update related issue introduced in https://github.com/triplea-game/triplea/pull/2099/files#diff-0840434b65a524f239ee2a067d3260b5L35-R38
Basically `java.util.Calendar` returns 0-based month counts, whereas `java.time.LocalDateTime` return "natural" month numbers.

I wonder if we should think about a mechanism to reset all stored client settings to prevent those kind of errors, or if we should just go ahead and put everything inside a try-catch block to prevent those kind of issues.

@dlmartin36 
Regardless I created a script that should fix the issue for you, simply unzip the file, double click the file inside it and accept the 2 dialogs, then it should work again no problem
[Reset-Update-Date.zip](https://github.com/triplea-game/triplea/files/4143375/Reset-Update-Date.zip)

**Comment by DanVanAtta** [comment]
The client setting overlap between versions can cause its share of headaches.

IMO a reset would not be super desirable as we would be removing all settings, part of the point was the settings would be persistent across versions.

We're almost in the territory to consider having a 'settings.props' file to store settings. In the short term, for client settings that conflict, my first recommendation would be to change the client setting key so that it looks brand new and the old one becomes unused.

**Comment by DanVanAtta** [comment]
@RoiEXLab is there any further follow-up we can do here? Are there any code-improvements? Can we close this issue?

**Comment by RoiEXLab** [comment]
I mean we could put a try catch block around the whole thing, but given that this change has been out for years and the problem only occured once so far, it's probably not worth it IMO

**Comment by ron-murhammer** [comment]
@DanVanAtta @RoiEXLab Thoughts on this one? Does it need addressed for the pre-release? Close or leave it open to eventually fix otherwise?

**Comment by RoiEXLab** [comment]
Leaning towards the latter, this issue is so rare that It's perhaps not even worth "fixing"

**Comment by DanVanAtta** [comment]
@RoiEXLab I don't quite see the reasoning why this would be extremely rare, would you mind clarifying that?

**Comment by RoiEXLab** [comment]
@DanVanAtta It would only happen if the value was set during january (index 0) + this change was already done during 1.9 development so given that we haven't seen this error until now for all the time 1.9 was out now, imperical evidence suggests that it's rare

**Comment by DanVanAtta** [comment]
Do I understand right - the version of TripleA where this would have been a problem no longer exists? (ie: it's a 1.9 prerelease, not a 1.9 release, and also this problem does not exist in 2.0).

**Comment by RoiEXLab** [comment]
Yes, people on the latest 1.9 who don't ran into this Problem already won't have this Problem on 2.0 either.
It's an 1.8 -> 1.9 upgrade issue most likely. (I'm not exactly sure when in the development of 1.9 this change was introduced, so it could be an 1.9 -> 1.9 issue as well)

**Comment by DanVanAtta** [comment]
Thanks for clarifying :+1:
