### ISSUE TITLE
2.0.17994: Dice Server returns error

### ISSUE THREAD

**Issue by panther2** [triplea-game/triplea#5918]
**How can the problem be recreated?**

Enter registered email-addresses into the "Dice Server Options".
Hit "Test Server"

**Which Engine Version are you using?** 

2.0.17994

```
Test
Contacting  https://dice.marti.triplea-game.org
An error has occurred!
Possible reasons the error could have happened:
  1: An invalid e-mail address
  2: Firewall could be blocking TripleA from connecting to the Dice Server
  3: The e-mail address does not exist
  4: An unknown error, please see the error console and consult the forums for help
     Visit https://forums.triplea-game.org/  for extra help
Text from dice server:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

java.io.IOException: Could not find start index, text returned is:<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

	at games.strategy.engine.random.MartiDiceRoller.getDice(MartiDiceRoller.java:113)
	at games.strategy.engine.random.PbemDiceRoller$HttpDiceRollerDialog.rollInSeparateThread(PbemDiceRoller.java:228)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Maybe it is because of the underlying server-address seems to be: `dice.marti.triplea-game.org` now.

**Comment by RoiEXLab** [comment]
Should be fixed now using the latest pre-release

**Comment by panther2** [comment]
@RoiEXLab Unfortunately it looks like this commit did not result in a new pre-release...

**Comment by RoiEXLab** [comment]
Ah, there was a temporary travis outage for some reason.
I did restart the build, but I missed that just restarting a single build won't restart the whole deployment chain.
The files haven been deployed now: https://github.com/triplea-game/triplea/releases/tag/2.0.17997
