### ISSUE TITLE
Pre-Release Bot Server has No Available Games

### ISSUE THREAD

**Issue by prastle** [triplea-game/triplea#6040]
**How can the problem be recreated?**
Join the bot server and attempt to select a map.  The error message in the screenshot is received.

**When the problem is fixed, what should have happened instead?**
You should be able to select a map to play.
**Which Engine Version are you using?** 

**Screenshots** 
![2020-03-11 (2)](https://user-images.githubusercontent.com/17258293/76473394-b8057680-63ce-11ea-9ac9-48d9b5244824.png)

**Zipped Save Game**

**Comment by prastle** [comment]
Current error message in the bot when attempting to load a save game file

Welcome to an automated dedicated host service (a host bot). 
If anyone disconnects, the autosave will be reloaded (a save might be loaded right now). 
You can get the current save, or you can load a save (only saves that it has the map for).
BotServer-01:  Mar 16, 2020 12:03:42 AM games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSe
lectorModel getGameData
BotServer-01:  SEVERE: Failed to load game
BotServer-01:  java.io.IOException: Incompatible engine versions. We are: 2.0.18289<br>Trying to load incompatible 
save game version: 1.9.0.0.11996<br>To download an older version of TripleA,<br>please visit: <a...
BotServer-01:  	at games.strategy.engine.framework.GameDataManager.loadGame(GameDataManager.java:68)
BotServer-01:  	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.getGameDa
ta(GameSelectorModel.java:95)
BotServer-01:  	at org.triplea.game.server.HeadlessGameServer.loadGameSave(HeadlessGameServer.java:130)
BotServer-01:  	at games.strategy.engine.framework.startup.mc.ServerModel$1.lambda$changeToGameSave$1(ServerModel.j
ava:245)
BotServer-01:  	at org.triplea.io.IoUtils.lambda$consumeFromMemory$0(IoUtils.java:35)
BotServer-01:  	at org.triplea.io.IoUtils.readFromMemory(IoUtils.java:57)
BotServer-01:  	at org.triplea.io.IoUtils.consumeFromMemory(IoUtils.java:32)
BotServer-01:  	at games.strategy.engine.framework.startup.mc.ServerModel$1.changeToGameSave(ServerModel.java:241)
BotServer-01:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
BotServer-01:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
BotServer-01:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.
java:43)
BotServer-01:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
BotServer-01:  	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:146)
BotServer-01:  	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:129)
BotServer-01:  	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:114)
BotServer-01:  	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.lambda$messageReceived$0(Unified
Messenger.java:293)
BotServer-01:  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

**Comment by DanVanAtta** [comment]
Are you  trying to load a 1.9 save @prastle ? Side-note, this might be better as a new issue as no maps and failing to load are somewhat distinct.

**Comment by prastle** [comment]
gd pt let me test that 1 sec

**Comment by prastle** [comment]
@DanVanAtta I am able to host np in the new lobby now.  So I hosted a game saved it and then attempted to load it in bot.  This time no error message just fails to do anything.  You are probably correct it was a 1.9 save I was trying to load.  either way no can use this bot atm.  Because you cannot load new game or load a save game.  I am using 2.0.18267 atm.

**Comment by DanVanAtta** [comment]
PS: the OP is a  perfect bug report @prastle - thank you, it's exactly what developers look for!
