### ISSUE TITLE
Minimum Version Error (1.9.0.0.13066)

### ISSUE THREAD

**Issue by Cernelius** [triplea-game/triplea#6079]
If I give minimum version 2.0 to a game, this is what I get:
```
mar 23, 2020 9:13:53 PM games.strategy.engine.framework.ui.GameChooserModel createGameChooserEntry
GRAVE: Engine version problem:file:/D:/Programs/TripleA/downloadedMaps/270bc_wars/games/270BC_Wars.xml
games.strategy.engine.data.EngineVersionException: Current engine version: 1.9, is not compatible with version: 2.0, required by map: 270BC Wars
	at games.strategy.engine.data.GameParser.parseMinimumEngineVersionNumber(GameParser.java:240)
	at games.strategy.engine.data.GameParser.parseMapProperties(GameParser.java:146)
	at games.strategy.engine.data.GameParser.parseShallow(GameParser.java:128)
	at games.strategy.engine.data.GameParser.parseShallow(GameParser.java:123)
	at games.strategy.engine.framework.ui.GameChooserEntry.<init>(GameChooserEntry.java:36)
	at games.strategy.engine.framework.ui.GameChooserModel.createEntry(GameChooserModel.java:168)
	at games.strategy.engine.framework.ui.GameChooserModel.createGameChooserEntry(GameChooserModel.java:147)
	at games.strategy.engine.framework.ui.GameChooserModel.populateFromDirectory(GameChooserModel.java:181)
	at games.strategy.engine.framework.ui.GameChooserModel.lambda$parseMapFiles$0(GameChooserModel.java:62)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
	at java.util.concurrent.CountedCompleter.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
This happens every time I open TripleA or try to join a hosted game in the lobby.

Am I right assuming that if I would upload in the repository such a game, all regular users using the 1.9 release will keep having this error, over and over again?

If so, I would suggest excluding a map from list for not meeting the minimumversion being no cause for an error (also since it is not actually an error of any kind, really).

Beside potentially fixing this issue, I would appreciate an answer, as I might request adding to the repository a 2.0 only game before 2.0 is released, but I'm not sure I want to do it, if, then, having people cursing me for having downloaded a map giving them errors all along... Thanks.

**Comment by DanVanAtta** [comment]
You can switch map @Cernelius after loading the game or stuck with the error message?

Some other thoughts:
- We are not going to be get this fixed for 1.9. We would need to have players mass update their game installation to pick up a patch, instead we would want them to upgrade to 2.0.

- Is the error messaging any better in 2.0, is this showing up as an info message instead of as a game crash message?

- Filtering game downloads for 2.0 is prohibitive performance-wise.

- We've had some discussions about version numbering (https://github.com/triplea-game/triplea/issues/3104), I have not been left very satisfied with those results:
   - map compatibility is unnecessarily tied to engine version
   - map compatibility is a problem when map advanced before an engine is released
   - map backward compatibility is a problem

IMO we need a different versioning number for Map XML specs that would imply both a min and max compatibility value.

In the meantime, the best thing to do is probably to keep 270BC the same, and launch a clone of it that is compatible with 2.0.

**Comment by Cernelius** [comment]
I cannot get the console to show at all, in 2.0.18437.

It is not 270BC, it is another map.

**Comment by DanVanAtta** [comment]
In the end this looks like a logging/messaging bug. The core message is there, that the current engine version is not compatible with map, but it should not be logged as 'severe' nor give a stack trace. The error message should also inform the user how to fix the problem (by downloading a newer version of the engine).

**Comment by DanVanAtta** [comment]
Fixed by: https://github.com/triplea-game/triplea/pull/6244

With #6244 the incompatible map will be suppressed.

> If so, I would suggest excluding a map from list for not meeting the minimumversion being no cause for an error (also since it is not actually an error of any kind, really).


> Beside potentially fixing this issue, I would appreciate an answer, as I might request adding to the repository a 2.0 only game before 2.0 is released, but I'm not sure I want to do it, if, then, having people cursing me for having downloaded a map giving them errors all along... Thanks.

That will be done. This was a good error report as the endless error message was bad. After 1.9 is no longer played, such a scenario should be safe without the cursing.
