### ISSUE TITLE
Build Failure -  java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6133]
@DanVanAtta The current test failure is interesting:
```
WARN  [2020-04-03 00:37:48,283] org.triplea.web.socket.MessageSender: Failed to send message: ServerMessageEnvelope(messageType=PLAYER_LEFT, payload={"value":"mod"})
! java.nio.channels.ClosedChannelException: null
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.enqueue(FrameFlusher.java:109)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:507)
! at org.eclipse.jetty.websocket.common.extensions.ExtensionStack$Flusher.process(ExtensionStack.java:400)
! at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
! at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
! at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.outgoingFrame(ExtensionStack.java:277)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.uncheckedSendFrame(WebSocketRemoteEndpoint.java:307)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendAsyncFrame(WebSocketRemoteEndpoint.java:241)
! at org.eclipse.jetty.websocket.common.WebSocketRemoteEndpoint.sendStringByFuture(WebSocketRemoteEndpoint.java:404)
! at org.eclipse.jetty.websocket.jsr356.JsrAsyncRemote.sendText(JsrAsyncRemote.java:176)
! ... 7 common frames omitted
! Causing: java.util.concurrent.ExecutionException: java.nio.channels.ClosedChannelException
! at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:122)
! at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30)
! at org.triplea.web.socket.MessageSender.sendMessage(MessageSender.java:27)
! at org.triplea.web.socket.MessageSender.lambda$accept$0(MessageSender.java:19)
! at org.triplea.java.Interruptibles.lambda$await$0(Interruptibles.java:41)
! at org.triplea.java.Interruptibles.awaitResult(Interruptibles.java:78)
! at org.triplea.java.Interruptibles.await(Interruptibles.java:39)
! at org.triplea.web.socket.MessageSender.lambda$accept$1(MessageSender.java:19)
! at java.base/java.lang.Thread.run(Thread.java:834)
WARN  [2020-04-03 00:37:48,351] org.triplea.modules.chat.ChatMessagingService: Messaging service error processing request, sending error message to client
! java.io.IOException: Broken pipe
! at java.base/sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
! at java.base/sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:182)
! at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
! at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:264)
! ... 16 common frames omitted
! Causing: org.eclipse.jetty.io.EofException: null
! at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:284)
! at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:393)
! at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:277)
! at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:380)
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.flush(FrameFlusher.java:264)
! at org.eclipse.jetty.websocket.common.io.FrameFlusher.process(FrameFlusher.java:193)
! at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:241)
! at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:224)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.outgoingFrame(AbstractWebSocketConnection.java:509)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.close(AbstractWebSocketConnection.java:184)
! at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:452)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
! at java.base/java.lang.Thread.run(Thread.java:834)
```

I assume it doesn't happen all the time, that's why I didn't restart the build

_Originally posted by @RoiEXLab in https://github.com/triplea-game/triplea/pull/6121#issuecomment-608671409_

**Comment by RoiEXLab** [comment]
@DanVanAtta Why has this issue been closed?
Has anything changed?

**Comment by DanVanAtta** [comment]
It's a warn message, should not have caused an impact. You're welcome to
investigate further, not sure if we can do too much. Maybe run thr related
test repeatedly. There was an update pushed to the branch that saw this,
I'm not sure if we have the info of which build and test that failed
