### ISSUE TITLE
NPE during edit mode: Matches.lambda$alliedUnit$161(Matches.java:1352)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6274]
**How can the problem be recreated?**
- single player napoleonic wars
- enter edit mode
- click action tab
- move neutral units to another territory

**When the problem is fixed, what should have happened instead?**
- No NPE

**Which Engine Version are you using?** 

Latest 2.0
@
commit 29d1378299d867f59c087b64a26577d941cbc9bc (tag: 2.0.18843, origin/master, master)
Date:   Thu Apr 16 17:54:04 2020 -0400

**Save Game** 
[2020-4-17-Napoleonic-Empires.tsvg.zip](https://github.com/triplea-game/triplea/files/4491515/2020-4-17-Napoleonic-Empires.tsvg.zip)

** Screenshot **
![Screenshot from 2020-04-17 00-18-20](https://user-images.githubusercontent.com/12397753/79542732-fe3e9d00-8040-11ea-90fe-8db6586b730d.png)

** Stack Trace **
```
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.delegate.Matches.lambda$alliedUnit$161(Matches.java:1352)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.triplea.java.collections.CollectionUtils.getMatches(CollectionUtils.java:49)
	at games.strategy.engine.data.UnitCollection.getMatches(UnitCollection.java:192)
	at games.strategy.triplea.util.MovableUnitsFilter.getPossibleTransportsToLoad(MovableUnitsFilter.java:192)
	at games.strategy.triplea.util.MovableUnitsFilter.filterUnitsThatCanMove(MovableUnitsFilter.java:117)
	at games.strategy.triplea.ui.panel.move.MovePanel.updateUnitsThatCanMoveOnRoute(MovePanel.java:1125)
	at games.strategy.triplea.ui.panel.move.MovePanel$3.mouseMoved(MovePanel.java:706)
	at games.strategy.triplea.ui.panels.map.MapPanel.notifyMouseMoved(MapPanel.java:499)
	at games.strategy.triplea.ui.panels.map.MapPanel.updateMouseHoverState(MapPanel.java:319)
	at games.strategy.triplea.ui.panels.map.MapPanel$4.mouseMoved(MapPanel.java:267)
	at java.desktop/java.awt.AWTEventMulticaster.mouseMoved(AWTEventMulticaster.java:338)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6677)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3360)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4560)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by ron-murhammer** [comment]
Interesting. Can't say I've ever tried moving a neutral unit in edit mode.

**Comment by DanVanAtta** [comment]
Just checked, this is not a problem on 1.9; so this is a regression.

**Comment by asvitkine** [comment]
I tried the steps on 2.6 and the issue no longer repros.
