### ISSUE TITLE
NPE in MoveValidator.checkCanalStepAndOwnership(MoveValidator.java:1541)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6275]
**How can the problem be recreated?**
- unsure

**StackTrace**

```
Caused by: java.lang.NullPointerException
	at games.strategy.triplea.delegate.MoveValidator.checkCanalStepAndOwnership(MoveValidator.java:1541)
	at games.strategy.triplea.delegate.MoveValidator.canAnyPassThroughCanal(MoveValidator.java:1529)
	at games.strategy.triplea.delegate.MoveValidator.canAnyUnitsPassCanal(MoveValidator.java:356)
	at games.strategy.engine.data.GameMap.lambda$getNeighborsValidatingCanals$5(GameMap.java:250)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by DanVanAtta** [comment]
This will be fixed by: https://github.com/triplea-game/triplea/pull/6383
