### ISSUE TITLE
NPE for image when starting local game

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#6338]
I originally just wanted to report this exception using the built in report feature, but this one froze on me for whatever reason.

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at games.strategy.triplea.image.UnitImageFactory.getImage(UnitImageFactory.java:124)
	at games.strategy.triplea.ui.screen.UnitsDrawer.draw(UnitsDrawer.java:116)
	at games.strategy.triplea.ui.screen.Tile.draw(Tile.java:70)
	at games.strategy.triplea.ui.screen.Tile.drawImage(Tile.java:55)
	at games.strategy.triplea.ui.panels.map.MapPanel.lambda$paint$7(MapPanel.java:749)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Seems like a concurrency problem to me.

**Comment by DanVanAtta** [comment]
Marking as a problem, assuming for now this is an existing problem unless we can show this is new as of 2.0

**Comment by DanVanAtta** [comment]
https://github.com/triplea-game/triplea/pull/6385 has a likely fix.

Identified a TOCTOU if we clear images cache after checking if an image exists and then trying to load it. The only other alternative is we are storing a null image into cache which does not look to be the case.
