### ISSUE TITLE
Freeze when reporting with invalid URI

### ISSUE THREAD

**Issue by RoiEXLab** [triplea-game/triplea#6339]
When trying to report #6338 via the built-in mechanism the whole game froze on me.

Looking at the debugger it seems that this error occured because I was still using an inalid URI I set for testing some time ago:

```
feign.FeignException: uri.invalid executing POST http://uri.invalid/error-report
Caused By: java.net.UnknownHostException: uri.invalid
```
I can't provide a more complete stacktrace unfortunately because I can only look at the exception in the debugger I attached afterwards, so not much to see here, but it should get the point across

So here's the Thread Dump:
```
"AWT-EventQueue-0@30083562320" prio=6 tid=0x12 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at java.awt.EventQueue.getNextEvent(EventQueue.java:566)
	  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:190)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	  at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	  at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	  at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	  at java.awt.Dialog.show(Dialog.java:1070)
	  at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
	  at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
	  at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
	  at org.triplea.swing.SwingComponents.showDialogWithLinks(SwingComponents.java:409)
	  at org.triplea.debug.error.reporting.ConfirmationDialogController.doShowFailureConfirmation(ConfirmationDialogController.java:23)
	  at org.triplea.debug.error.reporting.ConfirmationDialogController.lambda$showFailureConfirmation$0(ConfirmationDialogController.java:19)
	  at org.triplea.debug.error.reporting.ConfirmationDialogController$$Lambda$1986.run(Unknown Source:-1)
	  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	  at java.awt.EventQueue$4.run(EventQueue.java:721)
	  at java.awt.EventQueue$4.run(EventQueue.java:715)
	  at java.security.AccessController.doPrivileged(AccessController.java:-1)
	  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	  at java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	  at java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

"Thread-7@30156588464" prio=6 tid=0x2a nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:885)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1039)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
	  at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	  at games.strategy.triplea.ui.ActionPanel.waitForRelease(ActionPanel.java:71)
	  at games.strategy.triplea.ui.TechPanel.waitForTech(TechPanel.java:263)
	  at games.strategy.triplea.ui.ActionButtons.waitForTech(ActionButtons.java:229)
	  at games.strategy.triplea.ui.TripleAFrame.getTechRolls(TripleAFrame.java:1805)
	  at games.strategy.triplea.TripleAPlayer.tech(TripleAPlayer.java:282)
	  at games.strategy.triplea.TripleAPlayer.start(TripleAPlayer.java:133)
	  at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:538)
	  at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:408)
	  at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	  at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:61)
	  at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:34)
	  at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
	  at games.strategy.engine.framework.startup.launcher.AbstractLauncher$$Lambda$1663.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:834)

"TimerQueue@30118515232" daemon prio=5 tid=0x17 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at java.util.concurrent.DelayQueue.take(DelayQueue.java:217)
	  at javax.swing.TimerQueue.run(TimerQueue.java:171)
	  at java.lang.Thread.run(Thread.java:834)

"Trident callback thread@30118515608" daemon prio=6 tid=0x18 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:433)
	  at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:196)

"Common-Cleaner@30083543528" daemon prio=8 tid=0xc nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	  at jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:148)
	  at java.lang.Thread.run(Thread.java:834)
	  at jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:134)

"ForkJoinPool.commonPool-worker-17@30118514584" daemon prio=6 tid=0x24 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"ForkJoinPool.commonPool-worker-31@30118517632" daemon prio=6 tid=0x23 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"ForkJoinPool.commonPool-worker-27@30118513888" daemon prio=6 tid=0x21 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"ForkJoinPool.commonPool-worker-23@30118513192" daemon prio=6 tid=0x1f nid=NA waiting
  java.lang.Thread.State: WAITING
	  at jdk.internal.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1628)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

"Thread-8@30227596288" prio=6 tid=0x39 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at org.triplea.java.Interruptibles.lambda$sleep$1(Interruptibles.java:108)
	  at org.triplea.java.Interruptibles$$Lambda$1787.run(Unknown Source:-1)
	  at org.triplea.java.Interruptibles.lambda$await$0(Interruptibles.java:41)
	  at org.triplea.java.Interruptibles$$Lambda$37.get(Unknown Source:-1)
	  at org.triplea.java.Interruptibles.awaitResult(Interruptibles.java:78)
	  at org.triplea.java.Interruptibles.await(Interruptibles.java:39)
	  at org.triplea.java.Interruptibles.sleep(Interruptibles.java:108)
	  at games.strategy.triplea.ui.panels.map.MapPanel$3.lambda$mousePressed$0(MapPanel.java:254)
	  at games.strategy.triplea.ui.panels.map.MapPanel$3$$Lambda$1956.run(Unknown Source:-1)
	  at java.lang.Thread.run(Thread.java:834)

"Trident pulse source thread@30118511632" daemon prio=6 tid=0x19 nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at org.pushingpixels.trident.TridentConfig$FixedRatePulseSource.waitUntilNextPulse(TridentConfig.java:67)
	  at org.pushingpixels.trident.TimelineEngine$TridentAnimationThread.run(TimelineEngine.java:172)

"AWT-Windows@30083524232" daemon prio=6 tid=0x10 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.awt.windows.WToolkit.eventLoop(WToolkit.java:-1)
	  at sun.awt.windows.WToolkit.run(WToolkit.java:305)
	  at java.lang.Thread.run(Thread.java:834)

"AWT-Shutdown@30083533496" prio=5 tid=0xf nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:328)
	  at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:291)
	  at java.lang.Thread.run(Thread.java:834)

"Java2D Disposer@30083552320" daemon prio=10 tid=0xe nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	  at sun.java2d.Disposer.run(Disposer.java:144)
	  at java.lang.Thread.run(Thread.java:834)

"Finalizer@30083532320" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:170)

"Reference Handler@30083522320" daemon prio=10 tid=0x2 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.lang.ref.Reference.waitForReferencePendingList(Reference.java:-1)
	  at java.lang.ref.Reference.processPendingReferences(Reference.java:241)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:213)

"DestroyJavaVM@30083534192" prio=5 tid=0x15 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Attach Listener@30083522928" daemon prio=5 tid=0x5 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

"Signal Dispatcher@30083542320" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
```

**Comment by RoiEXLab** [comment]
Luckily this seems to be no longer the case. Something during development of the de-duplication code added a check. FYI @DanVanAtta

**Comment by RoiEXLab** [comment]
@DanVanAtta Do you remember why you reopened this ticket in august?

**Comment by DanVanAtta** [comment]
I re-opened all 'stale' tickets and removed stalebot. It was just too unpopular..
