### ISSUE TITLE
Null Pointer Error in Fast AI

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#6365]
### How can the problem be recreated?

I was playing the Hearts of Iron 2: The Turning Tide: 1943 and receive a null pointer error

### Which Engine Version are you using? 
19041
[Hearts_of_Iron2.zip](https://github.com/triplea-game/triplea/files/4567658/Hearts_of_Iron2.zip)
[Hearts_of_Iron2.zip](https://github.com/triplea-game/triplea/files/4567662/Hearts_of_Iron2.zip)

**Comment by DanVanAtta** [comment]
@RogerCooper does the null pointer happen all the time? When does it happen? Do you have the stack trace / error message from it by any chance?

**Comment by RogerCooper** [comment]
It happens when the FastAI gets to the Italian turn. It happened with 2 different versions of the pre-release but not with the official release. I don't have the trace.

**Comment by DanVanAtta** [comment]
@RogerCooper thanks for the details. This sounds like an active problem, should it stay open?

**Comment by RogerCooper** [comment]
Yes. I closed in error.

**Comment by DanVanAtta** [comment]
Thank you for attaching the map zip, I was able to reproduce the error:
```
SEVERE: null
java.lang.NullPointerException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at games.strategy.engine.data.GameMap.getNeighbors(GameMap.java:136)
	at games.strategy.engine.data.GameMap.getNeighborsValidatingCanals(GameMap.java:245)
	at games.strategy.engine.data.RouteFinder.findRouteByCost(RouteFinder.java:75)
	at games.strategy.engine.data.RouteFinder.findRouteByCost(RouteFinder.java:47)
	at games.strategy.engine.data.GameMap.getRouteForUnits(GameMap.java:330)
	at games.strategy.triplea.ai.pro.util.ProBattleUtils.territoryHasLocalNavalSuperiority(ProBattleUtils.java:350)
	at games.strategy.triplea.ai.pro.ProPurchaseAi.prioritizeSeaTerritories(ProPurchaseAi.java:1434)
	at games.strategy.triplea.ai.pro.ProPurchaseAi.purchase(ProPurchaseAi.java:352)
	at games.strategy.triplea.ai.pro.AbstractProAi.purchase(AbstractProAi.java:244)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:507)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:538)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:408)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:34)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:16)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at games.strategy.triplea.delegate.MoveValidator.checkCanalStepAndOwnership(MoveValidator.java:1538)
	at games.strategy.triplea.delegate.MoveValidator.canAnyPassThroughCanal(MoveValidator.java:1526)
	at games.strategy.triplea.delegate.MoveValidator.canAnyUnitsPassCanal(MoveValidator.java:355)
	at games.strategy.engine.data.GameMap.lambda$getNeighborsValidatingCanals$5(GameMap.java:250)
	at java.base/java.util.function.Predicate.lambda$and$0(Predicate.java:69)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)
	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by DanVanAtta** [comment]
With the updates in: https://github.com/triplea-game/triplea/pull/6383, was able to get past the NPE error.
