### ISSUE TITLE
Errors Launching Game - Java

### ISSUE THREAD

**Issue by bettyledbetter52** [triplea-game/triplea#6418]
Any help would be greatly appreciated.  Haven't been able to find an answer anywhere else on the web.  These are the errors I'm getting when trying to run the game:
```
May 06, 2020 12:03:26 PM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: com/sun/imageio/plugins/common/SubImageInputStream
java.lang.NoClassDefFoundError: com/sun/imageio/plugins/common/SubImageInputStream
	at com.sun.imageio.plugins.png.PNGImageDataEnumeration.nextElement(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageDataEnumeration.nextElement(Unknown Source)
	at java.io.SequenceInputStream.nextStream(Unknown Source)
	at java.io.SequenceInputStream.<init>(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
	at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at javax.imageio.ImageIO.read(Unknown Source)
	at games.strategy.engine.chat.ChatPlayerPanel.<clinit>(ChatPlayerPanel.java:50)
	at games.strategy.engine.lobby.client.ui.LobbyFrame.<init>(LobbyFrame.java:67)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.connectToLobby(MetaSetupPanel.java:148)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.lambda$setupListeners$6(MetaSetupPanel.java:125)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

May 06, 2020 12:14:17 PM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: Could not initialize class games.strategy.engine.chat.ChatPlayerPanel
java.lang.NoClassDefFoundError: Could not initialize class games.strategy.engine.chat.ChatPlayerPanel
	at games.strategy.engine.lobby.client.ui.LobbyFrame.<init>(LobbyFrame.java:67)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.connectToLobby(MetaSetupPanel.java:148)
	at games.strategy.engine.framework.startup.ui.MetaSetupPanel.lambda$setupListeners$6(MetaSetupPanel.java:125)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at org.pushingpixels.substance.internal.utils.RolloverButtonListener.mouseReleased(RolloverButtonListener.java:126)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by RoiEXLab** [comment]
@bettyledbetter52 That's a very odd issue to have, but it sound like there's something wrong with your installation of java.

Which operating system are you using, and how did you install TripleA on your machine?

**Comment by bettyledbetter52** [comment]
Using Windows 64; downloaded it from https://triplea-game.org/ version 1.9.0.0.13066.

I had TripleA on this PC 3 years ago, but uninstalled it a while back.  

My Java was just downloaded from Oracle: version 8.2510.8.

**Comment by RoiEXLab** [comment]
@bettyledbetter52 Hmm my best guess at that moment is that TripleA is not actually using the "correct" installation of java.
Could you try installing the latest pre-release? https://github.com/triplea-game/triplea/releases/tag/2.0.19225

We changed the way it installs java a little bit, so if my theory is correct, then you should be able to start the pre-release properly.
