### ISSUE TITLE
map errors

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#650]
should not be any map errors when loading the game with all maps

Next steps: better understand the errors, then see about bulk fixes

**Comment by RoiEXLab** [comment]
Related to #612

**Comment by DanVanAtta** [comment]
Looks like most errors were maps that had not had the 'attatch' -> 'attach' update applied properly. Hopefully all major issues should be fixed now with latest build after: https://github.com/triplea-game/triplea/pull/688

**Comment by RoiEXLab** [comment]
Found one:
```
Could not parse:jar:file:/C:/Users/Robin/triplea/downloadedMaps/big_world.zip!/games/Big_World_1942_v3rules.xml error at line:1 column:1
org.xml.sax.SAXParseException; systemId: file:/E:/GitHub/triplea/data/games/strategy/engine/xml/; lineNumber: 1; columnNumber: 1; Vorzeitiges Dateiende.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at games.strategy.engine.data.GameParser.getDocument(GameParser.java:275)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:83)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.<init>(NewGameChooserEntry.java:47)
	at games.strategy.engine.framework.ui.NewGameChooserModel.createEntry(NewGameChooserModel.java:214)
	at games.strategy.engine.framework.ui.NewGameChooserModel.addNewGameChooserEntry(NewGameChooserModel.java:187)
	at games.strategy.engine.framework.ui.NewGameChooserModel.processZipEntry(NewGameChooserModel.java:139)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populateFromZip(NewGameChooserModel.java:114)
	at games.strategy.engine.framework.ui.NewGameChooserModel.parseMapFiles(NewGameChooserModel.java:97)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populate(NewGameChooserModel.java:61)
	at games.strategy.engine.framework.ui.NewGameChooserModel.<init>(NewGameChooserModel.java:47)
	at games.strategy.engine.framework.ui.NewGameChooser.refreshNewGameChooserModel(NewGameChooser.java:218)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel$1.run(GameSelectorModel.java:327)
	at java.lang.Thread.run(Unknown Source)
Could not parse:jar:file:/C:/Users/Robin/triplea/downloadedMaps/big_world.zip!/games/big_world_1942.xml error at line:1 column:1
org.xml.sax.SAXParseException; systemId: file:/E:/GitHub/triplea/data/games/strategy/engine/xml/; lineNumber: 1; columnNumber: 1; Vorzeitiges Dateiende.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at javax.xml.parsers.DocumentBuilder.parse(Unknown Source)
	at games.strategy.engine.data.GameParser.getDocument(GameParser.java:275)
	at games.strategy.engine.data.GameParser.parse(GameParser.java:83)
	at games.strategy.engine.framework.ui.NewGameChooserEntry.<init>(NewGameChooserEntry.java:47)
	at games.strategy.engine.framework.ui.NewGameChooserModel.createEntry(NewGameChooserModel.java:214)
	at games.strategy.engine.framework.ui.NewGameChooserModel.addNewGameChooserEntry(NewGameChooserModel.java:187)
	at games.strategy.engine.framework.ui.NewGameChooserModel.processZipEntry(NewGameChooserModel.java:139)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populateFromZip(NewGameChooserModel.java:114)
	at games.strategy.engine.framework.ui.NewGameChooserModel.parseMapFiles(NewGameChooserModel.java:97)
	at games.strategy.engine.framework.ui.NewGameChooserModel.populate(NewGameChooserModel.java:61)
	at games.strategy.engine.framework.ui.NewGameChooserModel.<init>(NewGameChooserModel.java:47)
	at games.strategy.engine.framework.ui.NewGameChooser.refreshNewGameChooserModel(NewGameChooser.java:218)
	at games.strategy.engine.framework.startup.mc.GameSelectorModel$1.run(GameSelectorModel.java:327)
	at java.lang.Thread.run(Unknown Source)
```

Oh and "Vorzeitiges Dateiende" means too early end of file

**Comment by DanVanAtta** [comment]
Thanks for the report, sounds like I corrupted the XML, I'll take a look at the next chance I have.

**Comment by ZjelcoP** [comment]
Checked for some errors.
Downloaded all maps within 6 minutes! Great improvement!

Errors:

big_world_1939: keeps popping back in downloadlist.....

Attachment spelling issue:
-Capture the flag
-Invasion USA
-Large Middle Earth
-Red Sun Over China

**Comment by DanVanAtta** [comment]
3 different problems:
- middle earth did not have proper tokens set up for a build, so the release file was not updating
- big world lost it's xml file contents while being migrated
- the others were missed in name correction.

With some luck, should be now be fixed
