### ISSUE TITLE
Lobby Connection Timeout

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6631]
### How can the problem be recreated?

Joined prod2 lobby and left idle. Eventually saw a connection timeout.

### What is an expected fix?
1. Avoid the timeout
2. Perhaps reconnect automatically
3. If we cannot do any of the above, the lobby window should be closed.

### Which Engine Version are you using? 

commit 444bc0308429e405278a5faa39382ceda08ba68a
Date:   Sun Jun 7 13:15:57 2020 -0400

### (Optional) Additional information

Stack trace after the connection timeout and then tried to do a lobby chat message:
```
SEVERE: Failed to send text.
java.io.IOException: Output closed
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.tryCompleteWrite(TransportImpl.java:609)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl$SendTask.run(TransportImpl.java:547)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
	at java.net.http/jdk.internal.net.http.websocket.TransportImpl.sendText(TransportImpl.java:149)
	at java.net.http/jdk.internal.net.http.websocket.WebSocketImpl.sendText(WebSocketImpl.java:184)
	at org.triplea.http.client.web.socket.WebSocketConnection.sendMessage(WebSocketConnection.java:167)
	at org.triplea.http.client.web.socket.GenericWebSocketClient.sendMessage(GenericWebSocketClient.java:101)
	at org.triplea.http.client.web.socket.client.connections.PlayerToLobbyConnection.sendChatMessage(PlayerToLobbyConnection.java:80)
	at games.strategy.engine.chat.LobbyChatTransmitter.sendMessage(LobbyChatTransmitter.java:78)
	at games.strategy.engine.chat.Chat.sendMessage(Chat.java:161)
	at games.strategy.engine.chat.ChatMessagePanel.sendMessage(ChatMessagePanel.java:348)
	at org.triplea.swing.key.binding.SwingKeyBinding.lambda$addKeyMapping$1(SwingKeyBinding.java:105)
	at org.triplea.swing.SwingAction$2.actionPerformed(SwingAction.java:84)
```

**Comment by DanVanAtta** [comment]
Potentially fixed with: https://github.com/triplea-game/triplea/pull/6648

I strongly suspect this was a one-time failure sending websocket pings. The PR adds a few retries to the ping send.
