### ISSUE TITLE
2.0 Bots are Running out of Memory (Map Parsing Related)

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#6632]
Bots are exhausting heap space on launch. Looking at the stack trace below it looks to be map related. The way map XMLs are structured perhaps have hit a breaking point for data storage inefficiency : (

In the short term we need to determine which map is triggering this and exclude it from bots until we determine a way to fix the root cause.

```
Jun 07 21:04:05 li1116-193 systemd[1]: Started TripleA Bot 01.
Jun 07 21:08:22 li1116-193 run_server[324823]: Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.HashMap.newNode(HashMap.java:1797)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.HashMap.putVal(HashMap.java:637)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.HashMap.put(HashMap.java:607)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.HashSet.add(HashSet.java:220)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.triplea.attachments.TriggerAttachment.getTriggers(TriggerAttachment.java:187)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.triplea.attachments.TriggerAttachment.setActivateTrigger(TriggerAttachment.java:358)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.triplea.attachments.TriggerAttachment$$Lambda$1148/0x0000000840235c40.accept(Unknown Source)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.MutableProperty.setStringValue(MutableProperty.java:58)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.MutableProperty.setValue(MutableProperty.java:85)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.setOptions(GameParser.java:1383)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parseAttachment(GameParser.java:1323)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parseAttachments(GameParser.java:1237)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parseMapDetails(GameParser.java:213)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parse(GameParser.java:107)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parse(GameParser.java:99)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at games.strategy.engine.data.GameParser.parse(GameParser.java:85)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at org.triplea.game.server.AvailableGames.addToAvailableGames(AvailableGames.java:124)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at org.triplea.game.server.AvailableGames.populateFromZip(AvailableGames.java:103)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at org.triplea.game.server.AvailableGames.lambda$newGameRepository$0(AvailableGames.java:66)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at org.triplea.game.server.AvailableGames$$Lambda$43/0x0000000840092440.accept(Unknown Source)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
Jun 07 21:08:22 li1116-193 run_server[324823]:         at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
```

### How can the problem be recreated?

- Download all maps for a bot
- Start the bot, notice eventually it can hit the OOM

**Comment by RoiEXLab** [comment]
:/

**Comment by DanVanAtta** [comment]
It looks like #6634 did the trick. All 4 of the prod2 bot servers are now connected to the lobby, no OOM errors.
