### ISSUE TITLE
Install4jerror

### ISSUE THREAD

**Issue by ZjelcoP** [triplea-game/triplea#6760]
Ran into this error during installation.
TripleA seems to run fine though afterwards.
Did no further testing.
Win 10

### How can the problem be recreated?
Was installing 2.0.20183. Chose update installation.

### Do you have any ideas for an expected fix?
no
install4jError11294526928122257143

Exception:

java.lang.RuntimeException: java.io.IOException: write failed
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeOther(HelperCommunication.java:323)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeActionInt(HelperCommunication.java:262)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeAction(HelperCommunication.java:223)
	at com.install4j.runtime.installer.helper.fileinst.FileInstallerState.setRollbackIds(FileInstallerState.java:84)
	at com.install4j.runtime.installer.helper.fileinst.FileInstaller.setCurrentAction(FileInstaller.java:528)
	at com.install4j.runtime.installer.ContextImpl.performAction(ContextImpl.java:1143)
	at com.install4j.runtime.installer.controller.Controller.executeAction(Controller.java:399)
	at com.install4j.runtime.installer.controller.Controller.executeActions(Controller.java:365)
	at com.install4j.runtime.installer.controller.Controller.handleCommand(Controller.java:222)
	at com.install4j.runtime.installer.controller.Controller.start(Controller.java:121)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:57)
	at com.install4j.runtime.installer.Installer.main(Installer.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.io.IOException: write failed
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.sendObject(HelperCommunication.java:506)
	at com.install4j.runtime.installer.helper.comm.HelperCommunication.executeOther(HelperCommunication.java:286)
	... 18 more

System properties:

sun.desktop=windows
awt.toolkit=sun.awt.windows.WToolkit
java.specification.version=11
sun.cpu.isalist=amd64
sun.jnu.encoding=Cp1252
java.class.path=C:\Users\jelle\AppData\Local\Temp\e4j185.tmp_dir1592902540\i4jruntime.jar;C:\Users\jelle\AppData\Local\Temp\e4j185.tmp_dir1592902540\user.jar
sun.awt.enableExtraMouseButtons=true
java.vm.vendor=AdoptOpenJDK
sun.arch.data.model=64
install4j.exeDir=C:\Users\jelle\Downloads\
user.variant=
java.vendor.url=https://adoptopenjdk.net/
install4j.systemLanguage=nl
user.timezone=Europe/Berlin
os.name=Windows 10
java.vm.specification.version=11
user.country=NL
sun.boot.library.path=c:\users\jelle\appdata\local\temp\e4j185.tmp_dir1592902540\jre\bin
sun.java.command=C:\Users\jelle\Downloads\TripleA_2.0.20183_windows-64bit.exe
jdk.debug=release
sun.cpu.endian=little
user.home=C:\Users\jelle
exe4j.unextractedPosition=52429697
user.language=nl
java.specification.vendor=Oracle Corporation
java.version.date=2020-01-14
java.home=c:\users\jelle\appdata\local\temp\e4j185.tmp_dir1592902540\jre
file.separator=\
line.separator=

java.specification.name=Java Platform API Specification
java.vm.specification.vendor=Oracle Corporation
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
exe4j.moduleName=C:\Users\jelle\Downloads\TripleA_2.0.20183_windows-64bit.exe
exe4j.tempDir=C:\Users\jelle\AppData\Local\Temp\e4j185.tmp_dir1592902540
user.script=
exe4j.consoleCodepage=cp0
sun.management.compiler=HotSpot 64-Bit Client Compiler
exe4j.isInstall4j=true
java.runtime.version=11.0.6+10
user.name=jelle
path.separator=;
os.version=10.0
java.runtime.name=OpenJDK Runtime Environment
sun.java2d.noddraw=true
file.encoding=Cp1252
java.vm.name=OpenJDK 64-Bit Client VM
java.vendor.version=AdoptOpenJDK
exe4j.semaphoreName=Local\c:_users_jelle_downloads_triplea_2.0.20183_windows-64bit.exe
install4j.appDir=C:\Users\jelle\AppData\Local\Temp\
java.vendor.url.bug=https://github.com/AdoptOpenJDK/openjdk-support/issues
java.io.tmpdir=C:\Users\jelle\AppData\Local\Temp\
java.version=11.0.6
user.dir=C:\Users\jelle\AppData\Local\Temp\e4j185.tmp_dir1592902540
os.arch=amd64
java.vm.specification.name=Java Virtual Machine Specification
java.awt.printerjob=sun.awt.windows.WPrinterJob
sun.os.patch.level=
java.library.path=c:\users\jelle\appdata\local\temp\e4j185.tmp_dir1592902540\jre\bin;C:\Users\jelle\AppData\Local\Temp\e4j185.tmp_dir1592902540\user;C:\Program Files\Mozilla Firefox;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\jelle\AppData\Local\Microsoft\WindowsApps;
java.vendor=AdoptOpenJDK
java.vm.info=mixed mode
java.vm.version=11.0.6+10
jdk.gtk.version=2
sun.io.unicode.encoding=UnicodeLittle
java.class.version=55.0
exe4j.launchName=C:\Users\jelle\Downloads\TripleA_2.0.20183_windows-64bit.exe

**Comment by RoiEXLab** [comment]
tbh I don't think there's somethng we can do about this.
My best guess is that there's some sort of permission problem here

**Comment by ZjelcoP** [comment]
Okay, fine if you close it, will update if it ever happens again.

**Comment by RoiEXLab** [comment]
Hmm perhaps we want to report this to Install4j?
