### ISSUE TITLE
Bug in turn 8 of the TripleA axis&allies game

### ISSUE THREAD

**Issue by FrankManders** [triplea-game/triplea#7196]
I experience a reocurring bug in this game. aftercompleting turn8 for the british forces the game crashes while trying to decide the actions for the italians (level hard, axis is computer, allies is me)

here the error message:
Jul 18, 2020 11:07:51 AM games.strategy.engine.framework.GameRunner lambda$start$0
SEVERE: null
java.lang.NullPointerException
	at games.strategy.triplea.delegate.TransportTracker.isTransporting(TransportTracker.java:92)
	at games.strategy.triplea.ai.pro.data.ProTerritory.putAmphibAttackMap(ProTerritory.java:241)
	at games.strategy.triplea.ai.pro.simulate.ProSimulateTurnUtils.transferMoveMap(ProSimulateTurnUtils.java:129)
	at games.strategy.triplea.ai.pro.ProAi.purchase(ProAi.java:230)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:457)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:529)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:423)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:290)
	at java.util.Optional.ifPresent(Unknown Source)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:41)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$0(AbstractLauncher.java:51)
	at java.lang.Thread.run(Unknown Source)

hope this helps you in improving the game.

regards
Frank

**Comment by beelee1** [comment]
Which game are you playing ?
