### ISSUE TITLE
v2.3.22161  Should not be possible to have a normal battle in: Sea Zone 15 and have abandoned or only bombing there too.

### ISSUE THREAD

**Issue by TheDog-GH** [triplea-game/triplea#7992]
I have converted the Age of Tribes map and put my 9 fantasy armies in it, this was working well under 1.9

In 2.3.2 it crashes when air units attack sea units with transported land units. (Go to Italy)

In 2.3.2 Air **v** Sea only, does not crash
In 2.3.2 Air+Sea units **v** Sea+Land, does not crash

Attached are two files, the save game and the map zipped.

2.3.22161: BattleDelegate#setupTerritoriesAbandonedToTheEnemy:669 - java.lang.IllegalStateException

## Map
settlers_age_of_tribes

## Log Message
Should not be possible to have a normal battle in: Sea Zone 15 and have abandoned or only bombing there too.

## TripleA Version
2.3.22161

## Java Version
11.0.6

## Operating System
Windows 10

## Memory
Heap utilization statistics [MB]
Used Memory: 168
Free memory: 1811
Total memory: 1979
Max memory: 1979

## Stack Trace
```
Exception: java.lang.IllegalStateExceptionShould not be possible to have a normal battle in: Sea Zone 15 and have abandoned or only bombing there too.
java.lang.Exception
	at games.strategy.triplea.delegate.battle.BattleDelegate.setupTerritoriesAbandonedToTheEnemy(BattleDelegate.java:669)
	at games.strategy.triplea.delegate.battle.BattleDelegate.doInitialize(BattleDelegate.java:206)
	at games.strategy.triplea.delegate.battle.BattleDelegate.start(BattleDelegate.java:87)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:519)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:398)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:82)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.lambda$launch$0(LocalLauncher.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

[autosaveAfterOrcsCombatMove.zip](https://github.com/triplea-game/triplea/files/5460196/autosaveAfterOrcsCombatMove.zip)
[settlers_age_of_tribes.zip](https://github.com/triplea-game/triplea/files/5460209/settlers_age_of_tribes.zip)

**Comment by TheDog-GH** [comment]
This is fixed by making this property false.
Please Close


        <property name="Abandoned Territories May Be Taken Over Immediately" value="**false**" editable="false">
            <boolean/>
        </property>
