### ISSUE TITLE
Feb. 06, 2021 10:58:00 A.M. org.triplea.game.client.HeadedGameRunner

### ISSUE THREAD

**Issue by Sloshpit** [triplea-game/triplea#8793]
Hello,
I have tried to reinstall TripleA, updated Java on Big Sur, but I get the following error when I try to post to the forum via the TripleA App.  Please see the error below:
Feb. 06, 2021 10:57:50 A.M. org.triplea.game.client.HeadedGameRunner lambda$initializeClientSettingAndLogging$0
SEVERE: User Sloshpit doesn't exist.
java.lang.IllegalStateException: User Sloshpit doesn't exist.
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.checkUser(NodeBbTokenGenerator.java:102)
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.getUserId(NodeBbTokenGenerator.java:96)
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.generateToken(NodeBbTokenGenerator.java:63)
	at games.strategy.engine.framework.startup.ui.posted.game.pbf.ForumPosterEditorViewModel.renewToken(ForumPosterEditorViewModel.java:92)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:108)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Feb. 06, 2021 10:58:00 A.M. org.triplea.game.client.HeadedGameRunner lambda$initializeClientSettingAndLogging$0
SEVERE: User Sloshpit doesn't exist.
java.lang.IllegalStateException: User Sloshpit doesn't exist.
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.checkUser(NodeBbTokenGenerator.java:102)
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.getUserId(NodeBbTokenGenerator.java:96)
	at games.strategy.engine.posted.game.pbf.NodeBbTokenGenerator.generateToken(NodeBbTokenGenerator.java:63)
	at games.strategy.engine.framework.startup.ui.posted.game.pbf.ForumPosterEditorViewModel.renewToken(ForumPosterEditorViewModel.java:92)
	at games.strategy.engine.framework.ui.background.BackgroundTaskRunner$1.doInBackground(BackgroundTaskRunner.java:108)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I can confirm that my user exists.  I also reinstalled the app a few times.  I have tried this on multiple MACs as well.  I also tried a new user with no luck.

Thanks for looking into this!

**Comment by DanVanAtta** [comment]
@Sloshpit , I do see a new forum user named "Sloshpit31", perhaps that is the name you need to use?

**Comment by Sloshpit** [comment]
Hi Dan
I tried both and I am still experiencing the issue. Is there a way to
totally uninstall TripleA on osx including any cached credentials etc?

Thanks!
Neel

**Comment by doctored** [comment]
@Sloshpit that wont work i've tried that.

**Comment by tanderegg** [comment]
@DanVanAtta FYI, myself and a friend are both having this problem as well, he's on Windows and I'm on Linux.  Both of our user accounts are new as of this last weekend, while the other folks we are playing with have had accounts for a long time.  Not sure if that is the cause, but wanted to provide additional info.

**Comment by doctored** [comment]
anything else we can do to help with this?

**Comment by tanderegg** [comment]
Have you tried recently?  I think there was a misconfiguration on the TripleA forum that caused this, which has been fixed.

**Comment by doctored** [comment]
yup:

https://forums.triplea-game.org/post/48597

**Comment by doctored** [comment]
are we planning to fix this? haven't been able to play against humans since 2.0 :(

**Comment by Sloshpit** [comment]
> are we planning to fix this? haven't been able to play against humans since 2.0 :(

Same here. We have had to upload our files manually to the forum to share or use the email method. Would be awesome to be able to post again and be logged in correctly.

**Comment by doctored** [comment]
are we still working on this or has it been fixed in the newest unstable?
