### ISSUE TITLE
serious error in Big world Balance of power

### ISSUE THREAD

**Issue by MississippiKid1** [triplea-game/triplea#8842]
Bot102_Dallas:  Feb 12, 2021 1:24:48 AM games.strategy.engine.framework.startup.launcher.ServerLauncher launchInternal
Bot102_Dallas:  SEVERE: Unrecognized error occurred. If this is a repeatable error, please make a copy of this savegame and report to:
Bot102_Dallas:  https://github.com/triplea-game/triplea/issues/new
Bot102_Dallas:  java.lang.NullPointerException: territoryEffects is marked non-null but is null
Bot102_Dallas:  	at games.strategy.triplea.delegate.power.calculator.MainOffenseCombatValue$MainOffenseCombatValueBuilder.territoryEffects(MainOffenseCombatValue.java:26)
Bot102_Dallas:  	at games.strategy.triplea.delegate.power.calculator.CombatValue.buildMainCombatValue(CombatValue.java:57)
Bot102_Dallas:  	at games.strategy.triplea.delegate.power.calculator.TotalPowerAndTotalRolls.getUnitPowerAndRollsForNormalBattles(TotalPowerAndTotalRolls.java:383)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.casualty.CasualtyOrderOfLosses.sortUnitsForCasualtiesWithSupport(CasualtyOrderOfLosses.java:108)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.getDefaultCasualties(CasualtySelector.java:295)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.casualty.CasualtySelector.selectCasualties(CasualtySelector.java:118)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.AirBattle$DefendersFire$2.execute(AirBattle.java:764)
Bot102_Dallas:  	at games.strategy.triplea.delegate.ExecutionStack.execute(ExecutionStack.java:34)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.AirBattle.fight(AirBattle.java:123)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1342)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.BattleTracker.fightAirRaidsAndStrategicBombing(BattleTracker.java:1323)
Bot102_Dallas:  	at games.strategy.triplea.delegate.battle.BattleDelegate.start(BattleDelegate.java:113)
Bot102_Dallas:  	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:519)
Bot102_Dallas:  	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:398)
Bot102_Dallas:  	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
Bot102_Dallas:  	at games.strategy.engine.framework.startup.launcher.ServerLauncher.launchInternal(ServerLauncher.java:173)

**Comment by asvitkine** [comment]
Dupe of [8189](https://github.com/triplea-game/triplea/issues/8189)
