### ISSUE TITLE
Forum Stability/Availability Issues

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#8916]
- Seems to have locked up a week ago. Restarted server.
- Few days later was observing a lot of 503s, restarted again.
- Couple days ago got 504, restarted server.
- Again seeing 504.

**Comment by DanVanAtta** [comment]
Interestingly, `ps -ef` hangs after listing the nodebb process:

```
mongodb    833     1  0 Feb25 ?        00:08:12 /usr/bin/mongod --config /etc/mo
root       838     1  0 Feb25 ?        00:00:00 /usr/bin/python3 /usr/share/unat
root       847     1  0 Feb25 ?        00:00:02 /usr/sbin/sshd -D
root       849     1  0 Feb25 tty1     00:00:00 /sbin/agetty --noclear tty1 linu
root       851     1  0 Feb25 ttyS0    00:00:00 /sbin/agetty --keep-baud 115200 
root       855     1  0 Feb25 ?        00:00:00 nginx: master process /usr/sbin/
www-data   856   855  0 Feb25 ?        00:05:11 nginx: worker process
root       861     1  4 Feb25 ?        01:11:01 /usr/bin/python3 /usr/bin/fail2b
nodebb     898     1  0 Feb25 ?        00:00:00 /usr/bin/node loader.js --no-dae
```

**Comment by DanVanAtta** [comment]
Memory seems perhaps okay:
```
admin@forums:~$ free -m
              total        used        free      shared  buff/cache   available
Mem:            959         278          72           0         609         479
```
`htop` freezes, likely because it is trying to get process info.

System load is not extreme per-say, but is greater than 1:
```
admin@forums:~$ uptime
 02:46:13 up 1 day,  2:33,  2 users,  load average: 2.96, 2.48, 2.20
```


Of some interest, seeing this in the recent log:
```
Feb 25 00:13:18 forums.triplea-game.org nodebb[898]: 2021-02-25T00:13:18.289Z [4567/914] - warn: [plugins/nodebb-plugin-write-api] Hook "filter:router.page" is deprecated, please use "response:router.page" instead.
Feb 25 00:13:18 forums.triplea-game.org nodebb[898]: 2021-02-25T00:13:18.292Z [4567/914] - warn: [plugins/load] The following plugins may not be compatible with your version of NodeBB. This may cause unintended behaviour or crashing. In the event of an unresponsive NodeBB caused by this plugin, run `./nodebb reset -p PLUGINNAME` to disable it.
Feb 25 00:13:18 forums.triplea-game.org nodebb[898]:   * nodebb-plugin-ns-login
Feb 25 00:13:18 forums.triplea-game.org nodebb[898]:   * nodebb-plugin-ns-embed
Feb 25 23:56:37 forums.triplea-game.org nodebb[898]: 2021-02-25T23:56:37.848Z [4567/914] - warn: [plugins/github-embed] Received HTTP 403 from GitHub (triplea-game/triplea#1743)
Feb 25 23:56:59 forums.triplea-game.org nodebb[898]: 2021-02-25T23:56:59.081Z [4567/914] - warn: [plugins/github-embed] Received HTTP 403 from GitHub (triplea-game/triplea#4322)
Feb 25 23:57:36 forums.triplea-game.org nodebb[898]: 2021-02-25T23:57:36.660Z [4567/914] - warn: [plugins/github-embed] Received HTTP 403 from GitHub (triplea-maps/game_of_thrones#3)
Feb 26 00:00:10 forums.triplea-game.org nodebb[898]: 2021-02-26T00:00:10.868Z [4567/914] - info: [user/jobs] Digest (day) scheduling completed. Sending emails; this may take some time...
Feb 26 00:00:14 forums.triplea-game.org nodebb[898]: 2021-02-26T00:00:14.504Z [4567/914] - info: [user/jobs] Digest (day) sending completed. 5 emails sent.
Feb 26 00:00:14 forums.triplea-game.org nodebb[898]: 2021-02-26T00:00:14.504Z [4567/914] - info: [user/jobs] Digest (day) complete.
```

**Comment by DanVanAtta** [comment]
```
admin@forums:/opt/nodebb$ ./nodebb reset -p nodebb-plugin-ns-embed
```
> 2021-02-26T02:51:04.246Z [4567/26592] - info: [reset] Plugin `nodebb-plugin-ns-embed` disabled
2021-02-26T02:51:04.247Z [4567/26592] - info: [reset] Reset complete. Please run `./nodebb build` to rebuild assets.

```
admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb build
```

>  started
2021-02-26T02:51:41.377Z [4567/26636] - info: [build] Building in series mode
2021-02-26T02:51:41.379Z [4567/26636] - info: [build]         plugin static dirs  build started
2021-02-26T02:51:41.396Z [4567/26636] - info: [build]         plugin static dirs  build completed in 0.017sec
2021-02-26T02:51:41.397Z [4567/26636] - info: [build]          requirejs modules  build started
2021-02-26T02:51:47.822Z [4567/26636] - info: [build]          requirejs modules  build completed in 6.425sec
2021-02-26T02:51:47.822Z [4567/26636] - info: [build]           client js bundle  build started
2021-02-26T02:51:51.175Z [4567/26636] - info: [build]           client js bundle  build completed in 3.353sec
2021-02-26T02:51:51.176Z [4567/26636] - info: [build]            admin js bundle  build started
2021-02-26T02:51:53.750Z [4567/26636] - info: [build]            admin js bundle  build completed in 2.574sec
2021-02-26T02:51:53.751Z [4567/26636] - info: [build]         client side styles  build started
2021-02-26T02:52:02.982Z [4567/26636] - info: [build]         client side styles  build completed in 9.231sec
2021-02-26T02:52:02.982Z [4567/26636] - info: [build] admin control panel styles  build started
2021-02-26T02:52:11.032Z [4567/26636] - info: [build] admin control panel styles  build completed in 8.049sec
2021-02-26T02:52:11.033Z [4567/26636] - info: [build]                  templates  build started
2021-02-26T02:52:11.903Z [4567/26636] - info: [build]                  templates  build completed in 0.869sec
2021-02-26T02:52:11.903Z [4567/26636] - info: [build]                  languages  build started
2021-02-26T02:52:55.916Z [4567/26636] - info: [build]                  languages  build completed in 43.997sec
2021-02-26T02:52:55.961Z [4567/26636] - info: [build] Asset compilation successful. Completed in 74.557sec.


```
admin@forums:/opt/nodebb$ ./nodebb reset -p nodebb-plugin-ns-login

```

> 2021-02-26T02:54:03.664Z [4567/26665] - info: [reset] Plugin `nodebb-plugin-ns-login` disabled
2021-02-26T02:54:03.665Z [4567/26665] - info: [reset] Reset complete. Please run `./nodebb build` to rebuild assets.


```
admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb build
```
>  started
2021-02-26T02:54:20.246Z [4567/26687] - info: [build] Building in series mode
2021-02-26T02:54:20.248Z [4567/26687] - info: [build]         plugin static dirs  build started
2021-02-26T02:54:20.264Z [4567/26687] - info: [build]         plugin static dirs  build completed in 0.016sec
2021-02-26T02:54:20.264Z [4567/26687] - info: [build]          requirejs modules  build started
2021-02-26T02:54:26.600Z [4567/26687] - info: [build]          requirejs modules  build completed in 6.336sec
2021-02-26T02:54:26.601Z [4567/26687] - info: [build]           client js bundle  build started
2021-02-26T02:54:31.736Z [4567/26687] - info: [build]           client js bundle  build completed in 5.135sec
2021-02-26T02:54:31.736Z [4567/26687] - info: [build]            admin js bundle  build started
2021-02-26T02:54:35.931Z [4567/26687] - info: [build]            admin js bundle  build completed in 4.194sec
2021-02-26T02:54:35.931Z [4567/26687] - info: [build]         client side styles  build started
2021-02-26T02:54:44.775Z [4567/26687] - info: [build]         client side styles  build completed in 8.844sec
2021-02-26T02:54:44.776Z [4567/26687] - info: [build] admin control panel styles  build started
2021-02-26T02:54:55.951Z [4567/26687] - info: [build] admin control panel styles  build completed in 11.17sec
2021-02-26T02:54:55.954Z [4567/26687] - info: [build]                  templates  build started
2021-02-26T02:55:00.154Z [4567/26687] - info: [build]                  templates  build completed in 4.198sec
2021-02-26T02:55:00.157Z [4567/26687] - info: [build]                  languages  build started
2021-02-26T02:55:35.797Z [4567/26687] - info: [build]                  languages  build completed in 35.628sec
2021-02-26T02:55:35.826Z [4567/26687] - info: [build] Asset compilation successful. Completed in 75.567sec.


```
admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb stop
admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb start
admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb log
```

> 2021-02-26T03:00:44.880Z [4567/26948] - error: Error: Cannot find module 'templates.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-widget-user-subset/library.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)



```
admin@forums:/opt/nodebb$ ls node_modules/ | grep "^te"
textarea-caret
textcomplete
textcomplete.contenteditable
text-extensions
text-hex
text-table




sudo rm -rf node_modules
sudo npm install

admin@forums:/opt/nodebb$ sudo npm install colors -g

added 1 package, and audited 2 packages in 1s

found 0 vulnerabilities


```

> 2021-02-26T03:08:26.707Z [4567/27417] - info: Initializing NodeBB v1.16.2 https://forums.triplea-game.org
2021-02-26T03:08:30.378Z [4567/27417] - info: [socket.io] Restricting access to origin: https://forums.triplea-game.org:*
2021-02-26T03:08:30.764Z [4567/27417] - warn:    [plugins/nodebb-plugin-spam-be-gone] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2021-02-26T03:08:30.847Z [4567/27417] - warn: [plugins/nodebb-plugin-2factor] Hook "filter:router.page" is deprecated, please use "response:router.page" instead.
2021-02-26T03:08:31.153Z [4567/27417] - warn:    [plugins/nodebb-widget-user-subset] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.
2021-02-26T03:08:31.160Z [4567/27417] - warn: [plugins] Unable to load library for: nodebb-widget-user-subset
2021-02-26T03:08:31.162Z [4567/27417] - error: Error: Cannot find module 'templates.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at Object.<anonymous> (/opt/nodebb/node_modules/nodebb-widget-user-subset/library.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
2021-02-26T03:08:31.227Z [4567/27417] - warn:    [plugins/nodebb-plugin-user-invitations] The plugin.json field "library" is deprecated. Please use the package.json field "main" instead.



2021-02-26T03:08:31.436Z [4567/27417] - warn: [plugins/nodebb-plugin-write-api] Hook "filter:router.page" is deprecated, please use "response:router.page" instead.
2021-02-26T03:08:31.500Z [4567/27417] - info: [Newsletter] Initializing Newsletter...
2021-02-26T03:08:31.649Z [4567/27417] - info: [plugins/spam-be-gone] Settings loaded
2021-02-26T03:08:35.481Z [4567/27417] - info: [api] Adding 0 route(s) to `api/v3/plugins`
2021-02-26T03:08:35.502Z [4567/27417] - info: Routes added
2021-02-26T03:08:35.520Z [4567/27417] - info: NodeBB Ready
2021-02-26T03:08:35.522Z [4567/27417] - info: Enabling 'trust proxy'
2021-02-26T03:08:35.526Z [4567/27417] - error: NodeBB address in use, exiting...
Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2021-02-26T03:08:35.530Z [4567/27417] - error: uncaughtException: listen EADDRINUSE: address already in use 0.0.0.0:4567
Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19) {"error":{"code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","address":"0.0.0.0","port":4567},"stack":"Error: listen EADDRINUSE: address already in use 0.0.0.0:4567\n    at Server.setupListenHandle [as _listen2] (net.js:1280:14)\n    at listenInCluster (net.js:1328:12)\n    at doListen (net.js:1461:7)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","exception":true,"date":"Fri Feb 26 2021 03:08:35 GMT+0000 (Coordinated Universal Time)","process":{"pid":27417,"uid":110,"gid":117,"cwd":"/opt/nodebb","execPath":"/usr/bin/node","version":"v10.23.1","argv":["/usr/bin/node","/opt/nodebb/app.js"],"memoryUsage":{"rss":317014016,"heapTotal":180092928,"heapUsed":144808048,"external":106505298}},"os":{"loadavg":[8.890625,6.6044921875,4.8154296875],"uptime":96937},"trace":[{"column":14,"file":"net.js","function":"Server.setupListenHandle [as _listen2]","line":1280,"method":"setupListenHandle [as _listen2]","native":false},{"column":12,"file":"net.js","function":"listenInCluster","line":1328,"method":null,"native":false},{"column":7,"file":"net.js","function":"doListen","line":1461,"method":null,"native":false},{"column":19,"file":"internal/process/next_tick.js","function":"process._tickCallback","line":63,"method":"_tickCallback","native":false}]}
2021-02-26T03:08:35.531Z [4567/27417] - error: Error: listen EADDRINUSE: address already in use 0.0.0.0:4567
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at doListen (net.js:1461:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
2021-02-26T03:08:35.532Z [4567/27417] - info: [app] Shutdown (SIGTERM/SIGINT) Initialised.
2021-02-26T03:08:35.534Z [4567/27417] - error: Error [ERR_SERVER_NOT_RUNNING]: Server is not running.
    at Server.close (net.js:1566:12)
    at Object.onceWrapper (events.js:286:20)
    at Server.emit (events.js:203:15)
    at emitCloseNT (net.js:1619:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
3 restarts in 10 seconds, most likely an error on startup. Halting.

admin@forums:/opt/nodebb$ sudo -u nodebb ./nodebb start
Dependencies outdated or not yet installed.
Installing them now...


up to date, audited 1030 packages in 4s

1 package is looking for funding
  run `npm fund` for details

8 vulnerabilities (1 low, 1 moderate, 6 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/nodebb/src/cli/index.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by DanVanAtta** [comment]
Was able to find the colors module under `/usr/lib/node_modules` and copied it into the `node_modules` folder of `/opt/nodebb`. Then on startup a different module threw an error, in this case the module folder for in `/opt/nodebb/node_modules` was empty. Deleting that and trying to start seemed to install it but then another module had a problem and so on.

```
sudo cp -r /usr/lib/node_modules/colors/ node_modules/

sudo npm install nconf -g

admin@forums:/opt/nodebb$ sudo cp -r /usr/lib/node_modules/nconf/ ./node_modules/


admin@forums:/opt/nodebb$ ls -ltra node_modules/commander/
total 44
drwxr-xr-x   2 nodebb nodebb  4096 Feb 26 03:33 .
drwxr-xr-x 705 nodebb nodebb 36864 Feb 26 03:48 ..



Error: Cannot find module 'yargs'
    at Function.Module._resolveFilenam
    e (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/nodebb/src/cli/index.js:74:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
admin@forums:/opt/nodebb$ sudo ls node_modules/yargs
node_modules
admin@forums:/opt/nodebb$ sudo ls node_modules/yargs/
node_modules
admin@forums:/opt/nodebb$ sudo ls node_modules/yargs/node_modules/yargs-parser/
browser.js    build/        CHANGELOG.md  LICENSE.txt   package.json  README.md     
admin@forums:/opt/nodebb$ sudo rm -rf  node_modules/yargs/
```

**Comment by DanVanAtta** [comment]
Just restored the linode from backup, unfortunately it looks like we are back to the same borked state. The previous backup to the most recent looks to be a week prior : |
It looks like we essentially need node bb completely re-installed, if we can keep the mongodb then we would maintain data at least..

**Comment by DanVanAtta** [comment]
I'm hanging it up for the night.

@RoiEXLab , ball is yours if you can make some magic happen here.

**Comment by beelee1** [comment]
yea I've noticed not being able to get on several times the last few weeks as well. It seems some of yesterdays posts were deleted on the forum. At any rate, Good Luck Guys : )

**Comment by DanVanAtta** [comment]
available again, @RoiEXLab , was that you?

**Comment by RoiEXLab** [comment]
@DanVanAtta Well I booted the system after you restored the backup, and it seems to run fine so far, but I didn't really change anything

**Comment by DanVanAtta** [comment]
Problem mitigated. Closing for now..
