### ISSUE TITLE
Can't start TripleA

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#8955]
### Reproduction Steps

Not sure if this can be reproduced. I see this prompt when I launch TripleA, and it doesn't start. Report to TripleA does not bring up a screen. Clicking it just brings up the same prompt over and over again. O.K. Produces a TripleA process with no windows that I have to kill in the task manager on Windows 10.

![2021-03-01 19_07_55-New Issue · triplea-game_triplea - Avast Secure Browser](https://user-images.githubusercontent.com/4445057/109590909-9b6fbc00-7ac1-11eb-9819-3351079087a8.png)

### Engine Version

Engine Version: 2..6.57

### Is there anything else we should know?

Was working, halfway, until I ran into the problems mentioned in previous bug reports... got all the way up to "download updated maps", I clicked the X because I couldn't see buttons.

**Comment by DanVanAtta** [comment]
Is this after using the installer? Are you building from source?

**Comment by tvleavitt** [comment]
After using installer.

I now have multiple TripleA instances in the background.

**Comment by tvleavitt** [comment]
Deleting/reinstalling no effect.

Am guessing this is product of corrupted maps, perhaps because these were dynamically extracted during previous release, also have some downloaded maps as well. Noticed various inconsistencies in map file structure when I went through and deleted map.yml from all the maps directories.

**Comment by tvleavitt** [comment]
I renamed the maps folder to DownloadedMapsOld, blank "DownloadedMaps" created, still same problem.

**Comment by tvleavitt** [comment]
triplea.log (was previously 2GB), now 2k:

226  19:25:10.576 [main] INFO  o.t.game.client.HeadedGameRunner - Launching game, version: 2.6.57@e1cf9ee366 
307  19:25:10.589 [main] INFO  o.t.game.client.HeadedGameRunner - Launching game, version: 2.6.57@e1cf9ee366 
339  19:25:10.689 [AWT-EventQueue-0] ERROR o.t.game.client.HeadedGameRunner - input == null!
java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at org.triplea.swing.JFrameBuilder.getGameIcon(JFrameBuilder.java:105)
	at org.triplea.swing.JFrameBuilder.build(JFrameBuilder.java:76)
	at games.strategy.engine.framework.ui.MainFrame.<init>(MainFrame.java:31)
	at games.strategy.engine.framework.ui.MainFrame.buildMainFrame(MainFrame.java:52)
	at games.strategy.engine.framework.GameRunner.lambda$start$0(GameRunner.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
475  19:25:10.757 [AWT-EventQueue-0] ERROR o.t.game.client.HeadedGameRunner - input == null!
java.lang.IllegalArgumentException: input == null!
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1400)
	at org.triplea.swing.JFrameBuilder.getGameIcon(JFrameBuilder.java:105)
	at org.triplea.swing.JFrameBuilder.build(JFrameBuilder.java:76)
	at games.strategy.engine.framework.ui.MainFrame.<init>(MainFrame.java:31)
	at games.strategy.engine.framework.ui.MainFrame.buildMainFrame(MainFrame.java:52)
	at games.strategy.engine.framework.GameRunner.lambda$start$0(GameRunner.java:63)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tvleavitt** [comment]
Looks like it's trying to find an image and failing, or trying to load an image and failing?

**Comment by DanVanAtta** [comment]
yeah, it's a packaging error.
This update caused the issue by changing a lot of file paths: https://github.com/triplea-game/triplea/pull/8934

**Comment by tvleavitt** [comment]
Odd that the "Report to TripleA" button wasn't working. Related?

**Comment by tvleavitt** [comment]
Still an issue with the latest .59 release.

**Comment by DanVanAtta** [comment]
Checked .60, launched okay. Let me know if you see any further issues, should be fixed now.

**Comment by tvleavitt** [comment]
Yes, launched properly.
