### ISSUE TITLE
TripleA Twelve Clans keeps crashing

### ISSUE THREAD

**Issue by cjmagee182** [triplea-game/triplea#8959]
My game continually crashes after a few turns, usually around turn 4 but sometimes at turn 6. Here is the error I get every time:

Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!

Why does this always happen, any way to fix?

**Comment by beelee1** [comment]
@cjmagee182 I responded at the triplea site. If you can provide the save game, engine version and what OS you are using that will help to solve this.

When adding the saved game here, you'll need to put/compress it in a zip file.

**Comment by beelee1** [comment]
Using the save game from 
https://forums.triplea-game.org/topic/2691/game-keeps-crashing/4
The debug shows this

Mar 02, 2021 9:09:02 PM org.triplea.game.client.HeadedGameRunner lambda$initializeClientSettingAndLogging$0
SEVERE: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
	at java.base/java.util.TimSort.sort(TimSort.java:245)
	at java.base/java.util.Arrays.sort(Arrays.java:1515)
	at java.base/java.util.ArrayList.sort(ArrayList.java:1750)
	at games.strategy.triplea.ai.pro.util.ProSortMoveOptionsUtils.sortUnitNeededOptionsThenAttack(ProSortMoveOptionsUtils.java:117)
	at games.strategy.triplea.ai.pro.ProCombatMoveAi.tryToAttackTerritories(ProCombatMoveAi.java:1341)
	at games.strategy.triplea.ai.pro.ProCombatMoveAi.determineTerritoriesToAttack(ProCombatMoveAi.java:335)
	at games.strategy.triplea.ai.pro.ProCombatMoveAi.doCombatMove(ProCombatMoveAi.java:95)
	at games.strategy.triplea.ai.pro.AbstractProAi.move(AbstractProAi.java:139)
	at games.strategy.triplea.ai.AbstractAi.start(AbstractAi.java:514)
	at games.strategy.engine.framework.ServerGame.waitForPlayerToFinishStep(ServerGame.java:537)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:407)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:297)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInternal(LocalLauncher.java:82)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.lambda$launch$0(LocalLauncher.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)

[autosavebeforeendturn.zip](https://github.com/triplea-game/triplea/files/6073377/autosavebeforeendturn.zip)
