### ISSUE TITLE
War of the Relics - Triggers failing on load, NPE, error report upload fails, dialog box appears under other dialog box

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#8976]
2.6.64@e3b6bf53b5: ScrollableTextField#loadImages:128 - java.lang.NullPointerException

Loaded up latest version of TripleA, loaded up WoTR, sequence of triggers fail (see various examples in screenshots). Eventually after clicking through all them, I get an NPE (this error). I try to report it to TripleA, and that fails (see error message). Error dialog pops under the bug report dialog, has to be dragged out before I can click o.k. and dismiss the error report.

## Map
war_of_the_relics-master

## TripleA Version
2.6.64@e3b6bf53b5

## Java Version
11.0.9.1

## Operating System
Windows 10

## Stack Trace
```
Exception: java.lang.NullPointerException
java.lang.Exception
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at games.strategy.ui.ScrollableTextField.loadImages(ScrollableTextField.java:128)
	at games.strategy.ui.ScrollableTextField.<init>(ScrollableTextField.java:41)
	at games.strategy.triplea.ui.ProductionPanel$Rule.getPanelComponent(ProductionPanel.java:432)
	at games.strategy.triplea.ui.TabbedProductionPanel.getRulesPanel(TabbedProductionPanel.java:267)
	at games.strategy.triplea.ui.TabbedProductionPanel.initLayout(TabbedProductionPanel.java:87)
	at games.strategy.triplea.ui.ProductionPanel.show(ProductionPanel.java:108)
	at games.strategy.triplea.ui.TabbedProductionPanel.getProduction(TabbedProductionPanel.java:45)
	at games.strategy.triplea.ui.PurchasePanel$1.actionPerformed(PurchasePanel.java:57)
	at games.strategy.triplea.ui.PurchasePanel.lambda$waitForPurchase$2(PurchasePanel.java:221)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


```

![2021-03-04 23_21_02-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081667-1d214d00-7d41-11eb-9d24-62b930ec4692.png)
![2021-03-04 23_20_27-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081675-23172e00-7d41-11eb-9c96-bb750617c644.png)
![2021-03-04 23_24_54-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081688-290d0f00-7d41-11eb-81b8-1b433d27828e.png)
![2021-03-04 23_24_39-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081705-2f9b8680-7d41-11eb-8444-9936af462f2c.png)
![2021-03-04 23_22_34-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081722-34f8d100-7d41-11eb-8afd-151b862078c3.png)
![2021-03-04 23_21_41-TripleA - War of the Relics](https://user-images.githubusercontent.com/4445057/110081734-3aeeb200-7d41-11eb-8a8c-e1937c28be7d.png)

**Comment by tvleavitt** [comment]
I can't test it, since I've inadvertently submitted too many error reports (was telling me the process failed, but I see them in my inbox), but I suspect this may be because I was leaving the user description field empty, not reading it carefully enough to realize that the screen was a text input for human description of the problem.

**Comment by DanVanAtta** [comment]
@tvleavitt interesting error here. The NPE is coming from loading up/down images for a 'scrollable text field'. It looks like the error should not be possible without missing image assets. Would you mind checking if you can still replicate this problem?

**Comment by asvitkine** [comment]
Given no response since 2021, I'll close this out.
