### ISSUE TITLE
OOM: 2.6.64@e3b6bf53b5: TriggerAttachment#setRemoveUnits:1316 - java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by tvleavitt** [triplea-game/triplea#8978]
## User Description
Occurred when exiting Warcraft Heroes Map after opening and closing Unit Help menu a couple of times.

## Map
warcraft_war_heroes-master

## Log Message
Java heap space

## TripleA Version
2.6.64@e3b6bf53b5

## Java Version
11.0.9.1

## Operating System
Windows 10

## Stack Trace
```
Exception: java.lang.OutOfMemoryErrorJava heap space
java.lang.Exception
	at java.base/java.util.HashMap.resize(HashMap.java:699)
	at java.base/java.util.HashMap.putVal(HashMap.java:658)
	at java.base/java.util.HashMap.put(HashMap.java:607)
	at games.strategy.triplea.attachments.TriggerAttachment.setRemoveUnits(TriggerAttachment.java:1316)
	at games.strategy.triplea.attachments.TriggerAttachment$$Lambda$1322/0x0000000023b84c58.accept(Unknown Source)
	at games.strategy.engine.data.MutableProperty.setStringValue(MutableProperty.java:58)
	at games.strategy.engine.data.MutableProperty.setValue(MutableProperty.java:85)
	at games.strategy.engine.data.gameparser.GameParser.setOptions(GameParser.java:967)
	at games.strategy.engine.data.gameparser.GameParser.parseAttachment(GameParser.java:899)
	at games.strategy.engine.data.gameparser.GameParser.parseAttachments(GameParser.java:833)
	at games.strategy.engine.data.gameparser.GameParser.parse(GameParser.java:210)
	at games.strategy.engine.data.gameparser.GameParser.lambda$parse$1(GameParser.java:134)
	at games.strategy.engine.data.gameparser.GameParser$$Lambda$477/0x0000000022345500.apply(Unknown Source)
	at org.triplea.java.UrlStreams.openStream(UrlStreams.java:73)
	at games.strategy.engine.data.gameparser.GameParser.parse(GameParser.java:129)
	at games.strategy.engine.data.gameparser.GameParser.parse(GameParser.java:108)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel$$Lambda$257/0x000000002093fc40.apply(Unknown Source)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.parseAndValidate(GameSelectorModel.java:110)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.load(GameSelectorModel.java:83)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel$$Lambda$327/0x0000000020d5d458.accept(Unknown Source)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:201)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel.loadDefaultGameSameThread(GameSelectorModel.java:192)
	at games.strategy.engine.framework.startup.ui.panels.main.game.selector.GameSelectorModel$$Lambda$2128/0x0000000025298840.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by asvitkine** [comment]
Closing this as it's pretty old and the code has had a bunch of changes since.
