### ISSUE TITLE
Checkstyle config is not compatible with Checkstyle 8.42

### ISSUE THREAD

**Issue by asvitkine** [triplea-game/triplea#9233]
When trying to use it from IntelliJ, I get the following error:

```
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:473)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TreeWalker is not allowed as a parent of LineLength Please review 'Parent Module' section for this Check in web documentation if Check is standard.
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:140)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:468)
	... 7 more
```

Which seems to be referring to this:
https://github.com/triplea-game/triplea/blob/master/config/checkstyle/checkstyle.xml#L56

**Comment by DanVanAtta** [comment]
Yeah, this is a pain point that we have to use an older checkstyle config.

This PR puts us on a path to being on the latest:
- https://github.com/triplea-game/triplea/pull/7788

A key problem is that the current version we are using has several broken checks. The checks are configured in the XML but are not enforced. This means that when we upgrade to the latest and the checks then become enforced, we then have build failures due to numerous checkstyle violations.

In this issue I proposed we revisit the checkstyle rules: https://github.com/triplea-game/triplea/issues/8655

Overall there has not been that much traction to fix the checkstyle 'problem.' That I think is just largely due to us being an all volunteer team and we've run into differing degrees of time constraints.

Bottom line, I do think this is worth solving. My thoughts are to approach this by minimizing the checkstyle rules. Checkstyle was adopted before we started using spotless, many of the pure formatting rules are redundant. Furthermore, there are some rules which we do not follow and that I also do not think make sense. For example, I would like to see the mark variables as 'final' rule dropped (that is most useful for class variables, but the rule does not apply to them, so it's not that useful). Really bottom line, checkstyle is meant to automate typical and low level code review feedback, so we should gear it towards that. The heuristic should largely be, "would someone comment on this in a code review?". 

The gray area is that various classes and methods do benefit from a javadoc. Without a rule that often does not get written. With a rule, it always has to be written and one often sees then poor quality javadocs that are there mostly because they have to be rather than useful. I think javadoc requirement is probably the most prominent gray area. We could perhaps solve the checkstyle problem by simply removing those rules for now in favor of the ones that are more cut and dry and not redundant to spotless.

@asvitkine do you have any capacity or desire to take the lead on fixing up the checkstyle config?

**Comment by frigoref** [comment]
Is this still an issue, @DanVanAtta?

**Comment by DanVanAtta** [comment]
i believe we have mostly ripped checkstyle out at now if not entirely. We just use spotless now (not quite the same, but almost).
