### ISSUE TITLE
Air unit move arrow bug (1.9.0.0.2471)

### ISSUE THREAD

**Issue by FrostionAAA** [triplea-game/triplea#948]
There seems to be a bug with the arrows when moving to a southern place out of sight of the moving air unit. The arrow seems to shift to an origin point out of the map to the south. It is just a graphical error, and I think the move will be done as normal. I have experienced this in my Dragon War map. Here is a screenshot:
![reddragonmovearrowbug](https://cloud.githubusercontent.com/assets/15268177/16725721/ddaeb1b2-4758-11e6-8848-fb84f00120fe.png)

To recreate and see the bug you can:
•	Start a new Dragon War game (don’t need to select player)
•	Go to edit and add a 6 move dragon to the blue player capital.
•	Exit edit
•	Selects the dragon and scroll south so you are out of visual range of the air unit and you will see the arrow bug.

PS: I have not tested it on any other map, but I guess would occur with WW2 bombers and fighters also.

**Comment by RoiEXLab** [comment]
@FrostionAAA Dangit! I hoped this wouldn't happen... I will push another PR in order to fix this (I need to remove 3 lines of code).
Is there any map allowibg for infinite vertical scrolling?

**Comment by RoiEXLab** [comment]
@FrostionAAA @DanVanAtta #949 Has a Fix!

**Comment by RoiEXLab** [comment]
@FrostionAAA Please try to reproduce your issue... It should be fixed now... If it is, please close this issue!

**Comment by FrostionAAA** [comment]
I am having trouble with testing it out :(
I installed 1.9.0.0.2533
Could not load any of my downloaded maps without getting errors.
So I deleted all downloaded maps and opened TripleA program.
Looked at “select game” and only tutorial was there (as expected).
Then tried to download maps but cant. I am getting this error:

**triplea.engine.version.bin:1.9**
Loading map: tutorial, from: C:\Games\triplea\maps\tutorial.zip
Exception: java.net.ConnectException: Connection timed out: connect
java.lang.IllegalStateException: java.net.ConnectException: Connection timed out: connect
	at games.strategy.engine.framework.map.download.DownloadUtils.getDownloadLength(DownloadUtils.java:24)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.createLabelText(DownloadMapsWindow.java:285)
	at games.strategy.engine.framework.map.download.DownloadMapsWindow.lambda$updateMapUrlAndSizeLabel$55(DownloadMapsWindow.java:272)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.<init>(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.http.HttpClient.New(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at games.strategy.engine.framework.map.download.DownloadUtils.getDownloadLength(DownloadUtils.java:16)
	... 3 more

**Comment by DanVanAtta** [comment]
With the desire to keep issues specific to one topic, moved the download map error to: https://github.com/triplea-game/triplea/issues/967

@FrostionAAA , when you select a map in the download window, it shows the URL of the map, could you include that with the bug report? Second, are you gettng the same error for any map, or just specific ones? I'm wondering if maybe the URL is wrong in some places. If you would, please respond in #967
