### ISSUE TITLE
Lobby join game error: ClassCastException: games.strategy.engine.framework.ClientGame cannot be cast to games.strategy.engine.framework.ServerGame

### ISSUE THREAD

**Issue by DanVanAtta** [triplea-game/triplea#965]
Joining my own game on the 1.9 lobby, hit:

```
Caused by: java.lang.ClassCastException: games.strategy.engine.framework.ClientGame cannot be cast to games.strategy.engine.framework.ServerGame
	at games.strategy.triplea.ui.menubar.TripleAMenuBar.<init>(TripleAMenuBar.java:75)
	at games.strategy.triplea.ui.TripleAFrame.<init>(TripleAFrame.java:280)
	at games.strategy.triplea.TripleA.lambda$startGame$30(TripleA.java:134)
	at games.strategy.ui.SwingAction.lambda$invokeAndWait$241(SwingAction.java:61)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DanVanAtta** [comment]
fixed by PR
