### ISSUE TITLE
Windows Messed Up

### ISSUE THREAD

**Issue by RogerCooper** [triplea-game/triplea#9948]
I having problem where windows are getting messed up. Here is one example.

![image](https://user-images.githubusercontent.com/20504877/147506319-9cf2ff45-20e8-455c-8088-0104d1a4a30e.png)

The error log shows.

3251102 15:45:29.477 [AWT-EventQueue-0] INFO  g.s.e.m.UnifiedInvocationHandler - Blocking network operation performed from EDT
java.lang.Exception: null
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:52)
	at com.sun.proxy.$Proxy16.getPlaceableUnits(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at games.strategy.engine.player.DefaultPlayerBridge$GameOverInvocationHandler.invoke(DefaultPlayerBridge.java:151)
	at com.sun.proxy.$Proxy16.getPlaceableUnits(Unknown Source)
	at games.strategy.triplea.ui.PlacePanel.getUnitsToPlace(PlacePanel.java:249)
	at games.strategy.triplea.ui.PlacePanel$1.territorySelected(PlacePanel.java:58)
	at games.strategy.triplea.ui.panels.map.MapPanel.notifyTerritorySelected(MapPanel.java:490)
	at games.strategy.triplea.ui.panels.map.MapPanel$3.mouseReleased(MapPanel.java:213)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

This happens on one of my computers (the faster one). It has been happening ever since I bought the computer a few months ago. The error usually shows up as duplicated windows. I can bypass the error by saving, exiting TripleA and reloading the scenario.

**Comment by DanVanAtta** [comment]
Are you using 2.6?

**Comment by RogerCooper** [comment]
Yes, I am using 2.6 (on both computers).

**Comment by asvitkine** [comment]
Are you still seeing this?

**Comment by RogerCooper** [comment]
No. It stopped a couple of months ago. I had the same issue with another Java-based program, and that program is also working correctly now. Probably fixed by a Windows or Java update.
